### ISSUE TITLE
Investigate high CPU load on wazokazi

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#1005]
We experience [high CPU loads on wazokazi](https://wazokazi.is/pnp4nagios/index.php/graph?host=pixelated.wazokazi.i&srv=CPU%20load) from time to time. I'll attach graphs about that later.
I'd like to install [elastics metricbeat](https://www.elastic.co/downloads/beats/metricbeat) on wazokazi to get more information about system metrics, and connect it to our [Elastic Stack instance](https://github.com/pixelated/project-issues/wiki/Monitoring#elastic-stack-formerly-elk-installation).

**Comment by varac** [comment]
![image](https://cloud.githubusercontent.com/assets/488213/23753036/3a33441a-04d8-11e7-807e-5dbf665944d3.png)

**Comment by tuliocasagrande** [comment]
@varac about the graph, how the scale works?

Is 1.0 supposed to be 100%? It looks like it is.

How about the warning levels?
```
Warning 20
Critical 40
```

**Comment by anikarni** [comment]
Closed as this is specific to Wazokazi environment, which will no longer be maintained
