### ISSUE TITLE
Error: Attachment with 'None' id

### ISSUE THREAD

**Issue by FrailWords** [pixelated/pixelated-user-agent#1055]
We got the following error on Wazokazi due to the 'id' of the attachment being 'None'.  Following are the specific logs - 

```
C Apr 13 18:18:06 pixelated pixelated-user-agent[7921]: 2017-04-13 18:18:06 [pixelated.resources.mails_resource] ERROR error saving draft: No attachment with id None found!
C Apr 13 18:18:13 pixelated pixelated-user-agent[7921]: 2017-04-13 18:18:13 [pixelated.resources.mails_resource] ERROR error occurred while sending: No attachment with id None found!
```

The actual error seems to be coming from the `_fetch_attachment_contents` method in `mails_resource.py`.

**Comment by deniscostadsc** [comment]
Closing this issue for now. If the problem persist we can reopen.
