### ISSUE TITLE
API should be predictable when handling requests

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated/pixelated-user-agent#108]
Server responds in Json while doesn't expect Json requests.

**Comment by dudadornelles** [comment]
Can we get more details on this?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
