### ISSUE TITLE
Pin the message header when the user scrolls down

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#11]
Notice how the logo at https://twitter.com/pixelatedteam collapses on scroll down (using chrome). We want a similar effect for the mail pane header. End states are shown below:

![collapsed view](https://cloud.githubusercontent.com/assets/3587497/5882095/86517204-a32d-11e4-8a91-699f2773bf30.png)

The solution should work in Chrome, Firefox and IE. Some examples that do work across borwsers here: http://byassociationonly.com/ and http://kaitbos.com/. A how-to here: https://medium.com/@mariusc23/hide-header-on-scroll-down-show-on-scroll-up-67bbaae9a78c

**Comment by albogabriel** [comment]
Issue #410 will handle this.
