### ISSUE TITLE
Optional disable certificate checking in useragent

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#119]
we should have a parameter like "--no-check-certificate" or sth like this to disable cert checking. This would be a quick workaround for cert problems like i experience atm with the dev.wazokazi.is domain.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
