### ISSUE TITLE
make login on activist setup more fancy

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#126]
The user-agent will be started on activists laptop by clicking on an icon somehow.
We need to ask for username/password in this scenario.
Like a little wrapper that asks for credentials and then spins up the user-agent

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
