### ISSUE TITLE
When I click to mark all messages of a tag and go to the next page, the system doesn't allow me to mark all messages of the other pages, clicking in mark all.

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#13]

**Comment by bwgpro** [comment]
Is this something we really want?

**Comment by tiagoferraz** [comment]
We should define the behaviour of the checkboxes. They are weird as the Send button :)
But it is affected by the removal of mailbox All, @albogabriel ?

**Comment by albogabriel** [comment]
If I understand correctly, I think we should allow cross-page selecting, as long as we have a clearer indication of the number of selected messages. 

I'll play around with ideas around that.

**Comment by bwagnerr** [comment]
This is not part of our focus now, we should revisit this when we can validate these changes with users
