### ISSUE TITLE
Autodownload certificate for provider on activist setup

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#152]
*Notes*
* To log in to Pixelated the user shouldn't need to manually download the provider's certificate 
* Should accept automatically if signed by a CA or should prompt for user acceptance if self-signed

*Why*
In order to make it easier for the user to start using Pixelated without compromising security

*Definition of done*
We should be able to delete service/pixelated/certificates and log in into pixelated afterwards (downloading and validating - CA or self - on first use)

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
