### ISSUE TITLE
remove workaroud for soledad debian packages

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#187]
in #172 we created our own debian packages as a workaround for https://leap.se/code/issues/6500

we should remove these packages from our repository as soon as the leap packages work

**Comment by bwagnerr** [comment]
@cz8s @fbernitt Is this solved after the latest packaging changes?

**Comment by cz8s** [comment]
@bwagnerr nope. this issue has to wait until leap has all packages we need.

**Comment by cz8s** [comment]
since we are doing more soledad work now, it makes sense to keep our packages because we need
to deploy the code before the pr is merged and leap has built new packages.
