### ISSUE TITLE
Make docker containers secure/trustable

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#207]
*Why*
Whoever downloads a container from us should be able to trust that it hasn't been tampered with

*Definition of Done*
We generate the package in our servers and can sign it with our key.
The package is downloaded from our servers or distributed when Pixelated is installed (i.e. dockerhub is no longer needed)

**Comment by bwagnerr** [comment]
This is not part of our focus, specially because MAYBE we'll move away from docker with the multi-tenant setup, so closing this one
