### ISSUE TITLE
Allow bulk tagging for existing tags

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#21]
In order to avoid selecting and tagging messages one by one, it should be possible to assign the same existing tag to multiple messages at once.

@albogabriel @sahrosa to provide UX info.

Given that many messages are selected, when the user chooses to assign an existing tag to them, all messages become tagged.

Out of scope:
Removing messages from the inbox
Removing an assigned tag from a set of messages
Assigning a new tag (non-existing yet) to multiple messages

**Comment by re-nobre** [comment]
@SweetVirginia

**Comment by re-nobre** [comment]
I talked with @SweetVirginia and we will analyse all the UX proposals in a different place and create the issues when we will work on it.

For all the UX/UI proposals and feedbacks, take a look [here](https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

I'm closing this issue now.
