### ISSUE TITLE
Use top left logo to indicate loading events

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#238]
Edited by @albogabriel

![image](https://cloud.githubusercontent.com/assets/350155/13222332/498337dc-d95e-11e5-9f36-4f96d5d31ebf.png)

We want to use an animated version of the logo to indicate a general loading status. 

Some of the current "loading" event triggers

* After clicking on a shortcut on left bar
* On editing a mail/saving draft
* After clicking on an email to open it
* After hitting 'search'

## Logo animation 

The animation should look roughly like this: http://codepen.io/albogabriel/pen/QNwxoW

The color should be the logo color lighten by 20% (achieved with the sass lighten function)

**Comment by fjaguero** [comment]
Is this ready to be worked on?

**Comment by giovaneliberato** [comment]
@fjaguero probably not since the new logo on the user agent is orange now. Any updates @albogabriel?

**Comment by albogabriel** [comment]
In fact, that is ready to be picked up, @fjaguero and @giovaneliberato - as long as it's made on the svg. 

The logo is currently (svg) coded into the markup and its color is set using css, so using the sass lighten function making whatever color is the fill color 20% lighter, that will be "color-agnostic" - making it automatically adaptable to whatever the color theme is. 

By that, I mean we could make the lighter bits of the logo have their fill color defined as **lighten($logo_color, 20%)** 

Let me now if I can help in any way :)

**Comment by fjaguero** [comment]
Great. I will have a look at how to listen to the loading events and make the SVG animation.

**Comment by albogabriel** [comment]
Currently slicing the svg to set it up for CSS interactions.

**Comment by albogabriel** [comment]
Added sliced svg file here: https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/images/logo.svg

I've actually created paths on top of the existing logo. The paths are named "clock#", where # is a number from 1-6. They can be renamed or "none-displayed" until the animation is used.

**Comment by albogabriel** [comment]
CSS animation: http://codepen.io/albogabriel/pen/QNwxoW

**Comment by pereiragislene** [comment]
Currently we have spinning working for the following cases:

1. Switching between mail boxes
2. Opening a mail message
3. Opening a draft
4. Saving a draft

I've put a timeout on the stop spinning logo event in order to make the logo finish at least an entire cycle.

After some discussion, we've decided not to have the spinning function for the the empty Compose box.

**Comment by albogabriel** [comment]
Update the issue to remove the compose box activation.

I think i's a good idea to to also indicate the loading event when searching, as you've suggested earlier, @pereiragislene

**Comment by re-nobre** [comment]
The logo is fine to me.

But I saw one small strange behavior. 
When I opened an email, first I saw the header and only a few minutes later I saw the body of the email.
The loading on the logo just appear during the header loading. 

On the console I got this error with sandbox.
<img width="1269" alt="screen shot 2016-03-21 at 2 14 28 pm" src="https://cloud.githubusercontent.com/assets/2657059/13927303/0883ffbe-ef70-11e5-880e-02fa40982eef.png">

@felixhammerl Do you know if this is a error related with the iframe new behaviour?

**Comment by pereiragislene** [comment]
The logo stops loading before the message is loaded because now we use an iframe and it takes more time to be fully rendered. We decided to create another issue to add a gray loadiing logo inside the iframe area while it's being loaded (@albogabriel will do it).

Also, I'll create another issue to check this issue with the opensans.css file, which is related to the iframe.
