### ISSUE TITLE
Display current user pub key fingerprint on user agent

### ISSUE THREAD

**Issue by dudadornelles** [pixelated/pixelated-user-agent#292]
It is important for the user to know its own pub key fingerprint in case it needs to send its key to somebody (so they can verify it later).

A way of doing it is as with `keymanager.get_from_cache('currentuser@mail', OpenPGPKey)` and then get the fingerprint from the result.

Ideas on how to display that?

**Comment by albogabriel** [comment]
This blog post shows some experiments on how to display fingerprints: https://samirnassar.com/blog/2014-07-07-experiments-visual-pgp-fingerprint-representation

**Comment by pameck** [comment]
I tried the link @albogabriel suggested, it's broken but this will work: 
https://web.archive.org/web/20150212193157/https://samirnassar.com/blog/2014-07-07-pgp-fingerprint-experiments

**Comment by cacarrara** [comment]
I've already QA it and it's working properly. Thanks for great work on it @zaraG and @felixhammerl :+1: 

However, before passing it to Ready to Launch it would be better listen more opinions about how the fingerprint is being showed. Also, it would be nice if @albogabriel share some thoughts with us.

Fingerprint is currently showed on user settings box:
![image](https://cloud.githubusercontent.com/assets/348237/14338301/589966d6-fc4c-11e5-966d-38e7220173d6.png)

My thoughts about it are:
* There isn't a label or anything else describing to user what is that information. It's always good remember our [personas](https://pixelated-project.org/2015/07/15/personas/). Specially our main current persona, Olivia Organiser.
* The fingerprint is using same style of user email. Semantically it can tell that both information has same importance to the user. But couldn't be true if we look the the personas again.
* The fingerprint can be considered an information for advanced users? If so, it also cannot have the same importance of user email.

**Comment by albogabriel** [comment]
I really like @cacarrara's design. IMHO, you should go ahead with it :)

Two small, semi-related considerations:
- there's an [open request on font-awesome](https://github.com/FortAwesome/Font-Awesome/issues/4431) for them to add a fingerprint icon there. This would also be in sync with what folks at GPG summit have talked about (a fingerprint icon where there's a key). I don't think it's urgent (or even a reason to stop this issue from being launched), but while they don't implement it, I can come around with a custom fingerprint icon.
- this dialog's background opacity seems to be confusing, now that we have more information over it. I can play around with less transparent versions and pull request it.

Either way, I'd definitely push those changes and consider it done :)

**Comment by cacarrara** [comment]
Thanks for opinions folks :+1: 

So, as we talked here and on our standup, I'm going to lunch it with my design proposal for now. We can totally reopen it or work on new task to improve the UI for these infos (suggestions open).
