### ISSUE TITLE
User can permanently delete email from All

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated/pixelated-user-agent#298]
On All mailbox the user can delete an email permanently if the selected email is on trash by mistake. The system directs the user to believe that the email will be moved to Trash mailbox

**Comment by bwgpro** [comment]
This seems to be working, when you delete a trashed mail from all it says deleted permanently.

Do you think we should have an indication for trashed mail on all/search as we have for drafts @albogabriel ?

**Comment by tiagoferraz** [comment]
Remembering that the button on All only says to "Delete" instead of "Delete Permanently" , though the user is warned *after* it was permanently deleted. In conclusion, Pixelated behaves differently in this case than it teaches the user.

**Comment by albogabriel** [comment]
That's a good point, @bwgpro. I'd start with something as simple as this:

![issue298](https://cloud.githubusercontent.com/assets/350155/6969498/8a80fbbc-d945-11e4-9486-f3e84eda7a8a.png)

Good enough?

I'm going to create a story for removing the "all" tag from the UI, which should prevent this error from happening, if I understood this correctly. For now, I think fixing the bug @tiagoferraz mentioned (treating delete emails on "all" the same way we treat deleted emails on trash) should be the best way to go.

**Comment by giovaneliberato** [comment]
@albogabriel I was using the try environment and I first thought that this icon was a button to permanently remove the emails. What do you think about a label "trash"?

**Comment by albogabriel** [comment]
That can be a good alternative, @giovaneliberato. I'm assigning this card to myself, will play around with possible solutions and update this issue ASAP.

**Comment by albogabriel** [comment]
For now, what we can try is to lighten up the icons for trash, drafts and attachments in the mail list regardless of it being read or not.

![image](https://cloud.githubusercontent.com/assets/350155/11190316/f49901cc-8c7b-11e5-9f81-fb10c43b68ab.png)

**Comment by cz8s** [comment]
Does it make sense to search in deleted emails? Why should I delete emails then in the first place?

**Comment by pereiragislene** [comment]
@cz8s: I agree with you, but in some cases the users might want to search their deleted messages as well. 
I've discussed about this with @albogabriel and we thought it would be good to remove the deleted mails from the search results by default, but show something like "Some messages on your trash box match your search criteria. Click here to view them". What do you think?

**Comment by cz8s** [comment]
That sounds great

**Comment by jeffhsta** [comment]
This issue is done, we can launch it
