### ISSUE TITLE
Counter of drafts should be updated at same time of middle pane 

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated/pixelated-user-agent#299]
The update of the counter and the middle pane when a draft is sent occurs in different moments, so when a email is sent, the counter does not reflect the correct number of emails on draft

**Comment by tiagoferraz** [comment]
![screen shot 2015-02-19 at 6 20 41 pm](https://cloud.githubusercontent.com/assets/2946807/6275133/ff39ccc0-b863-11e4-81c5-862929465dd3.png)

**Comment by albogabriel** [comment]
It only updates the counter when the UI refreshes (i.e., the "Loading" toast message pops up). If we somehow triggered the refresh when we sent it, it could work (but this is an implementation detail ;))

**Comment by neissi** [comment]
There is a delay to UI be updated, is around 6..12 seconds. Since I press to send an draft until the counter reflect the right number.

**Comment by fbernitt** [comment]
Waitingt for #512

**Comment by re-nobre** [comment]
waiting for #512

**Comment by bwagnerr** [comment]
@neissi @fbernitt  currently we make a request to update the counter. I think it should be fairly easy to just decrement the counter directly and then ask to update the counter, that way we have fast feedback and we guarantee consistency after a short delay, what do you think?

**Comment by giovaneliberato** [comment]
@bwagnerr +1

**Comment by neissi** [comment]
@bwagnerr  Sounds good!

**Comment by neissi** [comment]
I did Qa on #512 and after that, delay on counter still happens.

**Comment by re-nobre** [comment]
As #512 didn't fixed it, I'm unblocking this issue.

**Comment by giovaneliberato** [comment]
Did QA on this issue. It works and it's better, but isn't being updated ~exactly~ on the same time than the middle pane. This could have a bigger delay if the internet is slow. 

Do we want to invest a big amount of time to fix this? @mnandri @albogabriel @fbernitt

**Comment by neissi** [comment]
For me, when I try send a email, now looks more fast the update.
