### ISSUE TITLE
As a person concerned about security I want the Content-Security-Policy header to be set.

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#304]
Background:

This header specifies from which sites resources can be downloaded (https://en.wikipedia.org/wiki/Content_Security_Policy). 

This might for example help with some kind of injection attacks where some malicious JavaScript code is downloaded from an external site because of some formatting/escape problems.

There is a special report only option, which might be helpful to identify which external stuff we unknowingly depend on. 

Content-Security-Policy-Report-Only: policy 

Requirements:
When I open any user-agent URI 
Then I get the Content-Security-Policy header as well as the Content-Security-Policy-Report-Only header

**Comment by varac** [comment]
i see the importance of this, but i don't see this as priority according to our focus for getting wazokazi up and running. we should add this feature after imo.

**Comment by bwagnerr** [comment]
This is quite straightforward to implement and nice to have even though it it not part of our priority. I'll make this a beginner's issue because it is a nice introduction to the code

**Comment by giovaneliberato** [comment]
Hey folks, 
 
I implement that creating a Pixelated[Site](https://twistedmatrix.com/documents/8.2.0/api/twisted.web.server.Site.html) class and a custom requestFactory to ass the CSP header to all requests.

Also, I saw that the CSP header has a lot of [options](http://content-security-policy.com/), so I'll need help with all this fine tunes. I've tried `Content-Security-Policy: default-src 'self'` but it seems to break some things in the agent. Any recommended options? @bwagnerr @fbernitt

**Comment by giovaneliberato** [comment]
Just as update, I used `Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'` and it works well. It blocks another domain includes (js, css, images) and inline js (onclick included). Inline CSS still permitted due to modernizr changes. What do you think?

**Comment by cz8s** [comment]
these headers do not get forwarded by the dispatcher.
Do we care?

**Comment by neissi** [comment]
was created a new card for that #105
we'll talk about after finish stuff related to migration and wazokazi.

**Comment by giovaneliberato** [comment]
@neissi Is this issue number correct?
