### ISSUE TITLE
Implement protection to CSRF attacks.

### ISSUE THREAD

**Issue by dudadornelles** [pixelated/pixelated-user-agent#305]
This way we can make it impossible for malicious scripts on different websites to get/post to the User agent.

A possible way of implementing this given we are using REST/JS rich client would be implementing Stateless CSRF protection - Double submit pattern: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookies.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
