### ISSUE TITLE
Mailbox changes should have a limited impact on contacts suggestion

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#307]
Today if we:
* Delete a bounce mail --> bounced contact comes back to suggestion
* Delete a valid mail --> suggestion is lost

So, we need to store the contacts list somewhere (soledad?) to control and limit unwanted side effects.
Related: #174

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
