### ISSUE TITLE
Internally generated bounces aren't recognized by suggestions filter

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#308]
See: #174 and #249 
The bounce generated internally doesn't contain specific headers to be consider during suggestions filtering.
This is simple to fix (index the error message as bounce), but we need to verify what is the underlying error and if the error is persistent or temporary.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
