### ISSUE TITLE
Addition of new emails to mail list should not change user position

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated/pixelated-user-agent#317]
## Why
The user position on mail list is displaced by new emails. When new emails arrives, they are added to the top of the list, pushing down the user.

## Definition of done
* When a user has many old emails on his or hers mail list, and a new email arrives, the may list will not move (you still see the same emails)
* If the user scrolls up after receiving emails, than you will see it. 
* If you have one email selected and an email arrives, the originally selected message should remain selected

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
