### ISSUE TITLE
Fail gracefully on unsupported encoding

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#325]
See #312 

7bit/8bit encoding support was added after a critical error during mail decoding.
We need to fail gracefully, log the error and keep running if a unsupported encoding appears.

Definition of done
=================
Given that we received a new (invalid or not) encoding, those behaviors are expected:
* Log that there is no support for this encoding as an error.
* Keep processing other mails (do not throw out exceptions for this)

**Comment by bwagnerr** [comment]
Considering we are migrating to the Leap mail API this is supposed to be checked there (we would only consume the message after processing). Closing this one
