### ISSUE TITLE
It should not be possible to use just spaces as a valid email address

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated/pixelated-user-agent#326]
## What
Pixelated understand just spaces in the To: fields as an email the user typed. It does not send emails, but ask the user to verify the addresses informed.

## How to Reproduce
type a series of spaces on To: Cc: or Bcc: fields and press Send. There are other ways of forcing when the field loses focus , but it's hard.

## Done
Pixelated should ignore string of spaces as valid address. 

## Print Screen
![screen shot 2015-03-16 at 3 41 49 pm](https://cloud.githubusercontent.com/assets/2946807/6673755/5227a134-cbf4-11e4-9023-fd25a8c4265e.png)

**Comment by re-nobre** [comment]
It was fixed!
