### ISSUE TITLE
show currently used version

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#332]
## why
when users send us bugreports of if we find a bug in
the user-agent, it would be nice if it would be easy to find out which version of the user-agent is currently used.

## definition of done
when I see the user-agent in the browser, it is easy for me to see which version is used

**Comment by cz8s** [comment]
maybe show the pipeline build-number and the last commit?

**Comment by bwagnerr** [comment]
We show the last commit in all the dev environments. We don't have version numbers for now, and as much as I would like to have them to facilitate debugging, it is not part of our focus right now. Closing this
