### ISSUE TITLE
Validate that file parameters passed to pixelated-user-agent script exist beforehand

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated/pixelated-user-agent#362]
Why
===

Currently, when running the pixelated-user-agent script, we can pass --config, --sslkey, --sslcert and --leap-cert which are files. It would be good to verify that those files actually exist before we move on with the server startup.

Definition of done
=============

When I pass a bad file path, the user-agent should immediately fail to start up and tell me which of the parameters was wrong.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
