### ISSUE TITLE
Remove encryption status from sent emails while we can't display accurate ones

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#364]
## Why
Currently, we're displaying a "not encrypted" status for all sent emails, despite of their actual status. story #365 is supposed to handle that, but meanwhile, we don't want to display any information there because it would be inaccurate.

Current:
![image](https://cloud.githubusercontent.com/assets/350155/7054533/8c43d67c-de13-11e4-8695-cbaa650e84b6.png)

Desired: (something like this)
![image](https://cloud.githubusercontent.com/assets/350155/7054826/cba8e56c-de15-11e4-97f3-2d458a0114ab.png)

## Definition of Done
Given I access the emails on my 'sent' tag
When I open any email
Then I see no indication of encryption status on its header.

## Open Questions
1. Does signature status make any sense to be displayed from the sender's point of view?

**Comment by albogabriel** [comment]
Could we move this to "ready"?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
