### ISSUE TITLE
Display the correct encryption status for sent emails

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#365]
## Why
(Currently, we're displaying a "not encrypted" status for all sent emails, despite of their actual status. After story #364 is played, there will be no indication of status whatsoever) 

As a user I want to see the encryption and signature status of the emails I have sent so I can be confident that they were encrypted or not.

The statuses are the same as the received emails ("Encrypted", "Not encrypted"), similar to the screenshot below:

![image](https://cloud.githubusercontent.com/assets/350155/7055129/916b71ec-de17-11e4-9d6a-b03590a73c6a.png)

![image](https://cloud.githubusercontent.com/assets/350155/7055149/bbb941b8-de17-11e4-8418-bba7a5c5c22f.png)

## Definition of Done
Given I access the emails on my "sent" tag
When I open an email I have sent encrypted
Then I see the "Encrypted" status in green on its header.

Given I access the emails on my "sent" tag
When I open an email I have sent not encrypted
Then I see the "Not encrypted" status in orange on its header.

## Open Questions
1. Seems like LEAP/Bitmask won't allow that right now, so there might be an extra development complexity involved. @bwgpro might have more details on this
2. Does it make sense to also mention signature status?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
