### ISSUE TITLE
Allow user to delete emails from recipients inputs

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#377]
## Why

As a user I want to be able to easily delete an email address I have entered on the recipient inputs so I don't have to erase them all or do it navigating with the keyboard.

## Definition of Done

When I enter two email address on the same recipients input field (to, cc or bcc)
And I click on the "x" to remove one of them\
Then the email whose "x" I clicked is removed from the list.

## UI sketch
![image](https://cloud.githubusercontent.com/assets/350155/7145292/9415ab66-e2c1-11e4-8b02-961a10f8d923.png)

Hovering over the X:
![image](https://cloud.githubusercontent.com/assets/350155/7145504/f9b265a8-e2c2-11e4-9afd-0f8fa9adc35d.png)

(just like the one we already have when hovering over a tag)

**Comment by SamuelToh** [comment]
Pull request#419 created. Please review.
