### ISSUE TITLE
Use official certificate on dev.pixelated-project.org

### ISSUE THREAD

**Issue by GavinSchalliol** [pixelated/pixelated-user-agent#379]
**AS** a new user navigating to dev.pixelated-project.org
**I WANT** to not see insecure connection warnings for server-signed certificates
**SO THAT** I am not confused about whether my connection is secure.

# Background
When following the link on the user agent wiki page to the Dev Provider, new users are shown a warning stating that the certificate is not trusted. For new users who are exploring Pixelated, seeing these warnings on a secure email service can be discouraging.

Using a properly signed certificate is a suggested solution. The most important thing is that the user does not see this warning.

# Steps to reproduce
1. Navigate to dev.pixelated-project.org
2. Observe certificate error

# Acceptance Criteria
**GIVEN** a user wanting to try the Pixelated user agent
**WHEN** they navigate to the dev.pixelated-project.org environment
**THEN** they are not shown a certificate error
**AND** a valid, signed certificate is served.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
