### ISSUE TITLE
Save search to left pane

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#38]
"Your saved searches" - Ad hoc tagging

@olabini: Unclear about where we save information about saved searches and other configuration information for a specific person. Maybe this belongs in the persona management on the server side.

Saved search should probably show up below the Default folders but above the tag-folders. Thoughts from UX on this?
We might also consider being able to expand the list of saved searches if there are many of them, like GMail allows you to do with Folders.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
