### ISSUE TITLE
connecting to provider without dns fails

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#380]
for testing it is important to be able to connect to a leap provider that does not have a valid domain and/or is not in the dns. But if I give the user-agent an IP to connect to,
it fails.

##  Definition of done
The user-agent should be able to connect to a leap provider specified by IP address

Problem: I don't even know if it is possible because
the platform might redirect http requests to an IP to a hostname ...

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
