### ISSUE TITLE
reloading breaks ui

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#381]
when hitting "reload" multiple times while the user-agent is loading (the grey loading screen), I can break the ui.
I will eventually see a grey screen without the pixelated icons, and after another reload, the user-agent interface with some missing icons/links and lots of js errors

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
