### ISSUE TITLE
Keep input label always present when composing an email

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#384]
As a user I want a constant indication of the input field I'm filling so I won't be confused with the order of inputs when composing a new email.

## Why

Currently, when the user starts typing on "subject" or "body", the placeholder text disappears, which doesn't help preventing input errors:

When selecting the subject input:
![image](https://cloud.githubusercontent.com/assets/350155/7326689/c386432c-ea9d-11e4-9185-4a77a8ef587a.png)

After starting to type, the placeholder is gone:
![image](https://cloud.githubusercontent.com/assets/350155/7326702/d9389616-ea9d-11e4-9875-051b3e469ec7.png)

If we make the placeholder always present, there would be fewer errors. Plus, the transition could reinforce the order of filling we're trying to reinforce (subject and body, then recipients, instead of the opposite).

## Definition of done
Give I am a user on the compose email form
When I click on "subject" and I start typing
Then I see the "Subject" label transition to the top of the input and remain there as I fill it.

Give I am a user on the compose email form
When I click on "body" and I start typing
Then I see the "Body" label transition to the top of the input and remain there as I fill it.

## UI (or "what it roughly could look like")

When starting to type, the subject label transitions to the top of the field and gets a reduced font-size:
![image](https://cloud.githubusercontent.com/assets/350155/7326858/e265f9ee-ea9e-11e4-8450-5ee4d5478b12.png)

Same thing would happen on "body" (not search, since there's already the magnifying glass icon there to indicate its purpose).

For the approximate transition behavior, please refer to the float label library below.

## Implementation details
This library implements something similar: http://mds.is/float-label-demo/

**Comment by neissi** [comment]
There are JS tests for this functionality, and they are passing;
Was used something similiar as http://mds.is/float-label-demo/;
The fields subject and body in compose, also inside draft mailbox  were implemented like the UI example.
