### ISSUE TITLE
Add tooltips with more info about encryption and signature statuses

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#388]
[EN] This issue is part of the Pixelated challenge at FISL 2016. Make a pull request to solve until the end of FISL and receive a gift!

[PT-BR]: Essa issue é parte do desafio do Pixelated no FISL 2016. Faça um pull request resolvendo-a e receba um brinde!

---
## Why

As a user I want to have more information about the encryption and signature statues so I can understand in more details what is happening. 
## Implementation

We want to have tooltips that, when hovering the short messages below, will pop up the longer messages, like this:

![image](https://cloud.githubusercontent.com/assets/350155/8232933/83adcf2c-15a9-11e5-9bb6-d1e4c32a74b1.png)

See on the bottom the full message mapping. For this story, this is the mapping that must be done:

![image](https://cloud.githubusercontent.com/assets/350155/8233524/192c2af0-15ad-11e5-8212-0682faa82b71.png)

Styling is similar to how [Foundation does it](http://foundation.zurb.com/docs/components/tooltips.html). Sorta like this:

![image](https://cloud.githubusercontent.com/assets/350155/7401449/7684419a-ee9a-11e4-8216-93535a4a79b0.png)

(And the way its done on #411)

Using foundation, which we already do for the rest of the app, should speed up a lot this ticket.
## Definition of done

All short messages have a corresponding tooltip with a longer message, as in the picture above.
## Attachments:

This is the full message mapping:
![image](https://cloud.githubusercontent.com/assets/350155/7399900/6865d746-ee8f-11e4-82d5-6d06ec47164b.png)
For all the "Unreliable signature" ones, we must have the same message: "Signed with a key that is either expired or revoked." We will be able to differentiate the statuses for signature after #316 is implemented.

**Comment by rdoh** [comment]
Will we now be able to differentiate the statuses for signature as #316 is closed?

**Comment by cz8s** [comment]
sorry, but #316 didn't fix everything. we still do not get enough information for displaying all the information. quoting @bwagnerr: to go further on this now we'll have to fix it in Leap mail.

**Comment by bwagnerr** [comment]
@SweetVirginia This problem goes with the tooltip problems that we received on feedback

**Comment by felixhammerl** [comment]
Further information:

* [Build Toolchain](https://github.com/pixelated/pixelated-user-agent/wiki/Build-Toolchain)
* [JS Architecture](https://github.com/pixelated/pixelated-user-agent/wiki/JS-Architecture)
* [CSS Architecture](https://github.com/pixelated/pixelated-user-agent/wiki/CSS-Architecture)
* [i18n](https://github.com/pixelated/pixelated-user-agent/wiki/Internationalization)

**Comment by tayanefernandes** [comment]
We created a issue just to add a tooltip explaining what encryption and signature statuses are. #828
