### ISSUE TITLE
New mails should be shown even if I receive a corrupted mail

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#399]
Why
===

If a mail gets corrupted or we don't have all the parts that compose it yet, I should still be able to see all 
other mails and receive new ones

Definition of done
===

I want to keep receiving mails even I have a problem with one specific mail

Notes
===

We do know that the mail processing loop breaks if any referenced document cannot be found

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
