### ISSUE TITLE
Make our whoosh usage more friendly to Twisted

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#404]
Whoosh relies on usual blocking calls to read/write index and this leads to performance hits on our Twisted code.
[There is a solution on their website](https://pythonhosted.org/Whoosh/api/writing.html?highlight=async#whoosh.writing.AsyncWriter) and it should be easy to implement here. This will reduce locking and *maybe* get rid of issues like #330 #218 #194 

However, since we implement our own file storage in order to protect data at rest, we have the option to also optimize writing. [See more](http://twistedmatrix.com/documents/8.1.0/api/twisted.internet.fdesc.html). It would be great since there will be no blocking at all, although it will also be way harder to implement. Another option would be using workers or gevent. Difficulty, performance gain and resource consumption should be weighted here.

Definition of done
===================
* We know how much bad it is now, what changes are possible and their viability.
* Changes, if any, are tested against [previous issues](https://github.com/pixelated-project/pixelated-user-agent/issues?utf8=%E2%9C%93&q=whoosh) and profiling done as way to prove that it got better.

**Comment by bwgpro** [comment]
Gevent and twisted are exclusive, they have the same purpose and wouldn't make sense. Any worker we create for this should be twisted too, because any query of mails or values return deferred anyway.

**Comment by shyba** [comment]
Actually, they [integrate quite well](https://github.com/jyio/geventreactor).
There is even a reactor using gevent, although its not the case.
The purpose of citing gevent is in the case where the solution involves threading, so, instead of running it using a real thread it would make more sense to use gevent's Greenlet.
See: [Lightweight pseudothread](http://gevent.org/intro.html#lightweight-pseudothreads)

**Comment by shyba** [comment]
Please test this last change with whatever load you can think of.
I tested using profiler from previous issues and apache benchmark to stress (100 concurrent), but more tests are possible.

More optimizations are still possible.

**Comment by neissi** [comment]
@shyba How can I do qa of this? Thanks in advance!

**Comment by shyba** [comment]
I would just run contacts performance tests and see if any Lock issue is raised (that was a previous issue).
This commit is so old that if search was broken we would already know by now. I can only think of Lock issues related to this... In terms of performance, not locking a real thread is already a good win.
We can catch up on this tomorrow.

**Comment by neissi** [comment]
Performance contact tests are ok.
User-agent works without any look issue ( exception, error)
