### ISSUE TITLE
Display logged in user address

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#411]
[EN] This issue is part of the Pixelated challenge at FISL 2016. Make a pull request to solve until the end of FISL and receive a gift!

[PT-BR]: Essa issue é parte do desafio do Pixelated no FISL 2016. Faça um pull request resolvendo-a e receba um brinde!

*****

*Note: Issues #413 and #25 also rely on having the user settings window, created in this story.*

As a logged in user
I want to see what account is logged in at the moment
So I know what account I'm using

---

For this issue, we want to create a new item in the sidenav - the "User Settings" - which opens a pop up with the logged in email.

This pop up will later be used to show more information, such as user fingerprints, color theme selection, etc. - all to be handled by other stories.

## Mockups ##

Collapsed view
![image](https://cloud.githubusercontent.com/assets/350155/8136536/29ce9224-1113-11e5-8075-f17a1f1a4be9.png)

Expanded view
![image](https://cloud.githubusercontent.com/assets/350155/8136546/33686b0c-1113-11e5-8547-8fae898100f6.png)

On click:
![image](https://cloud.githubusercontent.com/assets/350155/8136550/42dc1caa-1113-11e5-875d-666e60c3ad00.png)

**Background color:** #3E3A37 (opacity 90%)

**Fonts:**
- Open sans regular for the header (Color: #FFFFFF)
- Open sans light for the email address(Color: #FF9C00)

- Font awesome for the icons (Color: #FFFFFF - Check [their cheatsheet](http://fortawesome.github.io/Font-Awesome/cheatsheet/) for more details)
    - Keyboard: fa-user  (Will be changed later for a custom one) 
    - Close: fa-close

**Comment by giovaneliberato** [comment]
I found this edge case. When scrolling, the user setting box moves along with the mail list. @pereiragislene @jeffhsta 
I can take a look on it. [CSS is awesome!](http://www.tivix.com/uploads/original_images/css_is_awesome.png)

<img width="1279" alt="screen shot 2015-12-07 at 3 45 43 pm" src="https://cloud.githubusercontent.com/assets/2964631/11634982/e36c98b6-9cfa-11e5-8295-10689639b4b6.png">

**Comment by pereiragislene** [comment]
@giovaneliberato: nice catch! :+1:
Let us know if you need help. Thanks.

**Comment by fbernitt** [comment]
Looks good to me now. Settings window remains open until its manually closed, though. Is this intended?

**Comment by cz8s** [comment]
to make the window go away , I have to cklick the little x or the icon that opens the window.

**Comment by pereiragislene** [comment]
@fbernitt, @cz8s: have you tested it locally after cleaning the cache? 
The user settings box should be closed when clicking in any other part of the screen.

**Comment by bwagnerr** [comment]
@pereiragislene tested here on wazokazi, doesn't work too :(

**Comment by fbernitt** [comment]
Same here, even after cleaning the cache. (Also have the same behaviour with disabled cache in chrome)

**Comment by cz8s** [comment]
just checked on wazokazi and it works there. first klick opens the window, klicking somewhere else closes it.
