### ISSUE TITLE
Switch recipients position on compose screen

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#414]
As an email user
I want to see the recipients input fields on top
So I can continue writing my email while I wait for the key lookup to end 

## User Interface ##
![compose](https://cloud.githubusercontent.com/assets/350155/8214393/46da51e2-14ff-11e5-9688-0f5e6a138821.png)

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.

**Comment by re-nobre** [comment]
Now, this issue is part of our goal, so I'm reopening it! :)

**Comment by fbernitt** [comment]
The recipients are now on top of the screen but when I click on compose the Subject line has the focus. Is this intentional? I would expect that the top most input field has the focus?

**Comment by pereiragislene** [comment]
Moving it back to Development to fix the focus inconsistency.

**Comment by albogabriel** [comment]
The additional space around the "to", "cc" and "bcc" will be handled on #504

Closing this :)
