### ISSUE TITLE
Extract stories for migrate to new LEAP data model

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#420]
## Why 
We are working on the migration to the LEAP libraries HEAD code.
After fork their repositories we need to make the Pixelated code works with their new data model.

## Definition of done
The features list below need to work with the new data model. (Each one has its definition of done)

## Note
We discovered that this issue is big and we can split it in small ones. So, here is how we split:
#421 Migrate maintenance.py to new data model
#422 Find keys using new data model
#423 Show single mail using new data model
#424 Move mail into different mailboxes
#425 Edit drafts using new data model
#426 List mails using new data model
#427 Add mails to search index using new datamodel and search for them
#428 Send mail using new data model

**Comment by re-nobre** [comment]
We split this issue in smaller ones so I will closed it.
To you know the status of migration, please take a look on the new issues listed above.
