### ISSUE TITLE
Edit drafts using new data model

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#425]
## Note
This issue is part of #420

**Comment by fbernitt** [comment]
Depends on #429

**Comment by shyba** [comment]
![screenshot from 2015-08-24 19 02 16](https://cloud.githubusercontent.com/assets/1302078/9453746/d56e36bc-4a92-11e5-9846-e5ea4c1d9ec6.png)
Duplicated. :/

**Comment by kaeff** [comment]
I noticed this initially, but couldn't reproduce it after first sight. Do you see this happening regularly?

**Comment by shyba** [comment]
This is not easy to reproduce, will take some time to spot the real issue.
Investigation should go on with #443
