### ISSUE TITLE
Add mails to search index using new datamodel and search for them

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#427]
## Note
This issue is part of #420

**Comment by kaeff** [comment]
Current status: All test passing now, but we need another bugfix to get to green.

Through exploratory testing we found that multipart / base64 are not decoded correctly. This is a upstream bug in leap_mail, which we are reporting and fixing now.

**Comment by kaeff** [comment]
Here's the mentioned pull request with more description: https://github.com/leapcode/leap_mail/pull/195
