### ISSUE TITLE
Send mail using new data model

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#428]
## Note
This issue is part of #420

**Comment by shyba** [comment]
![screenshot from 2015-08-24 17 49 15](https://cloud.githubusercontent.com/assets/1302078/9452075/aa164fc2-4a88-11e5-9095-06be6de62a9a.png)

**Comment by shyba** [comment]
Unrelated discoveries: https://github.com/pixelated/pixelated-user-agent/issues/438
Why unrelated: previous mails from this account (pre-migration) are also being shown as old.
Also, many of this happens under leap.mail. It should worth a look in there.
