### ISSUE TITLE
Cleanup: Remove search engine and from mail service

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#430]
MailService still has some references to search engine, but it no longer needs it.

Requirements:
- search engine related code got removed from mail service

**Comment by shyba** [comment]
[reverted]
This card doesn't make sense anymore.
The main reason was that mail_service didn't need a search_engine, but after checking it is really needed for now.
Creating a search_service would be out of scope for this card and doesn't relate to a "cleanup".
I also don't see a benefit on creating a new service within current goals.

**Comment by pereiragislene** [comment]
A card for creating a search_service will be added when needed. Closing this one as it's unrelated.
