### ISSUE TITLE
Generic error callbacks for all twisted resources

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#431]
During the migration to 0.7 we saw that a lot of problems were not logged because there is no generic 'catch all' errback our twisted handlers. 

Requirements:
- Add a generic handler to all twisted handlers that logs errors to the twisted logger if the service callback fails
- Return a defined status code (500) if a handler does not yet have an error handler with a different code

**Comment by bwagnerr** [comment]
We migrated to twisted web.
In order to return an http error in case there's an error in the processing, we need to have an error callback at the end of each of the twisted routes.

**Comment by zaraG** [comment]
We added a generic errback in all resources who did not have them.
There is no easy way to QA this, one would to pick a resource and force it to break, and check if 500 is thrown and error log written.
