### ISSUE TITLE
Remove SoledadQuerier

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#432]
Context: Pre 0.7 data model we directly accessed soledad, creating and reading documents using the SoledadQuerier. This should now be obsolete.

Analyse whether the querier could be removed and remove it. If exisitng functionality is missing in 0.7 code this also means there is no test for this functionality.

Requirements:
Delete SoledadQuerier, mixins and related tests

**Comment by fbernitt** [comment]
Issue #433 needs to be resolved before the Querier can be removed.

**Comment by shyba** [comment]
#439 as well.

**Comment by pereiragislene** [comment]
This card is in progress. It's not blocked.

**Comment by pereiragislene** [comment]
The existing features are being tested in the code, the references to SoledadQuerier and its codes have been removed and all the features are still working fine.

PS.: The only untested featured is BouncedMail (#441), since it is still in development.
