### ISSUE TITLE
Suggestion: Prompt user for attachment when user has forgotten about it.

### ISSUE THREAD

**Issue by SamuelToh** [pixelated/pixelated-user-agent#434]
Hey, just an idea which I think we can implement for the mail application. 
** Please close this if  it  doesn't make any sense.

------------
Why?
------------
When keywords like 'attchment' is mentioned in the mail content and I have forgotten to attach my item, I would like the email application to prompt me for my attachment.

Given that I am composing an email
   And I have forgotten to attach my attachments to the mail
   And I mentioned the word "attachment" in my mail content
When I tried sending the email
 Then the email application prompt me about my missing attachment.

**Comment by bwagnerr** [comment]
This is a nice idea and it has already come up before, but considering we can't send attachments yet (we only support receiving for now) I am not sure this is actionable now.

**Comment by SamuelToh** [comment]
Hey, thanks for the clarification.

I'll close this since it is dependent on a yet to be exist feature.

**Comment by bwagnerr** [comment]
@SamuelToh I saved the idea for when we implement attachments, thanks!
