### ISSUE TITLE
Thunderbird is getting lost while parsing mail date

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#438]
Every mail I receive comes from 1969 or earlier.
Something is wrong with the date present on mail body. At least not on Thunderbird expected format.
We should test on other UA, review RFC and research if it is our fault.

**Comment by varac** [comment]
i can confirm this, even though my recieved mail is displayed from Jan 01 1970

**Comment by varac** [comment]
interestingly, this is the Date: header:
```
Date: 2015-09-16T15:13:51.977784+00:00

```

**Comment by kaeff** [comment]
This is quite a nasty bug. However, you can send mails within pixelated and you can send/receive the encrypted message from Thunderbird to pixelated nonetheless. Therefore removing the Wazokazi label.

**Comment by giovaneliberato** [comment]
@bwagnerr is that deployed to wazokazi?

**Comment by cz8s** [comment]
just did a `docker pull` if you do a `docker rm gliberat` and login again, it should be the latest version

**Comment by giovaneliberato** [comment]
Yeah, it works now :dancers:
