### ISSUE TITLE
Migrate removal of bounced mail addresses from contact suggestion list

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#441]
see #174 

Definition of done:
#174 works after recent upgrades on libraries.

**Comment by varac** [comment]
@jeffhsta @albogabriel sorry for re-assigning, i was testing sth with a random issue

**Comment by jeffhsta** [comment]
@varac Ok, no problem =)

**Comment by jeffhsta** [comment]
I figured out that we have a lot of Mails classes, and the LeapMail class seems be the new one, so is necessary change every code that use the old ones to use LeapMail class.

I committed some comments on the code that explain better.

**Comment by shyba** [comment]
There are no more references to bounce on our codebase. Ready to go.
