### ISSUE TITLE
Allow users to provide feedback for Wazokazi

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#442]
As a wazokazi user
I want to have a way to provide feedback
So I can help making Pixelated a better product :)

____________________________________________________________

We want to add a button to the sidenav, right above the logout icon, to allow users to open the feedback form.

![image](https://cloud.githubusercontent.com/assets/350155/9502570/8b3213d0-4c08-11e5-89f2-00984aedf08c.png)

When expanded, it should display the text "Feedback".

![image](https://cloud.githubusercontent.com/assets/350155/9502578/92d18b66-4c08-11e5-8540-e7616a984f01.png)

Icon: fa-exclamation-circle  /f06a (font-awesome)
Color: #faa519

When clicked, it should open a feedback form (which might look something like the images below) where the compose email panel usually is:

![image](https://cloud.githubusercontent.com/assets/350155/9522209/dba8409a-4ca9-11e5-90a6-840acd3ce996.png)

![image](https://cloud.githubusercontent.com/assets/350155/9521922/fb099ab2-4ca7-11e5-8d0d-786b65e448c0.png)

After sent, the user gets a confirmation that their feedback was sent (and a friendly "thank you" message :))

## Implementation details ##

TBD. On an overview, we're planning to store the feedback to couchdb, not send it through email.  @shyba might be able to provide more details.

## Open questions ##

- How are we going to see these feedbacks outside the database?

**Comment by giovaneliberato** [comment]
@shyba are we still going to store this feedbacks on couchdb?

**Comment by giovaneliberato** [comment]
@albogabriel the color you specified differs from the $light_orange color on sass. Which one is the right?

**Comment by albogabriel** [comment]
Good call, @giovaneliberato - we should go with the $light_orange one.

Thanks!

**Comment by kaeff** [comment]
This is in play already and it might be a little late, but leap web has a support ticket functionality. An MVP for the feedback functionality would be just to link to: https://pixelated.wazokazi.is/tickets/new

**Comment by giovaneliberato** [comment]
@cz8s I forgot to say, but to enable this you have to set an environment variable named FEEDBACK_URL that points to https://pixelated.wazokazi.is/tickets

**Comment by cz8s** [comment]
thats hard to do inside the dispatcher I think. @fbernitt : any ideas how to pass env variables to docker?

**Comment by shyba** [comment]
Found this on docker doc:
http://docs.docker.com/reference/builder/#environment-replacement
Maybe help?

2015-09-22 12:15 GMT-03:00 Christoph <notifications@github.com>:

> thats hard to do inside the dispatcher I think. @fbernitt
> <https://github.com/fbernitt> : any ideas how to pass env variables to
> docker?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-user-agent/issues/442#issuecomment-142320601>
> .
>



-- 
Victor Shyba

**Comment by cz8s** [comment]
we have to run docker like this:
```
 docker run -t -i -e "FEEDBACK_URL=https://pixelated.wazokazi.is/tickets" pixelated/pixelated-user-agent
```
but that is hardcoded into the dispatcher-manager.

**Comment by cz8s** [comment]
it almost works. we changed the dispatcher to set the env correctly and I get the form in the user-agent on staging. I even see the POST in the webapp log, but I also see
'''
webapp[3230]: WARNING: Can't verify CSRF token authenticit
'''
We need to tell the webapp to ignore CSRF if it receives a POST to /tickets ...

**Comment by giovaneliberato** [comment]
I created a issue on leap web to discuss their side of the solution
https://leap.se/code/issues/7489

**Comment by cz8s** [comment]
this one got merged 2 days ago \o/
Tested it on wazokazi. And saw the tickets from me and giovane
