### ISSUE TITLE
Investigate drafts duplication

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#443]
#216 got a regression, but it is not so easy to reproduce.
We need to investigate what is causing it with the newer implementation and fix (or close if unable to reproduce).

Definition of done:
No duplicating while editing a draft using new data model

**Comment by fbernitt** [comment]
Do we have any more info about this? Like what you were doing when it happend?
From looking at the code (pixelated.adapter.services.draft_service.DraftService#update_draft) it seems that only an error while deleting the old draft might lead to this behaviour... that could be a explained by the lack of transactions when using the soledad api.
