### ISSUE TITLE
Extract search index master key logic from soledad querier

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#449]
Currently the soledad querier is still responsible to manage the search index master key. This logic should be moved to its own class.

Blocks #432

**Comment by kaeff** [comment]
End of day status: Using the extracted responsibilities of `SearchIndexStorageKey` now. I haven't pushed yet since the checkboxes functional test is failing locally. Will investigate tomorrow.

**Comment by kaeff** [comment]
Dev Done: SoledadQuerier isn't used any more to retrieve the master key. Search should still work.

**Comment by pereiragislene** [comment]
The search is working fine. Closing the card.
