### ISSUE TITLE
Show software version number

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#453]
As a maintainer
I want my users to be able to tell me which version they're using
In order to reproduce their issues quickly.
If this is not played, I have to spend more time finding out if a problem exists when someone reports a bug and have to infer from other factors which software version they might have used at that point in time.

It seems we don't currently carry a version somewhere. The version shown could be the short commitish. 
Where would we show this information, @albogabriel?

Related: #442

**Comment by albogabriel** [comment]
Hey @kaeff!

I was talking to @neissi, we could aim to show it along with the email address, as described in #411. While that story isn't done, maybe we should just hide the number when the sidenav is collapsed, and show it again when it's expanded. 

This wouldn't necessarily be a blocker to this issue or even a new issue. As a UI tweak, I could probably do it later this week.

What do you think?

**Comment by neissi** [comment]
Currently are showing the software version number.
whether possible adding this behavior on the sidenave should be good. Anyway is done!
