### ISSUE TITLE
Create default mailboxes when user logs in

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#457]
Currently mailboxes are created on first use. This works fine most of the time, though in rare circumumstances there is a race condition that results the same mailbox having diffrent mbox uuids. See issue #444 

To avoid this race condition, we create all the mailbox right away directly after the user logs in and soledad has been synced.

**Comment by fbernitt** [comment]
Wait whether this happens again, otherwise close in a few weeks.

**Comment by bwagnerr** [comment]
@fbernitt Hey, I think 3 weeks without happening is good enough, should we close this?

**Comment by fbernitt** [comment]
Yes, looks good, closing it!
