### ISSUE TITLE
Error when trying to render mailbox after login

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#459]
After login in wazokazi, I see the gray pixelated logo page but after that it fails to render the app when it's loaded.

That's the error I got `Interstitial.js:1 Uncaught ReferenceError: $ is not defined`

**Comment by cz8s** [comment]
Thats because of #458 the user-agent just stops and the webapp does not get any updates anymore.

**Comment by cz8s** [comment]
you can fix it by removing your leap directory. then it works until the next login

**Comment by giovaneliberato** [comment]
Oh, I heard you talking about that.. should we close this issue?

**Comment by cz8s** [comment]
Yes :)
