### ISSUE TITLE
[wazokazi] Side nav can't be expanded

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#462]
When opening the UA and clicking on the hamburger icon, the side navigation should expand so I can see the tag labels und version (cf. #453). However, on wazokazi right now, when clicking the hamburger icon it stays collapsed - nothing happens.

**Comment by bwagnerr** [comment]
Just tried taking a look at this, it looks like it can't fetch the file js/initialize_foundation.js, it receives a 404 in response. That didn't happen locally but the difference is that the dispatcher UA has everything minified in one file, while locally we have the individual files.

**Comment by cz8s** [comment]
did docker pull on wazokazi. works there now
