### ISSUE TITLE
[wazokazi] Version is not displayed correctly

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#464]
Bug for #453. While expanding the side nav doesn't work (see #462), you can see in the browser's tools that the version isn't displayed; instead, UNKNOWN_VERSION is displayed 

Run this in the JavaScript console:
```
$('.version').text()
"version: UNKNOWN_VERSION"
```

**Comment by varac** [comment]
@kaeff wonder about the priorities compared to #438, and why this is more important (=has wazokazi tag) than #438 ?

**Comment by kaeff** [comment]
I added the wazokazi tag since I assume it’s very hard to troubleshoot a user's issue if we can’t tell which user agent version they’re on. To avoid getting stuck, this would be nice to have before the first user request arrive.

**Comment by fbernitt** [comment]
I guess this is because when the package is build the source is copied to a temp folder and only then build. There is no git repo available and thus no version is updated.

**Comment by kaeff** [comment]
After some digging through the pixelated-user-agent-packaging/package job and finding out that it calls npm run package, I think we're missing the add_git_version there (cf. 891d202dfbf7ad4339a1f9f12ae79e1dc3b8d325)

**Comment by kaeff** [comment]
Saw version 891d202dfbf7ad4339a1f9f12ae79e1dc3b8d325 in the sidebar on unstable and wazokazi

**Comment by cz8s** [comment]
mee too \o/
