### ISSUE TITLE
checkbox (all) already  checked

### ISSUE THREAD

**Issue by neissi** [pixelated/pixelated-user-agent#465]
There is a lot of mails that I would like delete for instance, but currently I need select one by one, the option all in checkbox is already checked.

Definition of done:

As a user
when I have a list of mails in my mailboxes
I would like to have a option to select all (checkbox)

<img width="1280" alt="screen shot 2015-09-22 at 6 53 21 pm" src="https://cloud.githubusercontent.com/assets/4038257/10032676/f59a9064-615a-11e5-9fe6-c7ce59ba19c0.png">

**Comment by kaeff** [comment]
Standup 23/9/:
> Checkboxes seem to be flaky. While this is annoying, it shouldn't keep us from launching wazokazi.

**Comment by neissi** [comment]
Does not happen anymore.
Currently I can select a list of mails to do some action.
