### ISSUE TITLE
email adresses and gpg-keys are mixed up

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#466]
There is a weired behaviour that happens after some mails have been exchanged with a different account. The active key docs that are managed by the LEAP KeyManager are mixed up and for an emailaddress, e.g. someuser@example.tld the GnuPG key for otheruser@exanple.tld is stored in soledad and also returned. This causes a bunch of exceptions at different places in the codebase.

**Comment by fbernitt** [comment]
It seems I found the culprit:

https://github.com/pixelated/keymanager/blob/develop/src/leap/keymanager/__init__.py#L606

```python
    def decrypt(self, data, address, ktype, passphrase=None, verify=None,
                fetch_remote=True):
        self._assert_supported_key_type(ktype)

        def decrypt(keys):
            pubkey, privkey = keys
            decrypted, signed = self._wrapper_map[ktype].decrypt(
                data, privkey, passphrase=passphrase, verify=pubkey)
            if pubkey is None:
                signature = KeyNotFound(verify)
            elif signed:
                pubkey.sign_used = True
                d = self._wrapper_map[ktype].put_key(pubkey, address)
                d.addCallback(lambda _: (decrypted, pubkey))
                return d
            else:
                signature = InvalidSignature(
                    'Failed to verify signature with key %s' %
                    (pubkey.key_id,))
            return (decrypted, signature)

        dpriv = self.get_key(address, ktype, private=True)
        dpub = defer.succeed(None)
        if verify is not None:
            dpub = self.get_key(verify, ktype, private=False,
                                fetch_remote=fetch_remote)
            dpub.addErrback(lambda f: None if f.check(KeyNotFound) else f)
        d = defer.gatherResults([dpub, dpriv], consumeErrors=True)
        d.addCallbacks(decrypt, self._extract_first_error)
        return d
```

address is the address of the person the mail has been encrypted to, while pubkey is the key of the sender, signing the message!

**Comment by kalikaneko** [comment]
@fbernitt would this explain this stacktrace? https://leap.se/code/issues/7420#note-10

**Comment by kalikaneko** [comment]
>  d.addCallback(lambda _: (decrypted, pubkey))

I still not see the problem (although I've seen the mixing-up you're referring to)

>         :return: A Deferred which fires with:                                                                                                                                                       > * (decripted str, signing key) if validation works

so, apparently the documentation for the return types does not contradict the actual behavior, right?

**Comment by kaeff** [comment]
@kalikaneko I understood that @fbernitt was referring to this line:
```
d = self._wrapper_map[ktype].put_key(pubkey, address)
```
If I'm alice and I use `decrypt` to read an email send by bob, `put_key` will be called with bob's pubkey and my address. In Pixelated, this means that alice can't log into her account anymore.

See https://pad.riseup.net/p/vmPccbhMnHgg for details

**Comment by fbernitt** [comment]
@kalikaneko yes, I would say it is very likely that this explains the stacktrace in 7420

The problem is in this line:
> d = self._wrapper_map[ktype].put_key(pubkey, address)

Pubkey is the public key of the signer (sender) while address is the email-address the mail has been encrypted for (receiver). pubkey also is dpub in the bottom of that method. I am currently working on a test that shows the problem.

**Comment by fbernitt** [comment]
Have a look at this commit: https://github.com/pixelated/keymanager/commit/003517c1c5da3e2066a49ecc99db18cbe6bedc5c

In lines 446 to 456 there is a new assertion that should be green, but its not. The debug output before that shows the content of the database and also the OpenPGPKey-active docs where key_id and email are mixed up.

**Comment by meskio** [comment]
I think you are right @fbernitt, I added this `put_key` a while ago to signal the 'successfully used' keys:
https://leap.se/en/docs/design/transitional-key-validation/#key-manager-rules

And yes, we put back the key with the wrong address. How do you like https://github.com/leapcode/keymanager/pull/86 ?

**Comment by fbernitt** [comment]
Added two regression tests for this problem, see https://github.com/leapcode/keymanager/pull/86 and https://github.com/pixelated/keymanager/commit/7d01c02a23a13671d4aa07c4e4d5cb7bb2c5c8d4

**Comment by cz8s** [comment]
tried on staging. I couldn't break the user-agent \o/
