### ISSUE TITLE
tags are not shown if viewing all mails from a tag

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#474]
I don't know if this really is an error, but I got confused.
If I create a tag and klick on it on the sidebar, I see all mails that have this tag, but the tag itself is not shown on the emails (this blue thing below the subject of each email).

**Comment by bwagnerr** [comment]
@cz8s This is by design, considering you actively choose some filter, we only show the other tags that mail also has instead of duplicating the information (selected filter + tag in mail list).

**Comment by cz8s** [comment]
Okay. Thanks for the info.
