### ISSUE TITLE
Remove the encryption status on sent emails

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#475]
##What

We don't show the correct encryption status on sent emails. All of them have the "not encrypted" status tag.

<img width="1278" alt="screen shot 2015-09-28 at 11 51 40 am" src="https://cloud.githubusercontent.com/assets/2657059/10139039/88e584f2-65d7-11e5-92f5-9f1eb8655a03.png">

One first thing to do is remove the encrypted status  on the sent emails.

## Definition of done

The sent emails will not have the tag of encryption status.

**Comment by cz8s** [comment]
this now always says 'unencrypted' for every mail. Wouldn't it be better to remove the orange sign completely?

**Comment by kaeff** [comment]
For *every* mail, not only sent? I was under the impression the status was supposed to be working?

**Comment by cz8s** [comment]
I was only talking about sent mails.
Encryption status for received emails works

**Comment by cz8s** [comment]
with version b432e03 I still see the orange label saying 'Not Encrypted' on top of a sent email

**Comment by jeffhsta** [comment]
@cz8s did you test it running pixelated-user-agent in your box or in wazokazi?

Because by now we dont have the latest vertsion on wazokazi

**Comment by cz8s** [comment]
I tested on wazokazi

**Comment by cz8s** [comment]
after a 'docker pull' everything looks great.
