### ISSUE TITLE
Add jshint to test task on npm

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#476]
When running ./go test on service folder it runs flake8 to detect any python's lint problem, but it doesn't happen when running ui tests, which take us to some unnecessary broken builds.

The proposal is to add jshint as a requirement to test on npm tasks.

**Comment by giovaneliberato** [comment]
The stacktrace is quite big when jshint errors are found.. do you guys thinks it's a problem?

`
> pixelated-user-agent-web-ui@0.0.0 test /Users/gliberat/pixelated/pixelated-user-agent/web-ui
> npm run jshint && npm run build && node_modules/karma/bin/karma start --single-run --browsers PhantomJS $GRUNT_OPTS


> pixelated-user-agent-web-ui@0.0.0 jshint /Users/gliberat/pixelated/pixelated-user-agent/web-ui
> jshint --config=.jshintrc app test

app/js/mail_view/ui/feedback_box.js: line 37, col 51, Missing semicolon.

1 error

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "jshint"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! pixelated-user-agent-web-ui@0.0.0 jshint: `jshint --config=.jshintrc app test`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pixelated-user-agent-web-ui@0.0.0 jshint script 'jshint --config=.jshintrc app test'.
npm ERR! This is most likely a problem with the pixelated-user-agent-web-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jshint --config=.jshintrc app test
npm ERR! You can get their info via:
npm ERR!     npm owner ls pixelated-user-agent-web-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gliberat/pixelated/pixelated-user-agent/web-ui/npm-debug.log

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! pixelated-user-agent-web-ui@0.0.0 test: `npm run jshint && npm run build && node_modules/karma/bin/karma start --single-run --browsers PhantomJS $GRUNT_OPTS`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixelated-user-agent-web-ui@0.0.0 test script 'npm run jshint && npm run build && node_modules/karma/bin/karma start --single-run --browsers PhantomJS $GRUNT_
OPTS'.
npm ERR! This is most likely a problem with the pixelated-user-agent-web-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run jshint && npm run build && node_modules/karma/bin/karma start --single-run --browsers PhantomJS $GRUNT_OPTS
npm ERR! You can get their info via:
npm ERR!     npm owner ls pixelated-user-agent-web-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gliberat/pixelated/pixelated-user-agent/web-ui/npm-debug.log`

**Comment by kaeff** [comment]
The invoker can avoid it using `./go jshint —silent`. I’d say it’s fine

**Comment by kaeff** [comment]
If you open a pull requests with jshint violations, snap builds it and fails fast in the first stage:
![screenshot 2015-09-30 14 58 06](https://cloud.githubusercontent.com/assets/344781/10193480/bb8b14be-6783-11e5-9354-8a0486827635.png)

Failure is highlighted in the PR as usual:
![screenshot 2015-09-30 14 57 51](https://cloud.githubusercontent.com/assets/344781/10193485/bee24d12-6783-11e5-87c8-6b8a853579d6.png)
