### ISSUE TITLE
Fix loading screen layout

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#486]
Because of the way the blinking logos are positioned in the loading screen, not only our layout is broken for certain screen sizes (missing at least a column of logos at the far right), but also some logos are being lit up out of screen bounds - causing the user not to have any indication of "loading in progress".

![image](https://cloud.githubusercontent.com/assets/350155/10320564/7775bb00-6c4a-11e5-9952-fcb497bbd1ae.png)

We want to have the screen filled with logos and always blinking logos visibly on the screen.

**Comment by giovaneliberato** [comment]
@albogabriel Although the right side of the screen is fixed, it is still selecting some logos on the very first row to blink.. Was that expected?

**Comment by giovaneliberato** [comment]
Yes, that was expected
