### ISSUE TITLE
Generate Swagger API documentation during build process

### ISSUE THREAD

**Issue by hamvocke** [pixelated/pixelated-user-agent#489]
We're developing an Open Source [iOS client](https://github.com/SwiftMeetupHamburg/pixelated-mosaic-ios) for pixelated that's consuming the REST API provided by the pixelated user agent. When we started with our project there was no API documentation so one of our contributors reverse-engineered the pixelated REST API by clicking through the web interface and intercepting all the request going back and forth. The results of this reverse-engineering can be seen in a Swagger file we've created at https://github.com/SwiftMeetupHamburg/pixelated-mosaic-api-doc

The pixelated REST API is still in development and changes frequently. To make it easier for us to develop our app without having to manually figure out all the API changes the hard way it would be really helpful for us if you could provide a Swagger documentation on your side for all possible clients to use.

Having a Swagger documentation allows us to automatically generate a client library in Swift to use within our app that complies with your API. Other clients that might pop up in the future would have the same benefits.

Generating a Swagger documentation automatically as part of your build process would of course be a great solution for all of us involved. Quick research showed that there are libraries to generate a Swagger documentation out of endpoint definitions and/or docstrings for different frameworks (there are a couple of examples for Flask <sup>1,2,3</sup>,  there are other's around as well<sup>4</sup>. ). Maybe there's something around that pixelated could use?

<sup>1</sup>: [flask-swagger](https://github.com/gangverk/flask-swagger)
<sup>2</sup>: [flask-restplus](https://github.com/noirbizarre/flask-restplus)
<sup>3</sup>: [flasgger](https://github.com/rochacbruno/flasgger)
<sup>4</sup>: [Open Source Swagger Integrations](http://swagger.io/open-source-integrations/)

**Comment by anikarni** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
