### ISSUE TITLE
Reply All should not contain own account

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#491]
When I click on Reply All the account I am currently logged in with is added to the list of recipients. It should not appear there by default.

(Reported as user feedback:
"Reply all" includes myself in the message recipient list. This is weird and is not the behavior on other email clients.)

**Comment by kaeff** [comment]
Looks good from a QA perspective when running version 3863e28 on wazokazi.

However, there seems to be a regression. See #494.

**Comment by kaeff** [comment]
Another thing: There's no regression test for reply-to-all. We should have one, if can be added feasibly.
