### ISSUE TITLE
Auto split addresses when they are separated by a space

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#492]
If I enter multiple email addresses separated by spaces without pressing tab, they should automatically be converted into multiple, separate addresses. The current behaviour is, that a single, invalid entry is created that contains the entire string, including the spaces.

user feedback (ticket : cmesegpz)

 if you separate two addresses with a white space once you hit tab it will take it as one single address and mark it as wrong.

**Comment by giovaneliberato** [comment]
Talking to @albogabriel yesterday, we decide do include a invalid token that is created when the address isn't on the right format.

What lead us to that is when you type a word and press space, it would disappear with the old behavior.

**Comment by cz8s** [comment]
if I enter an address and press space or comma, it is recognized as an address.
It even tells me if the address is not correct (e.g. without an @ sign)
But the address 'me@examle' is considered a valid address. Is this still in the scope of this ticket?
Everything else works fine

**Comment by giovaneliberato** [comment]
> But the address 'me@examle' is considered a valid address. Is this still in the scope of this ticket?
It won't take that long to fix, I'll do that!

**Comment by giovaneliberato** [comment]
@cz8s fixed!

**Comment by cz8s** [comment]
great. works. can be launched
