### ISSUE TITLE
I should receive mails I sent to a group including myself

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#494]
Expected:
Given I received a mail that I sent to a group of multiple recipients, including myself
When I reply to that mail
Then the only recipient should be myself

Actual:
Then the recipient is someone else from that group

Sounds like a regression of #491

**Comment by kaeff** [comment]
A more concrete example

Given I am kaeff
And I sent an email to kaeff, kaeff2, kaeff4
And I received it in my inbox
When I reply to that mail
Actual: Then the recipient is kaeff 4
Expected: Then the recipient is kaeff

**Comment by fbernitt** [comment]
We should use something like gmail as a blueprint to define these behaviours in a way that matches the user expectations.

**Comment by fbernitt** [comment]
Reply behaviour:
- Sender that is not me: Reply to single sender
- Sender is me: All To: recipients (including me, if I am part of the list)

Reply-All behaviour
- Sender that is not me: Reply to all but remove me from the recipients list
- Sender that is me: Reply to all (including me, if I am part of the list)

**Comment by giovaneliberato** [comment]
It works! :accept:

**Comment by fbernitt** [comment]
Seems the way its implemented does not match op with the requirements

**Comment by jeffhsta** [comment]
Hey @fbernitt we decide to implement in a different way. We discussed here and I forgot to put that this issue, sorry that was my mistake.

So basically we thought that if the sender reply an email it should me send to self.

The implementation covers the below idea

When the sender is me:
* Reply: should send to my self
* Reply All: should send to everyone else, me not included - there is one exception for that if the receiver is just me reply all will send to my self

When I am not the sender:
* Reply: should reply to the sender
* Replay All: should reply to everyone else, me not included

@fbernitt is it make sense?

**Comment by fbernitt** [comment]
We decided to implement it in the same way that other mail clients do it and use gmail as a blueprint. The requirements should match this.

**Comment by fbernitt** [comment]
We'll leave this in its current shape as for now the behaviour is close enough to other mail clients.
