### ISSUE TITLE
Reply to a draft quotes original sender as "undefined"

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#495]
Given a sent mail
When I reply to it
Then the old message should be quoted, including the original date and my "Name <address@host.com>"

Actual
The quoted message's first line shows *undefined* as my email address

![screenshot 2015-10-14 18 21 12](https://cloud.githubusercontent.com/assets/344781/10490397/188a5a80-72a1-11e5-8f76-a8046c1fdba9.png)

Might this be related to #491 ?

**Comment by fbernitt** [comment]
This is related to:

web-ui/app/js/helpers/view_helper.js:105

```javascript
  function prependFrom(mail) {
    return i18n(
      'On __date__, <__from__> wrote:\n',
      {'date': new Date(mail.header.date).toString(), 'from': mail.header.from}
    );
  }
```
Guess a draft does not yet have a from header, therefore the undefined
