### ISSUE TITLE
Visual glitch in mail view when opening mail with many recipients

### ISSUE THREAD

**Issue by kaeff** [pixelated/pixelated-user-agent#496]
There is a little glitch with the divider line in the mail header in the mail view when the list of recipients is long:
![screenshot 2015-10-20 19 09 34](https://cloud.githubusercontent.com/assets/344781/10615106/32d31424-775e-11e5-964f-296718ab8d44.png)
It should be a single, continuous line

**Comment by kaeff** [comment]
Dev-done, not tested on an environment yet, waiting for deploy

**Comment by albogabriel** [comment]
I can have a look at this on different browser engines; judging by the code checked in by @kaeff, probably should be alright everywhere, though :)

**Comment by albogabriel** [comment]
Fixed and deployed to wazokazi.

All working fine :D

![image](https://cloud.githubusercontent.com/assets/350155/10717113/ba1d36e6-7b35-11e5-849a-c447e1906441.png)
