### ISSUE TITLE
Implement login on user-agent

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#497]
What
---
We need to move the user management to the user agent, at first this will be used to replace the CLI we have today and later to support multi-user on the UA.

Definition of done
---

- The user can login to the user agent through a web interface (roughly the same one we have in the dispatcher today)
- The user can logout of the user agent through a web interface
- If the credentials file or the credentials stdin are passed on the command line, skip the login screen entirely (works exactly as it is today)

**Comment by fbernitt** [comment]
Guess this can be closed because of issue https://github.com/pixelated/pixelated-user-agent/issues/576
