### ISSUE TITLE
 Implement encryption without SMTP - Adapt our code to call encryption

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#498]
What
---
We want to be able to encrypt and sign mails on the user agent without relying on the local SMTP, that way we won't have to spawn another loop for the SMTP and we'll be able to give feedback of the encryption and signature to the user even before sending.

This should be done after #499, we'll need to modify the user agent code so it calls the bitmask libraries to try to encrypt and sign mails.

Definition of done
---
We can run the user agent and send encrypted/signed mails without using the local SMTP

**Comment by shyba** [comment]
solved by https://github.com/pixelated/pixelated-user-agent/commit/4bc459e55331f8a07a676598bac264d54fb818d7

**Comment by shyba** [comment]
:+1: 
https://github.com/pixelated/pixelated-user-agent/issues/499#issuecomment-155155427
