### ISSUE TITLE
Implement encryption without SMTP - Adapt leap code to encrypt without SMTP

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#499]
What
---
We need to fully isolate the code to encrypt/sign mails in leap.mail so we can call it anywhere on the user agent and have the possibly encrypted/signed mail back with information on the outcome of the encryption process

Definition of done
---
We can call bitmask libraries to try to sign and encrypt a mail without sending or relying on the local SMTP

**Comment by jeffhsta** [comment]
This issue is related to #500 and #498, maybe if this is done these two issues should be done as well

**Comment by shyba** [comment]
Tests are in place, it got removed and enabled.
Talking quickly with @fbernitt we decided to think of contract or other integrations tests later (another card). This one already have unit tests.
Doing a basic exploratory to see if something broke, looks good so far! :+1:

**Comment by shyba** [comment]
Ports open: 9000/9001 [zmq](https://github.com/leapcode/leap_pycommon/blob/d3519a062ea6924fa6b6b5cb4d804b5a39eb249f/src/leap/common/events/server.py#L33) and 3333 (user agent web api)
```
pixelated-rec@LApixelatedrec:~/workspace/pixelated/pixelated-user-agent$ lsof -p 32535 | grep LIST
pixelated 32535 pixelated-rec    3u  IPv4 6077612      0t0      TCP *:3333 (LISTEN)
pixelated 32535 pixelated-rec   13u  IPv4 6075348      0t0      TCP localhost:9000 (LISTEN)
pixelated 32535 pixelated-rec   15u  IPv4 6075350      0t0      TCP localhost:9001 (LISTEN)
```
Sent mails between 3 accounts, 2 on dispatcher and one locally (activist). Everything went fine.
Launch it! :+1:
