### ISSUE TITLE
Implement encryption without SMTP - Remove SMTP

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#500]
What
---
After #499 and #498 we won't need the second SMTP anymore and we can remove all the code concerning it from the user agent

Definition of done
---
No local SMTP is present when you start the user agent

**Comment by shyba** [comment]
Solved by https://github.com/pixelated/pixelated-user-agent/commit/50f599dcc5297b3b29827b2ac02e6a9885b52d62

**Comment by shyba** [comment]
:+1: 
https://github.com/pixelated/pixelated-user-agent/issues/499#issuecomment-155155427
