### ISSUE TITLE
Show indication when there are no emails on the list

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#503]
## What

As a Pixelated user
I want to have a visual indication when my email list is empty
So I know it has zero emails instead of a broken UI.

## UI
It should display, horizontally aligned with the "Nothing selected" message on the mail pane and vertically centered, a message saying "No emails in '<tag_name>'.", as in the example below:

![image](https://cloud.githubusercontent.com/assets/350155/10950614/ad8c5578-831f-11e5-8ff7-e1144162b6fe.png)

This should display not only the default tags (inbox, sent, drafts, all), but also custom tags*, such as:

NO EMAILS IN 'INBOX'.
NO EMAILS IN 'SENT'.
NO EMAILS IN 'DRAFTS'.
NO EMAILS IN 'INSTAGRAM'.

Etc..

_* Currently, empty custom tags are erased. When we implement tag management, we might decide to keep them existing, even if empty._

**Comment by jeffhsta** [comment]
@giovaneliberato When I open 'All Mail' and it's empty I see:

NO RESULTS FOR: 'IN:ALL'.

It should be

NO EMAILS IN 'ALL MAILS'.

**Comment by giovaneliberato** [comment]
Fixed :dancers:
