### ISSUE TITLE
Fix alignment and clickable area in the recipients input fields

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#504]
## What
Currently, there's a lot of unclickable whitespace around the recipient fields labels.

![image](https://cloud.githubusercontent.com/assets/350155/10737350/c631b42a-7bf8-11e5-94e5-e64b1a430e4e.png)

We want to increase the clickable area while also improving the alignment (which was broken after we inverted the recipients and subject/body areas).

When clicking over "to", "cc" or "bcc", focus should be sent to the input field, making it editable and changing its background color to #fafafa (like Subject and Body already do).

## UI

![image](https://cloud.githubusercontent.com/assets/350155/10946831/91ea9280-830b-11e5-8f14-97708454ca8a.png)

**Comment by albogabriel** [comment]
Another issue - the problem when line breaks after many addresses are entered - has been mapped to #514.

**Comment by fbernitt** [comment]
The area below the To, Cc and Bcc fields is still not clickable. Is this the intended behaviour?

**Comment by fbernitt** [comment]
![click_areas](https://cloud.githubusercontent.com/assets/108677/10965616/94c02f08-83ae-11e5-8a05-c99b0b5aee2f.png)

**Comment by fbernitt** [comment]
Alignment looks good!

**Comment by fbernitt** [comment]
Fix looks good! Can be launched!
