### ISSUE TITLE
entering email adresses with spaces does not work

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#505]
When I want to send an email to
```Christoph  <ckluente@thoughtworks.com>``` 
the UI splits the address to three parts:
'Christoph', 'ckluente@thoughtworks.com' and '<>'

**Comment by giovaneliberato** [comment]
@cz8s is that when you're typing or pasting? It may happen because we included space as a parser trigger

**Comment by cz8s** [comment]
It happens when typing

**Comment by giovaneliberato** [comment]
@cz8s Fixed it :D

**Comment by cz8s** [comment]
works. Great!
