### ISSUE TITLE
user agent interface seems broken when loading

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#507]
## What

User agent components takes a little to get fully loaded. If the internet is slow, it may take even longer and the users may think it's broken.

<img width="1157" alt="screen shot 2015-10-28 at 12 09 17 pm" src="https://cloud.githubusercontent.com/assets/2964631/10790849/c02bb9ac-7d6c-11e5-9d69-d94d79c2c79d.png">

## Design ##

One suggestion would be adding an interstitial layer with some opacity (~85%?) over the UI that is being built, kinda like:

![image](https://cloud.githubusercontent.com/assets/350155/10950666/004706fa-8320-11e5-83f1-f9b83c369e3f.png)

## Definition of done

TBD

**Comment by albogabriel** [comment]
@bwagnerr and I will discuss the feasibility of a couple of solutions for this and update this issue when we have an answer.

**Comment by bwagnerr** [comment]
We removed the magnifier that was giving the impression that the interface was broken and on discussion decided that that was enough to fix this bug.

There is still a possible improvement that would be extending the loading screen (or an overlay) while loading the interface, as a hint for the user that this is the latest stage of loading, but we decided to spin that off in another issue and focus on it when we focus on system feedback for the user.

**Comment by pereiragislene** [comment]
It's working fine. Can be closed.
