### ISSUE TITLE
Highlight should match our search engine matches

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#508]
What
---
When we search for something on the user agent, it highlights the matches (even partial matches), but the search engine only searches for whole words.
Example: Searching for mon will highlight "mon"th, but the search engine doesn't match the word month.

Definition of done
---
Only the matches that the search engine would do will be highlighted

**Comment by giovaneliberato** [comment]
Search now works with substrings. For instance, if you search for "kazi" it should return emails that contains "Wazokazi" and "Kamikazi". It now indexes the body, subject and raw content.

**Comment by fbernitt** [comment]
Looks good!
