### ISSUE TITLE
BCC isn't blind

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#515]
## What

When I sent a email and put three emails in BCC field
All three emails will see the others two emails

## Definition of done

When I sent a email and put more than one address on BCC field
The recipient shouldn't see the others emails

**Comment by fbernitt** [comment]
One thing I observed: The mentioned behaviour, that Bcc recipients are visible is only true for pixelated (or users that are on the same platform). Even before the fix, mails that where sent to external recipients did not contain bcc headers. (guess that postfix does its magic here)

**Comment by jeffhsta** [comment]
@fbernitt I had tested sending from pixelated to riseup.net and gmail providers, using thunderbird as email client I cannot see bcc, but lookig and email source is possible see bcc header.

Did you check the email source if bcc is there?

**Comment by fbernitt** [comment]
yes, source does not contain Bcc header
