### ISSUE TITLE
Remove "dave draft" button

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#517]
## What
Remove the "save draft" button and whatever tests or actions depending on it.

We're still keeping auto save for drafts - and the "Draft was saved" message. Only the button is going away.

![image](https://cloud.githubusercontent.com/assets/350155/11002764/f99d01f2-8495-11e5-8e47-709229f26c43.png)

## Why
We've created this button as an experiment; the hypothesis (based on user interviews) was that some users felt uncertain whether something they wrote was properly saved when using apps with automatic saving, so we added a "save draft" button to serve as a fallback.

User testing so far proved that this isn't necessary, so we can remove the button.

(hooray for getting rid of UI pollution! :))

**Comment by giovaneliberato** [comment]
Fixed in #521
