### ISSUE TITLE
Users should be able to change their passwords

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#522]
We should integrate this feature, because it's very important in situations where ppl leak the passwords i.e.

The bitmask client has already implemented this btw.

**Comment by re-nobre** [comment]
Hey, @varac !
Can we consider this as an user feedback?

**Comment by varac** [comment]
Hi @re-nobre, 

if you consider me as a user, then yes ! :D

**Comment by re-nobre** [comment]
this issue will be solved by the password reset feature that @SweetVirginia  is working

**Comment by re-nobre** [comment]
I talked with @SweetVirginia and we will analyse all the UX proposals in a different place and create the issues when we will work on it.

For all the UX/UI proposals and feedbacks, take a look [here](
https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

I'm closing this issue now.
