### ISSUE TITLE
Create tag show incomplete placeholder text

### ISSUE THREAD

**Issue by pamcdm** [pixelated/pixelated-user-agent#524]
<img width="479" alt="screen shot 2015-11-13 at 3 18 31 pm" src="https://cloud.githubusercontent.com/assets/975037/11152621/cebd1aaa-8a1a-11e5-87a3-4ed88c9313d5.png">

## Solution

We can change the placeholder text to "Press enter do add tag"

![image](https://cloud.githubusercontent.com/assets/350155/11188330/655d2fa6-8c71-11e5-81fb-4b321dc1b698.png)

**Comment by albogabriel** [comment]
Will investigate possible alternatives and update this with some possible solutions.

**Comment by mnandri** [comment]
please add the Portuguese translation
