### ISSUE TITLE
 Contacts suggestion isn't working consistently

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#526]
##What
The contacts suggestion box stopped appearing when the user types an address

##Definition of done
When an user starts to type an address the contacts suggestion box should display all contacts that the user sent or received an email.

**Comment by cz8s** [comment]
contacts get auto-completed now, but I have some contacts that have a space and they get autocompleted to multiple recipients

**Comment by bwagnerr** [comment]
@cz8s The problem with that specific address (the problem is reported on issue #531) is that it contains a CRLF, that is the reason it gets separated in a weird way. Those email addresses are being indexed wrongly and #531 was created to deal with that.
I don't think there's anything we can do on this issue to deal with that, any ideas?

**Comment by cz8s** [comment]
I have another example: I have this in my contacts :
'Name <someone@example.com>'
This gets split also. Maybe we should have a look how input is validated when we paste and do the same here?

**Comment by bwagnerr** [comment]
cz8s: That is not identified as a email address (format is: xxx@xxx) and neither as a canonical email address (format is: Name <xxx@xxx>).

We'll have the same problem typing this as we'll have with the auto suggestion (it doesn't do anything differently, it just fills the input and remove the focus)

Do you think we should support other formats?

**Comment by cz8s** [comment]
I did mean a canonical valid address. And i think i did type < and>. Anyway, what i want to say is as a user I can't control what suggestions I get. These suggestions should then at least work.
