### ISSUE TITLE
Duplicated address when displaying "From" information

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#531]
It show `email@address.com from: email@address.com` on the mail list and on the contacts

This could have been broken after after https://github.com/pixelated/pixelated-user-agent/commit/c88514fdf18f39fb67101e3ea9741b3430f221b6 

<img width="1280" alt="screen shot 2015-11-18 at 5 51 27 pm" src="https://cloud.githubusercontent.com/assets/2964631/11252644/66dd8cc8-8e1e-11e5-8c53-bda9c0b08062.png">

**Comment by cz8s** [comment]
this only fixes the problem for newly indexed adresses, right? 
If I have wrong addresses in the index, they will be used as suggestion?

**Comment by bwagnerr** [comment]
cz8s: that's right, if the address was wrong, it will be indexed wrongly, the only way to remove that from the search is by removing the mail with the wrong address.

We don't filter or try address validation when saving.

**Comment by cz8s** [comment]
Okay. I sent a mail to wazokazi with a email address I didn't use before. And after that the suggestion box when sending a new mail included that address and it was valid. That should be sufficient for qa, right?

**Comment by bwagnerr** [comment]
@cz8s yes, it should
