### ISSUE TITLE
Make user-agent installable on debian jessie

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#533]
Related to https://github.com/pixelated/pixelated-platform/issues/133

The installation fails because jessie doesn't have the package libffi5. Instead, we should use [libffi6](https://packages.debian.org/search?keywords=libffi6)

Also, be aware that other packages cannot be available as well.

```
vagrant@debian:~$ sudo apt-get install pixelated-user-agent
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pixelated-user-agent : Depends: libffi5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by cz8s** [comment]
Switched to building jessie packages in ed80d4c60e42fedd9a9169290fe469f806b7313d
our docker images are using jessie now (84c591fdee9decd3527578ccbe701e5ddf72f40b)
Saw it working on staging already

**Comment by cz8s** [comment]
wazokazi runs with jessie images now

**Comment by fbernitt** [comment]
Great, works, bye bye wheezy!
