### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by Greg1586** [pixelated/pixelated-user-agent#536]
Text size on a 15-inch retina display seems quite small, and could be tricky to read for some users. 

As a user
I want the text size to be large enough to read easily
So that I can read the interface comfortably

**Comment by albogabriel** [comment]
Hi @Greg1586,

Point taken!

Any specific part of the app that is tricky on your 15" retina display? Would you be able to attach a screenshot to give us a better idea of what it looks like for you?

Thanks again for the feedback!

**Comment by Greg1586** [comment]
![screengrab](https://cloud.githubusercontent.com/assets/1903129/11461309/b7c9adda-9754-11e5-936b-a92da220af22.png)

hopefully this works!

**Comment by Greg1586** [comment]
when the item is unread, perhaps the background colour could change, or the text weight could be one increment heavier than as demonstrated, such as 200/700 instead of 100/500 ?

**Comment by felixhammerl** [comment]
@Greg1586 out of curiosity: do you have your display set to high resolution settings, or is this the default mode?

**Comment by Greg1586** [comment]
It was hi res

**Comment by felixhammerl** [comment]
i'm tempted to blame it on your hi res setting ;)

on a more serious note, if you want to submit this as a PR and run it by @albogabriel, that'd be great :)

**Comment by Greg1586** [comment]
A good point, Macs do scale content as well as window chrome when scaling
resolution.

Perhaps it's a case for more whitespace / negative space ... I'll have a
futz around with it.

**Comment by felixhammerl** [comment]
This issue has been idle for a while, I'll close it for the time being.
