### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Greg1586** [pixelated/pixelated-user-agent#537]
The site has some responsive design, but fails at smaller window sizes

As a user
I want the experience to be responsive to my device and screen size
So that I can use pixelated on a number of devices

**Comment by albogabriel** [comment]
Good point, @Greg1586. We'll be discussing strategy for implementing mobile friendly/responsiveness in the next team huddle .

Could you identify specific window sizes in which the UI starts to break?

Thanks again!

**Comment by felixhammerl** [comment]
Ok .... so this issue requires quite a bit of preparation. If you give me a day or two, I'll probably have more insight on how we can pull this off.
