### ISSUE TITLE
Overshoulder Mode

### ISSUE THREAD

**Issue by Greg1586** [pixelated/pixelated-user-agent#538]
There's a story for the user to be able to change the colour scheme, so this could align with that one. 
Give the user a colour scheme that is inverted ( as a suggestion ) so that the interface looks less like a mail client and more like some form of work - such as a terminal window. 
This would make the interface easier on the eye when it's dark, and also not be so obviously a mail client in case of prying eyes overlooking the user. 

As a user
I want to have a "secret" colour scheme
So that I'm less likely to be bothered if someone overlooks me.

**Comment by albogabriel** [comment]
Just to add, the issue about color schemes is #413

**Comment by felixhammerl** [comment]
Can you describe what "a "secret" colour scheme" means? Or better: Can you add a color scheme with the given SASS constants?

**Comment by Greg1586** [comment]
Yes, both ;) I'll work on it tomorrow.

**Comment by felixhammerl** [comment]
cool, thanks!

**Comment by Greg1586** [comment]
getting a timeout error on https://try.pixelated-project.org:8080/ at the
moment, I'll touch base later.

On 17 February 2016 at 21:25, Felix Hammerl <notifications@github.com>
wrote:

> cool, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-user-agent/issues/538#issuecomment-185140145>
> .
>



-- 
*Greg Skinner*
gskinner@thoughtworks.com
+61 4267 49 334
Greg1586
[image: ThoughtWorks] <http://www.thoughtworks.com/>
