### ISSUE TITLE
Translate the remaining tags, words and messages of the user agent to Portuguese

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#540]
## What
Just a few words have been translated into Portuguese. When the browser language is set to Portuguese, most of the buttons and messages are displayed in English. Sometimes the buttons have the ID displayed instead of their actual names in human language (i.e.: "send-button" instead of "Enviar").

## Definition of Done
We should have all the tags and words available in the EN translation file translated into Portuguese.

**Comment by giovaneliberato** [comment]
@felixhammerl Isn't this issue covered by #614?
Maybe we should try to find hardcoded text and add them to the translation files instead.

**Comment by felixhammerl** [comment]
yes, that's why i was moving it to development, to indicate that there was somthing happening :)

**Comment by felixhammerl** [comment]
Further action is covered by #619
