### ISSUE TITLE
Adapt leap common - Change event system to support multiuser

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#543]
What
===
The event system used by leap and pixelated for several communications doesn't have the notion of user, that means that an event fired will be picked up by all users, even if not related to their account

Definition of done
===
With one event server, one can fire events that will be picked up by one user but not by another

* Pending: Kaliy will create a PR about this, we should fill in the issue number to help follow the progress

**Comment by shyba** [comment]
https://github.com/leapcode/leap_pycommon/pull/133
In progess, me and @fbernitt will try to help.

**Comment by bwagnerr** [comment]
The code was merged, I think when we adapt keymanager we'll be able to see it working :)
