### ISSUE TITLE
Make zmq optional on Leap Common

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#544]
## What
Make zmq optional as a transport component on leap.common.events

**Comment by giovaneliberato** [comment]
Hey @re-nobre @fbernitt, this issue should have been created on https://github.com/pixelated/leap_pycommon, right?

**Comment by bwagnerr** [comment]
Hey, considering the changes leap is doing with bonafide, I don't think it would be wise to change the messaging passing too much currently. I would like to close this issue and if it comes a time when we think this makes sense again, we do it.
