### ISSUE TITLE
[soledad][bug] InvalidGeneration during fetch phase on sync

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#545]
There is a module called encdecpool and it is reused across syncs.
There was no test for it and a bug related to concurrency was being raised randomly.
This is what happens during a fetch:
fetch.py:
* fetch changes list (ordered)
* one request for each change with the index of the change on the list
encdecpool:
* start: create a Deferred that will signal its execution and see how many docs it will process
* (callback for last step) insert it on a staging area for decryption if it is symmetrically encrypted.
* decrypt, insert it decrypted on staging area (parallel with multiprocessing)
* query for the longest sequence that we can insert, insert it and delete from staging area.
* finish: fire the Deferred and reset vars

Those two last steps were bugged, specially when reusing the same instance within sequential syncs. Some instance vars were not being reset and a yield was missing, making the insertion of decrypted doc fall together with any other step, which resulted sometimes in the document being inserted after being processed. That is hard to reproduce.

Definition of done
====================
We have unit tests checking pool reuse and docs ordering. (and they are green, of course)
That was the PR: https://github.com/leapcode/soledad/pull/298

**Comment by bwagnerr** [comment]
We have tests checking this and they passed, this is ok for me!
