### ISSUE TITLE
Discover how to adapt user agent to work for 2 users

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#546]
We still have some pieces of code like:
```InputMail.FROM_EMAIL_ADDRESS = leap_session.account_email()```
This kind of code will go wrong with multiple users on the same process.

There is a branch called multi_poc that tries to run 2 users on the same process and should be able to tell what is currently braking.

What
=======
Discover and open issues for what needs to be adapted, fixing small issues as well.

Definition of done
=======
Create issues for what we need to do to adapt user agent to work for 2 users
Link here these issues.

**Comment by shyba** [comment]
talked to @bwagnerr and this doesnt fit the current priority. Moving back to Ready until we start enabling multi user support.

**Comment by re-nobre** [comment]
Hey, @shyba 
I renamed this issue and edited your comment just to use the standard that we are using on the others "UA multiuser" issues. Do this make sense for you?

**Comment by fbernitt** [comment]
Guess this can be closed because of issue https://github.com/pixelated/pixelated-user-agent/issues/576
