### ISSUE TITLE
Create a parameter to enable soledad sync in batch on user agent

### ISSUE THREAD

**Issue by jeffhsta** [pixelated/pixelated-user-agent#547]
## What

Given that now soledad client support document sync in batch
I want to be able to enable that feature on user agent

## How

That can be a parameter on user agent to enable that feature, the default must be disabled, because it can cause problems if soledad client try sync documents in batch when soledad server doesn't have that feature enabled

**Comment by bwagnerr** [comment]
Leap folks are preparing a discovery for the batch feature, that way the client will be able to sinalize with the server if they support batch and enable it by default, this issue doesn't make sense anymore in that context so I'm closing it
