### ISSUE TITLE
Send an email with one attachment

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#548]
## Definition
As a user
I want to be able to add a file attachment to an email and send it
So I can share this file with my contacts

## Constraints
- File limit should be 1 MB (this is an arbitrary value for testing purposes. We can update this if it's too big/small). "File size limit exceeded" warnings will be handled in another issue.
- Only one file should be attached right now. Multiple attachments will be covered in another issue.

## UI
We want to add a paperclip besides the "Send" button.

![image](https://cloud.githubusercontent.com/assets/350155/11744363/df5129b4-9ff6-11e5-94db-3518d5a69a2d.png)

This is the same font-awesome paperclip we use in other parts of the app, but rotated to be horizontally aligned. (the [css rotate property](http://www.w3schools.com/cssref/css3_pr_transform.asp) can be used to achieve that).

We will then display the browser's default file attachment window.

![image](https://cloud.githubusercontent.com/assets/350155/11744375/f5db5614-9ff6-11e5-9d14-a2af8768c7ec.png)

When a file is selected, it's displayed above the action buttons area (send/delete). It uses the same type of component used in the email recipient token - without the border and encryption icon indication.

![image](https://cloud.githubusercontent.com/assets/350155/11744766/6ccdb8cc-9ffa-11e5-88f1-6f55e85cf079.png)

Notes:
* The "x" to remove the attachment will be covered in #549.
* The file size information will be covered in another issue, yet to be created.

 
Ideally, this UI will also work for reply and forward components. If it doesn't, we can create a new issue for that. 

![image](https://cloud.githubusercontent.com/assets/350155/11745040/4e1b3a7e-9ffc-11e5-9784-a4339a5d50bb.png)

## Notes 
* Displaying the attachment size will be covered in another issue
* Displaying an alert if the attachment is too big to be sent will be covered in another issue

**Comment by mnandri** [comment]
to do:
- file names, don't come back if they have spaces
- forward and drafts do not automatically get the attachments

**Comment by fbernitt** [comment]
\o/ Works for me! Just sent my first mails with attachments :+1:

**Comment by albogabriel** [comment]
Icon isn't present on the reply UI. Should we crate a new issue for that?

![image](https://cloud.githubusercontent.com/assets/350155/12180446/ae2f98ac-b563-11e5-86ac-0446e5aad8c8.png)
