### ISSUE TITLE
Alert user when attachment size exceeds limit

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#550]
## Definition
As a user who is trying to upload an attachment
When I try to add a file that exceeds the size limit *
Then I see an alert explaining that the file can't be uploaded due to its size.

* Size limit, for now, will be 1 MB for testing purposes, but this will change.

## Constraints
This story depends on #548 being done.

## UI

When the user selects a file that is bigger than the size limit, a message is added where attachments are usually displayed saying "Upload failed. This file exceeds the 1MB limit." accompanied by the links "Chose another file" - which opens the browser file picker - and "dismiss" - which hides the message". Clicking the "X" on the left also hides the message.

![image](https://cloud.githubusercontent.com/assets/350155/11810564/24ac5ffc-a316-11e5-91df-35498f3c60e7.png)

**Text Color:** #D93C38 ($error color as defined in the _colors.scss file)
**Font-awesome character:** fa-close (alias) [&#xf00d;]

**Comment by pereiragislene** [comment]
I've edited the attachments feature functional test in order to cover this scenario:

1. The user tries to upload a file over 1MB
2. The user sees an error message
3. The user clickes the Dismiss button and the error message disappears
4. The user uploads a valid file
5. The file is successfully uploaded

I'm still trying to test this in a lower level (on the Javascript).

**Comment by pereiragislene** [comment]
Today, @mnandri and I created Javascript tests to cover the following cases:

1. User uploads a file smaller than 1MB
2. User uploads a file larger than 1MB
3. User dismiss the upload error message (close icon and dismiss button)
4. User Chooses to upload another file.

Moving the issue to QA.

**Comment by fbernitt** [comment]
Looks good, can be launched!
