### ISSUE TITLE
Cancel attachment upload

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#552]
## Definition
As a user uploading an attachment
I want to be able to cancel the upload
So that I don't need to wait until it's done if I decide not to send it anymore

## Constraints
This story depends on #548 and #551 being done.

## UI
Clicking the X at the right during an upload should cancel it
![image](https://cloud.githubusercontent.com/assets/350155/11749919/9d16689a-a017-11e5-9b5a-b62012704dff.png)

No (cancel) action confirmation will be required for now.

**Comment by felixhammerl** [comment]
https://github.com/pixelated/pixelated-user-agent/commit/511d621 adds upload button and restores user interface to pre-upload state.

<img width="433" alt="screen shot 2016-02-03 at 6 50 27 pm" src="https://cloud.githubusercontent.com/assets/1818340/12791352/189d3476-caa7-11e5-8c6c-1006c32d8039.png">
