### ISSUE TITLE
Show attachment size

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#553]
## Definition
As a user who added an attachment to an email
I want to see the size of the file I attached
So I know how big it is in order to decide if I want to send it

## Constraints
This story depends on #548 being done.

## UI
![image](https://cloud.githubusercontent.com/assets/350155/11750022/40f671b2-a018-11e5-8a0f-48cad28092d7.png)

**Comment by re-nobre** [comment]
It was implement as part of #548 and I can see the file size 

<img width="658" alt="screen shot 2016-01-11 at 11 11 50 am" src="https://cloud.githubusercontent.com/assets/2657059/12234477/60466c62-b854-11e5-8675-3143c60d6ceb.png">

So i'm closing this issue!
