### ISSUE TITLE
Send email with multiple attachments

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#554]
## Definition
As a user 
I want to be able to attach multiple files
So I can send all files I want in a single email

## Constraints
This story depends on #548 being done.

Combined size of all files must be under the defined size. See #550 and #548 in regards of what the limit must be.

## UI
The basic flow should be like #548. 

When seeing the browser file upload component, the user can select multiple files at once.

![image](https://cloud.githubusercontent.com/assets/350155/11750173/22bf137e-a019-11e5-8311-75a234d17576.png)

Every new attachment will be added below the previously added one.

![image](https://cloud.githubusercontent.com/assets/350155/11750074/91887bb6-a018-11e5-9397-a03e92679ea2.png)

## Open Questions
Q: Should we limit the number of attachments or should that be limited according to their total size?

Q: Should we add display the size of all files combined somewhere?

**Comment by pereiragislene** [comment]
Findings:

1. There should be a blank space between each attachment, according to the image attached by Albo, but there's no space between them;
2. I wasn't able to select multiple files at once. I had to open the dialog box multiple times to select different files (tested in Firefox/MAC OS).

**Comment by re-nobre** [comment]
hey, team!

I checked the issue description and I saw that @albogabriel described this follow behavior for this issue:

<i>When seeing the browser file upload component, the user can select multiple files at once. </i>

As we didn't dedicate a time to do this specific behaviour and as we just moved this issue to QA to see if previously issues covered it, I think the best is bring this issue back for ready and spend some time to develop it.

What do you think?

**Comment by pereiragislene** [comment]
I agree with @re-nobre's point.

**Comment by giovaneliberato** [comment]
@re-nobre Agreed :)
