### ISSUE TITLE
Can we make only storage(not web-ui or services) isolated by accounts?

### ISSUE THREAD

**Issue by tcz001** [pixelated/pixelated-user-agent#555]
I have tried to configure a pixelated-UA with my self-hosted provider, found it quite nice to have a well designed Webmail UI, and security by default configuration on data transportation.

But the problem is if I want to use this web-ui for many accounts, it's hard to resolve the cost of large amount of services. 

Thus, If some services can be shared between UAs (for example use file folders to isolate the sqlites of different accounts), it would be nice to minimize the number of duplicate service instances.

I'm asking this because for now I think pixelated is quite well organized and designed, but seems not able to suit to mass market because of this problem.

**Comment by tcz001** [comment]
The current structure:
![image](https://cloud.githubusercontent.com/assets/1702340/11772956/1f36d99c-a1f1-11e5-8178-8e682f6d398c.png)

A scalable proposal:
![image](https://cloud.githubusercontent.com/assets/1702340/11773132/54cc3faa-a1f3-11e5-931d-bc9f453f3df5.png)

**Comment by cz8s** [comment]
Hi, 

thanks for your feedback. In fact we are in the progress of removing docker and making the user-agent a normal webapp that is multi-user capable. 
It is still some work, but we are slowly getting there. 
At the moment, we have a tag for all issues related to that:
https://github.com/pixelated/pixelated-user-agent/labels/UA%20multiuser

Cheers,
  Christoph

**Comment by tcz001** [comment]
Glad to know it's on roadmap. I will look into the issues.
