### ISSUE TITLE
Update received attachment UI

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#558]
## Definition
As a user
I want to see my attachments in a way that is consistent to the rest of the UI
So that I can identify them quicker.

## UI

![image](https://cloud.githubusercontent.com/assets/350155/11812007/5249dc8c-a320-11e5-9d6e-8ab6df8f85a0.png)

**Font awesome icon:** fa-arrow-down

Despite the download icon in the far right of the component, the entire rectangle should be clickable and start the file download.

**Comment by neissi** [comment]
When I received a email with attachment, this one was update in my mail list, I can download it properly, but the UI definitions looks different than Albo's mockup, was missing rectangle and arrow icon.

**Comment by neissi** [comment]
After wazokazi has been updated, all UI definitions looks fine.
