### ISSUE TITLE
Recipient field is too small when typing a big email address

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#559]
## What
When entering a recipient in the compose box, there's a light gray box where the email address is located until the user finishes editing it. When the email address is bigger than the box width, it's not possible to see the whole address. 
<img width="363" alt="compose_box_recipient_field_email_address_bigger_than_area" src="https://cloud.githubusercontent.com/assets/554552/11820435/5028f8ac-a343-11e5-8081-44f1756de5eb.png">

## Definition of done
Currently, the input width is around 138px; we can safely make it nearly twice as big with no problem, so we can settle for a **270pm width** and adjust in the future if we feel like it.

**Comment by giovaneliberato** [comment]
@pereiragislene why this is blocked?

**Comment by pereiragislene** [comment]
@giovaneliberato: because it's missing the acceptance criteria. @albogabriel is looking into it.

**Comment by albogabriel** [comment]
Looking into now :) Will update this and unblock as soon as it's ready.
