### ISSUE TITLE
Should be able to receive inline attachments

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#562]
## What
Some mail clients send attachments as inline, specially images and PDF files (i.e.: Apple Mail). There's a verification on the user-agent code that only consider an attachment if the content-disposition has the word "attachment" inside it. When the attachment received is inline, it doesn't have the word "attachment" and, therefore, the user is not able to receive it on Pixelated.

## Definition of done
The users should be able to see the number of attachment(s) and the link(s) to download it/them if they were sent as inline attachments from different mail clients.

**Comment by re-nobre** [comment]
I tried on dev.pixelated-project and it works for me! 

Email from Gmail
<img width="681" alt="screen shot 2016-01-04 at 4 13 18 pm" src="https://cloud.githubusercontent.com/assets/2657059/12096678/2c22297c-b2fe-11e5-94af-5561d80ddacd.png">

Email from Apple
<img width="670" alt="screen shot 2016-01-04 at 4 24 12 pm" src="https://cloud.githubusercontent.com/assets/2657059/12096899/b83b8236-b2ff-11e5-9ed6-9fede90b9520.png">

OBS: My signature is showed as an attachment like @pereiragislene comment on the issue: #569
