### ISSUE TITLE
Enable hide/show toggle for cc and bcc fields

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#563]
As a user writing an email
I want to be able to show the cc and bcc fields
So that I can add recipients to those fields

As a user writing an email
I want to be able to hide the cc and bcc fields
So that I have a cleaner interface for most of the time

## UI
We want to be able to show and hide the cc and bcc fields by clicking a toggle link/button.
 
The default state is having cc and bcc collapsed.

**Comment by pereiragislene** [comment]
The arrow rotates up and down when composing a new message, but it doesn't rotate when editing a draft (including forwarding). It remains pointing to the bottom after expanding the CC/BCC area.

**Comment by neissi** [comment]
I did Qa and works fine. Should be launched!
