### ISSUE TITLE
Show unread count on page title 

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#564]
#### What
As a user
I want to be able to see how many unread mails I have on the page title
So I can easily keep track of new mails

#### Definition of done
<img width="208" alt="screen shot 2015-12-29 at 10 21 41 am" src="https://cloud.githubusercontent.com/assets/2964631/12038342/6a2d8334-ae3e-11e5-8069-f1af78cdafde.png">

**Comment by neissi** [comment]
Stanging still down to do Qa of this and wazokazi needs a new deploy.

**Comment by re-nobre** [comment]
I tested on dev.pixelated-project.org and it works for "inbox" and "draft box" :+1:

**Comment by neissi** [comment]
I did Qa on Dev environment and looks fine, works properly!
