### ISSUE TITLE
Can't open encrypted attachments from Thunderbird 

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#567]
## What
When receiving an encrypted mail from Thunderbird with the option "Encrypt each attachment separately and send the message using inline PGP", the attachments are not decrypted. They have the extension .pgp and it's not possible to see their content.

## Definition of Done
The users should be able to receive emails with encrypted attachments and see their content.

**Comment by giovaneliberato** [comment]
On the last LEAP call Meskio said that this is an deprecated method of encrypting email and enigmail should drop that soon so I'm closing the issue.
