### ISSUE TITLE
Signed mail doesn't show the label "Verified Sender" (from Thunderbird)

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#568]
## What
When receiving signed mails, the label "Verified Sender" is not displayed when it's sent using OpenPGP.
I was only able to see the correct label when receiving signed mail using PGP/MIME (from Thunderbird).

## Definition of Done
The label "Verified Sender" should be displayed when receiving a signed mail from Thunderbird.

**Comment by jeffhsta** [comment]
This issue is already fixed by the #569
