### ISSUE TITLE
Signed mail should have the "Verified Sender" label instead of a .asc attachment (from Apple Mail)

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#569]
## What
When receiving signed mails from Apple Mail using OpenPGP, the signature is displayed as an attachment and the label "Verified Sender" is not displayed.

## Definition of Done
- [x] The label "Verified Sender" should be displayed when receiving a signed mail from Apple Mail.
- [x] The signature (.asc file) shouldn't be displayed as an attachment.

**Comment by giovaneliberato** [comment]
PR opened https://github.com/leapcode/leap_mail/pull/220

**Comment by pereiragislene** [comment]
For signed mail only, it worked fine. But when receiving a signed AND encrypted mail, it doesn't have the Verified Sender label and the .asc attachment is displayed.

**Comment by giovaneliberato** [comment]
PR got accepted

**Comment by pereiragislene** [comment]
I'm closing this issue. The scenario described above will be covered by #605.
