### ISSUE TITLE
Set PHANTOMJS_BIN in the UA vagrant bashrc

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#571]
Currently, we can't run the functional tests directly on the UA vagrant box, because it can't find the phantomJS binary (it expects a fixed /usr/local/bin/phantomjs). We should set the variable PHANTOMJS_BIN in the bashrc so that people can use without having to set this manually

Definition of done
---

I can do a vagrant up, vagrant ssh and run the functional tests (./go functional) without phantomJS errors

**Comment by rdoh** [comment]
Is this fixed already? `./go functional` runs all the tests and passes for me.

**Comment by phss** [comment]
I see the same behaviour as @rdoh. I can do the following with no PhantomJS errors:

    vagrant up
    vagrant ssh
    cd /vagrant
    cd web-ui
    ./go test
    cd ../service
    ./go functional

Note that PHANTOMJS_BIN is still not set. Perhaps it was fixed differently?

**Comment by bwagnerr** [comment]
I've verified the same thing, thanks for the heads up!

We'll close this issue
