### ISSUE TITLE
Adjust file attachment UI

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#572]
Adjust UI for attachments so it looks like described in #548, such as: 

**paperclip smaller and rotated to be 90 degrees;**
*current*
![image](https://cloud.githubusercontent.com/assets/350155/12177780/1edffec0-b555-11e5-8ec1-e236e739e30c.png)

*desired*
![image](https://cloud.githubusercontent.com/assets/350155/12177801/3966a622-b555-11e5-9420-413beb0ab005.png)

(the [css rotate property](http://www.w3schools.com/cssref/css3_pr_transform.asp) can be used to achieve that).

**- no "Attachments" text;** 
**- attachment box taking full width;** 
**- Attachment size color (lighter gray than the file name)**

*current*
![image](https://cloud.githubusercontent.com/assets/350155/12177889/b4b5b840-b555-11e5-8e4a-632c04b0d893.png)

*desired*
![image](https://cloud.githubusercontent.com/assets/350155/12177864/8c40dc3c-b555-11e5-954c-e32d49d981ae.png)

**- no whitespace between the end of the "body" input and the "Send" button row when there are no attachments;**

*current*
![image](https://cloud.githubusercontent.com/assets/350155/12177936/fa235eb4-b555-11e5-9a97-43bce5996379.png)

*desired*
![image](https://cloud.githubusercontent.com/assets/350155/12177976/24b004e8-b556-11e5-832b-80de6cdfbe82.png)

**- no margin between attachments**

*current*
![image](https://cloud.githubusercontent.com/assets/350155/12178084/b62a5e1e-b556-11e5-8ef0-bcdbf2000911.png)

*desired*
![image](https://cloud.githubusercontent.com/assets/350155/12178100/d4f74f00-b556-11e5-9438-d18a655b5170.png)

(this can be solved by adding a "margin-bottom: 8px" to ".attachmentsWrap .attachmentsArea li")

Notes:
* The "x" to remove the attachment will be covered in #549.
* Displaying an alert if the attachment is too big to be sent will be covered in #550

**Comment by pereiragislene** [comment]
All changes according to @albogabriel's suggestions are done.

Regarding this:
>  " - Attachment size color (lighter gray than the file name)"

What should be the file name color when the user hovers/focus the link? For now, I didn't setup this.

**Comment by jeffhsta** [comment]
The feature described on this issue is done.

And as @albogabriel are not working these days, we can discuss about the color on hover/focus on the link later when he be back.
