### ISSUE TITLE
Enable Attachments on Save drafts

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#573]
Narrative:
As an email user, when I type a message in compose box or  open existing drafts, and append attachments to it, I want pix to save a new draft, with those attachments ... so that I can review/send it later, with those attachments. 

ACs:
- when you change the "to" field or cc, bcc, subject, body and you added an attachment it should save a new draft with that attachment.
- when you just add an attachment to an existing draft, it should save a new draft with that attachment.
- when you navigate to another page and come back to the draft folder, all drafts with attachments should show attachment list when opened.
- when you navigate to the draft folder, email drafts with attachments should have a little paperclips icons on the far right side.

**Comment by fbernitt** [comment]
Works for me!
