### ISSUE TITLE
Search engine should use a different path per user

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#577]
What
===
The search engine uses one path ("leap_home/search_index") for every run, that causes problems when trying to run multiple users, because they try to use the same files. This path should be namespaced for each user

Definition of done
===
I can run one user without errors and when O run two users and don't see any "Error when opening file: Wrong MAC" errors

**Comment by fbernitt** [comment]
Looks good!

**Comment by dudadornelles** [comment]
Adding something a bit 'unrelated', but maybe is time we spike another
search engine for the multi tenant version of the app.

**Comment by shyba** [comment]
+1

2016-01-13 12:05 GMT-03:00 Duda Dornelles <notifications@github.com>:

> Adding something a bit 'unrelated', but maybe is time we spike another
> search engine for the multi tenant version of the app.
> On Jan 13, 2016 5:37 PM, "Renata Nobre" <notifications@github.com> wrote:
>
> > Closed #577 <
> https://github.com/pixelated/pixelated-user-agent/issues/577>
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/pixelated/pixelated-user-agent/issues/577#event-513610747
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-user-agent/issues/577#issuecomment-171322572>
> .
>



-- 
Victor Shyba
