### ISSUE TITLE
Reply To, Reply All, Forward email with Attachments

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#579]
Narrative:
As a user, when I respond or forward an email, I would like to be able to add attachments to my response.

ACs:
* When I open an email and I  click on Reply To or Reply All or Forward button,  I should see the Attach paperpclip Icon
* When I click on the paperclip Icon, then it should have the same behavior as #548
* When I open an email with attachments and I click Forward, I should see all attachments re-attached to email inline compose box. I should be able to add more attachments to it.

**Comment by cz8s** [comment]
tested it on wazokazi. I can add attachments when replying.
But when I forward an email, the attachment from the original mail can not be
forwarded? Or I don't see the button?
![selection_001](https://cloud.githubusercontent.com/assets/369402/12614531/d6474cd4-c500-11e5-9b27-0fe0ba6aceb1.png)

**Comment by giovaneliberato** [comment]
@cz8s My bad, I didn't saw the third acceptance criteria.. I'll move back to development and implement this behaviour

**Comment by fbernitt** [comment]
When I receive a mail with attachments and I would like to forward it, I would expect that the mail contains the attachments the original mail had. Currently the list of attachments for the forwared mail is empty and i could add new attachments.

**Comment by giovaneliberato** [comment]
@fbernitt I had implemented that, but the commit went accidentally to the #509 :( My bad again.

I also did some toggling with the icons on the attachment box.

https://github.com/pixelated/pixelated-user-agent/commit/ec80088330eff5f44e8cc8eaab04c83c259b9098
