### ISSUE TITLE
Attachment should have the right filename and extension 

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#581]
## What
When receiving mails with attachment, sometimes when downloading it, the file is downloaded with its ident as the file name and there's no file extension. 

## Definition of Done
- [x] When downloading an attachment, the downloaded file should have the same file name as displayed in the e-mail.
- [x] The file extension should be set.

**Comment by fbernitt** [comment]
Had a look at the change for dispatcher, in the handle_response there is a list of headers that are forwared, guess you could also add the Content-Disposition there

**Comment by jeffhsta** [comment]
@fbernitt Thanks for take a look and comment here, I just changed there, I think now the code is better

**Comment by fbernitt** [comment]
Works, can be launched!
