### ISSUE TITLE
Spike Load Testing Tool

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#585]
Done will be:
- We have a tool/framework that we can use to run regular load test of multi UA
- Describe pros/Cons of alternative tools if many.
- Provide bare minimum framework for -future- load testing for multi UA

**Comment by mnandri** [comment]
We are using [locust.io](http://locust.io/)
It was recommended by [tech-radar](https://www.thoughtworks.com/radar/tools/locust) a few years back.
It is very easy to use, readable and can fit our use cases more or less. 

For this issue, we are only running a few scenarios, per user:
1. Login
2. Go to home (probability 1/6)
2. Read mails (probability 1/3)
3. Send email, and delete if successful (probability 1/2)

To QA:
* _pip install locustio_
* Start multi UA in a terminal
* In another terminal,  run within the service folder:
_
> locust -f test/load/locustfile.py --host=http://localhost:3333 --no-web -c 10 -r 1 -n 100
_
This will run 10 concurrent users, 1 user spawned  per second, and total 100 requests

* To use the GUI, simply run 
_
> locust -f test/load/locustfile.py --host=http://localhost:3333
_
and browse to http://localhost:8089/ and specify parameters from there.

**Comment by giovaneliberato** [comment]
It works :D
