### ISSUE TITLE
Logout on multi UA

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#586]
Narrative:
as a mail user, when I am logged in, I want to logout so that any other user have no access to my emails

ACs:
* Given I am logged in, when I click on the logout icon, I am redirected to the login page. Any subpath of the webmail, will redirect me to the login page, until I login again.

Note: All services, in services_factory should all be closed out whenever a user is logged out.

**Comment by mnandri** [comment]
part of this is already done:
- sessions are closed, on click of logout.

what is missing:
- closing user services... e.g. closing soledad access to its sqlite and so on
- remove the user services from the serives factory

**Comment by giovaneliberato** [comment]
Services that needs to be explicitly closed
- Leap session
- Soledad (does leap_session.close includes soledad.close?)

Services that can be ignored
- Draft service
- Feedback service

Services that I don't know what to do with
- Search engine
- Mail service
- Keymanager

Search engine and Mail service depends on Soledad and Leap session, so closing this ones should be enough

Did I miss something @shyba @mnandri?

**Comment by mnandri** [comment]
Leap session close will stop background mail fetching jobs, closes soledad (including connection to u1db and sqlite) and remove the session from cache

**Improvement:**
what -could be- missing is a graceful close of soledad... if a sync is underway while the close button is clicked, either it -gracefully- stop or abort sync or it waits for it to complete sync before completing the request.

I'm moving the card for now as that improvement will potentially involve some  hands-on soledad changes so... better to put that in different card.

Serious QA needs to be done:
* login
* logout
* login back
* perform all regular operations: compose, save draft, send, tag, un-tag,... and view 
we need to be sure closing and re-init soledad works properly without restarting the reactor...
