### ISSUE TITLE
Access pixelated under DOMAIN/pixelated

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#594]
As discussed on the pixelated-team ml, we should make sure that the useragent is accessible under a domain like DOMAIN/pixelated or DOMAIN/mail ( i would prefer the first ).
Reason behind this is that providers should not need to buy a second cert for the mail.DOMAIN subdomain.

**Comment by varac** [comment]
for the record, eric agreed on this, so i made a story for it so we don't forget about this.

**Comment by re-nobre** [comment]
As we are using letsencrypt and the certificates are free, we believe it's not a problem anymore and because of that we are closing this issue
