### ISSUE TITLE
Add customizable disclaimer support to login screen

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#598]
The dispatcher had a way to customize the login screen. We use that e.g. to display some special information on try.pixelated-project.org.

**Comment by mnandri** [comment]
@fbernitt,
 
For clarity:
do we need to pass it from the command line, as an argument?
e.g.

pixelated-user-agent --multi-user --provider=dev.pixelated-project.org --banner=_login_banner.html

**Comment by mnandri** [comment]
to override the default that is in service.pixelated.assets._login_banner.html
you would need to supply the --banner=/path/to/file

Note: please make sure that the file is xml compliant ( tags has to match and close properly)
