### ISSUE TITLE
QA vagrant setup on Windows

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#600]
There was one person joining the AU hackday how didn't get the useragent set up in vagrant. We should try this before our hacknight.

**Comment by alset** [comment]
I was trying the setup of user agent using vagrant. I ran all the steps through Cygwin and I was able to get 'vagrant up'. After this, I do a vagrant ssh and loginto the vagrant box. As the next step I, I do ./go setup from the approriate folder and I got an error message complaining that the script was unable to  open bash script I noticed the ^M character at the end of the line which I suspect is the problem

**Comment by varac** [comment]
@alset normally, you should not need to do `./go setup`. did you run into any problem before this step ?

**Comment by varac** [comment]
so today we learned about line ending issues: https://help.github.com/articles/dealing-with-line-endings/
the above commit fixes the problem @alset had.
we're close of using vagrant on windows successful, so everybody hang on.

**Comment by varac** [comment]
i need to reset my windows machine in order succeed, waiting for philip.

**Comment by varac** [comment]
This looks promising: [Babun - a windows shell you will love](https://babun.github.io/)

**Comment by varac** [comment]
I gave babun a try but [failed downloading a vagrant box](https://github.com/babun/babun/issues/645) :/

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
