### ISSUE TITLE
Remove blocking calls

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#602]
As discussed on retro, we still have many blocking calls, such as HTTP(s) with requests on our leap_auth lib or LeapSession here.
We should review and get rid of them in order to free the reactor. This is mainly motivated by multi user migration where the same event loop will be used by multiple users and if someone blocks a call the entire environment will be frozen for a while. Or worse.

Definition of done
==============
No more urllib/requests (synchronous) messages on logs. Or, at least, make sure that they are running outside of reactor.

**Comment by bwagnerr** [comment]
Hey, we created several smaller issues to address this, we still have some requests blocking calls on user-agent bootstrap, but we removed all of them from the login onwards.

Because of that I'm closing this issue.

**Comment by bwagnerr** [comment]
Hey, we created several smaller issues to address this, we still have some requests blocking calls on user-agent bootstrap, but we removed all of them from the login onwards.

Because of that I'm closing this issue.
