### ISSUE TITLE
[soledad] simplify some soledad sync parts, making reactor more responsive for multi tenant

### ISSUE THREAD

**Issue by shyba** [pixelated/pixelated-user-agent#603]
Just found out a way to remove multiprocessing pool among other optimizations/refactors that brought sync to a constant network rate and low cpu usage with reactor being way more responsive than before.

Definition of done
================
Sync works and no error is thrown during a sync in single or multi user environments.
Also, http responses should be consistent during sync.

QA tips
==================
Try using a http benchmarking tool to check response times across sync.
Ideally, it should be better than before, throw no errors and present a constant request response time over time. That means (ideally) HTTP response times shouldn't change so much during a sync.

Pull Request
================
https://github.com/leapcode/soledad/pull/309

**Comment by shyba** [comment]
All comments claiming resolution for issue 7370 were removed and the test is skipped again.
Currently it still fails on slow machines and is out of scope for this card.
This refactor makes it pass on SSD, but that doesn't fix the issue.

**Comment by cacarrara** [comment]
@shyba changes on soledad was added to this PR: https://github.com/leapcode/soledad/pull/320

**Comment by shyba** [comment]
Awesome, :+1:
Ping me if anything
