### ISSUE TITLE
Fix os.makedirs issue breaking tests on OSX

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#604]
currently test.unit.bitmask_libraries.test_smtp_client_certificate.TestSmtpClientCertificate.test_download_certificate_if_redownload_necessary

is failing due to os.makedirs trying to re-create "/"

Done:
Test green while keeping the feature #591 working

**Comment by mnandri** [comment]
The problem is with mockito limitations.
If we stub a method for a specific input then it will return None for everything else (that is not the specified input)... which is a very bad thing for os.makedirs because it will think that even "/" does not exists...

To QA:
all tests should be green :)

**Comment by fbernitt** [comment]
Looks good, can be launched!
