### ISSUE TITLE
Signed and encrypted mail has label "Not Signed" and show signature as attachment (from Apple Mail)

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#605]
## What
When receiving signed and encrypted mails from Apple Mail using OpenPGP, the signature is displayed as an attachment and the label "Not Signed" is displayed as below:

<img width="797" alt="screen shot 2016-02-12 at 15 10 50" src="https://cloud.githubusercontent.com/assets/554552/13015987/e9a224a6-d19a-11e5-95ba-0e8b192ae0a7.png">

## Definition of Done
- [ ] The label "Verified Sender" should be displayed when receiving a signed and encrypted mail from Apple Mail.
- [ ] The signature (.asc file) shouldn't be displayed as an attachment.

**Comment by varac** [comment]
I sent a signed and encrypted mail to an useragent running `version: 9e79c3b` (HEAD as of now), and it displays the mail as "Not Signed", but properly as "Encrypted".

However, i don't see any signature as attachment.

I composed the mail with Thunderbird/Enigmail.
I can send a similar mail for testing porposed, ping me.

**Comment by pereiragislene** [comment]
@varac: the "signature.asc" attachment was displayed when composing the message with Apple Mail. What do you think of creating another issue to cover Thunderbird's case, since it's a bit different?

**Comment by varac** [comment]
see also #566

**Comment by giovaneliberato** [comment]
https://github.com/leapcode/leap_mail/pull/225

**Comment by cacarrara** [comment]
The previous PR got pretty outdated, so we thought could be better to open a new one: https://github.com/leapcode/leap_mail/pull/243
