### ISSUE TITLE
Remove unlinked attachments from soledad

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#606]
At the moment, attachments are all saved as soledad docs and kept forever.

We need to work with leap on a  model that will allow us to:
- delete attachments after/when unlinking them from an email
- as much as possible avoid duplicating attachments that has the same content.

related story: #549

**Comment by bwagnerr** [comment]
The problemand solution is that the documents are not attached to emails, so we could have a body that is used by more than one email. There is no duplication of attachments with the same content.
How do we identify that no more emails need that specific body? That is still not answered.

**Comment by anikarni** [comment]
Closed due to inactivity
