### ISSUE TITLE
(meta)Focus of Usability

### ISSUE THREAD

**Issue by JRingelstein** [pixelated/pixelated-user-agent#607]
The current UI does not seam to be tailored to a specific type of user.
If you can define a target audience, you can address their specific needs.
If the idea is to make encryption accessible to a wider group of people the UI should be reduced and the actions should be hidden in the background . The focus should be on the tasks the user wants to get done (reading, deleting, answering, ...) rather than application features (e.g. tagging, moving, subfolders, ...) that are incidental.
Make it available in various languages. [Based on popularity to remove language as a barrier](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers)

This is a rough example of a minimalistic UI without exposed buttons. The actions feel natural and are intuitive. Context-sensitive options are only shown if they make sense. e.g. bulk actions are only visible when you select various mails. (see medium.com)

![imag1422](https://cloud.githubusercontent.com/assets/10738364/13058579/61e96812-d424-11e5-9267-66751fefced7.jpg)

**Comment by felixhammerl** [comment]
@JRingelstein thanks for the issue!

A bit of background: We're currently preparing a major refactoring of the UI. That will probably go in multiple steps, starting with cleaning up the stylesheets, refactoring to BEM, and finally making a transition to responsive.

> The current UI does not seam to be tailored to a specific type of user.
> If you can define a target audience, you can address their specific needs.

True, it's pretty general purpose right now, even though we had Personae in mind when we designed it, @albogabriel can give you more input on that than me. If you have any specific ideas on how to work on that, I'll be glad to help you get started on the next Hacknight. I'm sure there will be more people there that'd like to tag along!

> If the idea is to make encryption accessible to a wider group of people the UI should be reduced and the actions should be hidden in the background . The focus should be on the tasks the user wants to get done (reading, deleting, answering, ...) rather than application features (e.g. tagging, moving, subfolders, ...) that are incidental.

If we have some fresh minds on the next hacknight, we can run it by them and see how they'd like to have it. How does that sound?
Other than that, I'd take the client to a public place and watch people use it. If we find enough people to support this cause, we could plan a UX-guerilla hacknight where we gather as much input from fresh, untouched minds, and compile UX designs from there.

> Make it available in various languages. Based on popularity to remove language as a barrier

So far, we have translations for English (US), Portuguese, and Swedish.
https://github.com/pixelated/pixelated-user-agent/tree/master/web-ui/app/locales

We're happy to have more, though :)

> This is a rough example of a minimalistic UI without exposed buttons. The actions feel natural and are intuitive. Context-sensitive options are only shown if they make sense. e.g. bulk actions are only visible when you select various mails. (see medium.com)

As I said above, shall we try to gather more input here, test a couple of ideas with pen and paper on the next hacknight?
