### ISSUE TITLE
Mail to self includes public key as UNNAMED attachment

### ISSUE THREAD

**Issue by thokari** [pixelated/pixelated-user-agent#608]
![screenshot from 2016-02-15 21 34 59](https://cloud.githubusercontent.com/assets/6663430/13059696/5aa8c298-d42c-11e5-88b3-731b88c65ec5.png)
![screenshot from 2016-02-15 21 35 21](https://cloud.githubusercontent.com/assets/6663430/13059697/5aacf886-d4e2c-11e5-909a-23320f52ad30.png)

The first email I sent to my newly created dev.pixelated-project.org account had an attachment with the name UNNAMED, which included my public key, but the second did not. If this is not intended, it might confuse the user.

**Comment by varac** [comment]
Hi @thokari i edited your post above and removed your email addr because it will possibly attract spam harvesters.

**Comment by mnandri** [comment]
@giovaneliberato I have reverted your commit for now... i didn't understand the logic behind changing/adding the submodules in...
so just to get the build green... please revert the revert later

**Comment by giovaneliberato** [comment]
@mnandri I installed the leap_mail in editable mode and that messed up with the code creating submodules files. Thanks for reverting the change.

**Comment by giovaneliberato** [comment]
For now, we decided to remove the attachments that have content type equals application/pgp-keys. Leap is verifying if they remove the key attached or not after importing it.

The problem with this approach is that if someone send a key attached, it won't appear :(
Any thoughts on that @albogabriel?

**Comment by giovaneliberato** [comment]
We implemented that, but in the wrong place.

The way we did, we would end with gpg calls every time a mail was being loaded from soledad. This lead to a very slow user agent and was not a very good decision.

Talking to leap, we decided that the leap_mail should exclude the keys after adding it to keymanager. Maybe here: https://github.com/pixelated/leap_mail/blob/develop/src/leap/mail/incoming/service.py#L639

**Comment by tuliocasagrande** [comment]
We started working reverting locally the previous changes.

Then, we found out that the problem with the attachment being UNNAMED is the `Content-Disposition` header written in **lower case**. We could fix that in [service/pixelated/adapter/mailstore/leap_mailstore.py#L172](https://github.com/pixelated/pixelated-user-agent/blob/e9776bd0524dca87f18fd366016b1236427d2518/service/pixelated/adapter/mailstore/leap_mailstore.py#L172) changing to:

    content_disposition = headers.get('Content-Disposition') or headers.get('content-disposition', '')

However, a better approach could be to fix the header itself. Leap side, maybe?

In addition - and I think it's more important - we noticed that every email sent to somebody else contains the sender public key, but when you send an email to yourself, only the first email contains this key. Are we filtering this in some other place of the user-agent?

**Comment by tuliocasagrande** [comment]
More thoughts about that:
Should we consider that sending the public key attached is a desired behavior?
Should we do that on every single email?

**Comment by bwagnerr** [comment]
If it's desired I don't know, we have to think about it. But it is definitely the currently defined behaviour.
All mails attach the public key when sending, but leap mail processes the public key as far as I understand

**Comment by zaraG** [comment]
> but when you send an email to yourself, only the first email contains this key
What do you mean by only the first mail? You are sending it to a couple of ppl + yourself and just the first recipient gets the pub key?

> Should we consider that sending the public key attached is a desired behavior?
Why not? I think it is very valuable.

> Should we do that on every single email?
I guess the first mail (to a recipient) should be enough.

**Comment by cz8s** [comment]
When I send the fist email to someone I have never sent a mail to before, the key is attached.
If I send a second mail to the same address, the key is not attached. Thats how leap-mail says it works. If it attaches the key even on the second mail, thats a bug.

**Comment by tuliocasagrande** [comment]
We talked to meskio and he said that the expected behaviour from leap-mail is:

> it should attach the key as long as you don't receive an encrypted email from this address
kind of an acknowledgement that the key was received

So looking for the reported case, the behaviour is as expected. Since you are sending an email to yourself, you're acknowledging that you received your own key. So the upcoming emails won't have the key anymore.

**Comment by felixhammerl** [comment]
![screen shot 2016-06-17 at 2 39 33 pm](https://cloud.githubusercontent.com/assets/1818340/16150753/5b103702-3499-11e6-9e73-6916214b4470.png)


key is there, has useful name :)
