### ISSUE TITLE
Sending is very slow

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#609]
Make sending async and send an email as errback if any error during the async sending

**Comment by mnandri** [comment]
What we eventually ended-up doing:
* Close the compose box/ inline box (for forward/reply/reply all) as soon as the send button is clicked.
* Ensure the growl shows appropriate feedback whenever the email is sent or failed to send... wherever page the user is in.
* Backend not changed

css: 
- success is still yellow
- failure is red

@pereiragislene  please feel free to add anything i missed.

**Comment by fbernitt** [comment]
Looks good, can be launched! Handling smtp erros had been extracted to issue #625.
