### ISSUE TITLE
Isolate display of mail content in iframe

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#617]
We are currently adding the content of emails directly to the DOM of our page. Even though we do some content escaping and filtering, an attacker might be able to bypass this and send a malicious mail that actually does some harm. To avoid this, we could isolate the display of the mail body into its own iframe.

```
<iframe sandbox="allow-popups" src="link to mail body"></iframe>
```

This would completely disable javascript within the iframe. This also means that some basic HTML-wrapping needs to be generated by the server. At the moment we are only rendering escaped text. This should remain for now.

Expected problems with iframe size responsiveness

**Comment by felixhammerl** [comment]
* [ ] send content to iframe via message passing [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), [example](http://robertnyman.com/html5/postMessage/postMessage.html)
* [ ] sanitize received content [DOMPurify](https://github.com/cure53/DOMPurify) [example](https://cure53.de/purify)
* [ ] style content in iframe
* [ ] iframe resizing, [example](https://github.com/davidjbradshaw/iframe-resizer)

**Comment by felixhammerl** [comment]
See changes on branch: 
https://github.com/pixelated/pixelated-user-agent/tree/dev/sandbox

**Comment by cz8s** [comment]
tried to break it and it didn't break. and everything is properly encoded in an iframe.

**Comment by cz8s** [comment]
need to merge!
