### ISSUE TITLE
Add recommended security headers

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#618]
When we run [securityheaders.io for try](https://securityheaders.io/?q=https%3A%2F%2Ftry.pixelated-project.org%3A8080%2F&hide=on).

Headers that are missing:
* X-Frame-Options
* X-XSS-Protection
* X-Content-Type-Options
* Public-Key-Pins

We could add the first three without any bigger side effects, only Public-Key-Pins depends on the server setup, so we should skip it for now.

Acceptance criteria **(updated)**:
The user-agent responds with these headers and use the recommended values:
- [ ] X-Frame-Options: SAMEORIGIN
- [ ] X-XSS-Protection: 1; mode=block
- [ ] X-Content-Type-Options: nosniff

**Comment by phss** [comment]
Might be a silly question, but what should the values be?

securityheaders.io suggests:
* x-frame-options: SAMEORIGIN
* X-XSS-Protection: 1; mode=block
* X-Content-Type-Options: nosniff

Is that good enough?

**Comment by fbernitt** [comment]
Very valid question! Yes, the recommendations should be good enough! Will update the acceptance criteria.

**Comment by phss** [comment]
Cool! Might take a stab at it if that's ok. Seems like a simple enough issue to get started. :)
