### ISSUE TITLE
Modularize stylesheets

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-user-agent#620]
The aim of this ticket is to restructure the currently messy style sheets in a modular way.

![q3cug29](https://cloud.githubusercontent.com/assets/1818340/13155648/f8f2b446-d67e-11e5-9967-fddbc38d0fb1.gif)

The first step will be to separate the UI into its modular building blocks, then rebuild the CSS from there. Concepts like OOP, DRY, the open/closed principle, separation of concerns, etc. still apply to CSS. Good CSS satisfies the following criteria:

* Predictable CSS means your rules behave as you’d expect. When you add or update a rule, it shouldn’t affect parts of your site that you didn’t intend. It also avoids cross-contamination by namespacing classes. A CSS rule should apply to one element, one type of mixin, etc. 
* Reusable CSS rules should be abstract and decoupled enough that you can build new components quickly from existing parts without having to recode patterns and problems you’ve already solved. Extend components with modifier classes. SASS allows to do that easily! You should never reach into an element from the parent selector, solely depending on where it's used. 
* Maintainable CSS means new components and features can to be added, updated or rearranged on our site without refactoring existing CSS. In order to do this, it is vital to avoid cross-contamination. If you want to replace a button with another one, this is possible because of a separation of positioning and visual representation. 
* Scalable CSS means our CSS architecture is easily approachable without requiring an enormous learning curve.

Other best practices and infos (this list should be updated as you go along):
* The CSS should use classes as the least specific selector possible
* Alphabetize your Properties
* Use rem for absolute and em for relatvie font sizes
* [SVG > Icon Font](https://css-tricks.com/icon-fonts-vs-svg/)

Here's the structure I'm proposing ("_" prefix in SASS filename means: *This is a partial*):
```
styles.scss (imports everything else)
|
|-- base
|   |-- _colors.scss
|   |-- _responsive.scss
|   |-- _fonts.scss
|   |-- _scaffolding.scss
|
|-- mixin
|   |-- (...)
|
|-- template
|   |-- (...)
|
|-- vendor
|   |-- _normalize.scss
|   |-- _scut.scss
|   |-- (any other framework)
|
|-- layout
|   |-- _nav.scss
|   |-- _mail-list.scss
|   |-- (...)
|
|-- views
|   |-- _nav.scss
|   |-- _mail-list.scss
|   |-- (...)
|
|-- _others.scss
```

#### Definition of Done
The CSS satisfies the above criteria and does not change the current visual style in any major way.

#### Dependencies
This ticket depends on the cleanup done in #616. 

#### Dependent tickets
This ticket is a preparation for #537

**Comment by felixhammerl** [comment]
github findings on svg vs icon fonts: https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by felixhammerl** [comment]
Helpful resources:

* [Check browser compatibilty for APIs and CSS propertiers on caniuse](http://caniuse.com/)
* [Sass playground](sassmeister.com)
* [SASS Guide](http://sass-lang.com/guide)
* [What is BEM](https://mattstauffer.co/blog/organizing-css-oocss-smacss-and-bem)
* [Chris Coyer's CSS Tricks w/ tons of simple hacks and solutions to everyday problems](https://css-tricks.com/)
* [Lea Verou's book CSS Secrets](http://www.amazon.com/CSS-Secrets-Solutions-Everyday-Problems/dp/1449372635)
* [MDN](https://developer.mozilla.org/en-US/Learn/CSS)

VIM
* [SCSS Syntax](https://github.com/cakebaker/scss-syntax.vim)
* [CSS3 Syntax](https://github.com/hail2u/vim-css3-syntax)
* [Autoformat w/ SCSS support](https://github.com/Chiel92/vim-autoformat)

**Comment by re-nobre** [comment]
We agreed to split this issue in small ones and put the label [Modularize stylesheet.](https://github.com/pixelated/pixelated-user-agent/labels/Modularize%20stylesheets)
So, I'm closing this issue.
