### ISSUE TITLE
Hide email reply buttons until content has been loaded

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#622]
Currently, while an email is loading, the reply/forward actions are already available. We want to load it only after the rest of the content is also available.

![image](https://cloud.githubusercontent.com/assets/350155/13206806/5695abaa-d8e4-11e5-86ce-6de0bbccde54.png)

Note: there will be a follow-up for this story including some sort of loading state feedback to be adopted to other actions.

**Comment by felixhammerl** [comment]
there's a couple of things i'd like to improve in here, if that's ok with you. please assign to me when you're done.

**Comment by felixhammerl** [comment]
relevant commit: https://github.com/pixelated/pixelated-user-agent/commit/59532a5

**Comment by felixhammerl** [comment]
There's some open points here:

* `events.mail.draftReply.notFound` is no longer listened to (https://github.com/pixelated/pixelated-user-agent/commit/59532a5)
* nobody is listening to the results of this [code branch](https://github.com/pixelated/pixelated-user-agent/blob/59532a50c8b0233b2a596b996cbe799b745c4fac/web-ui/app/js/services/mail_service.js#L293-L307) anymore
