### ISSUE TITLE
Unhandled outgoing send_message errors

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#625]
whenever OutgoingMail.send_message has errors it actually never gets propagated to the mails_resource controller... 
As a result, the user never actually see any feedback about failure to send emails...
handling and showing errors on email sending is a feature that exits but basically will never be seen/used by the user.

To see/investigate:
- handle_post method in mails_resources.py
- _send_mail_to_all_recipients method in mail_sender.py
- send_message method in leap.outgoing.service.OutgoingMail

to reproduce:
trigger error in _route_msg in leap.outgoing.service.OutgoingMail it will not get shown in the browser...

**Comment by re-nobre** [comment]
hey @mnandri!
Do you think it keeping or it solved?

**Comment by ayoyoness** [comment]
picking this up as part of #851

**Comment by re-nobre** [comment]
hey, @ayoyoness!
Should we blocked the #851 until this issue be finish?

**Comment by ayoyoness** [comment]
yes yesterday
no as of now :)

**Comment by ayoyoness** [comment]
Details:
https://0xacab.org/leap/bitmask-dev/commit/db8567e5035978dc16fd5bbac9aecb73b600d41e
fixed leap.mail errors not bubling up to mails resources

https://github.com/pixelated/pixelated-user-agent/commit/0dd71ff7c3a895e774205231c23720ee7313ad39
fixed logs raising exceptions as they had typo

now email sending errors should be logged properly and is shown in the front-end.

**Comment by deniscostadsc** [comment]
@ayoyoness 

I raised an ordinary  exception on the `_rout_msg` method, and I could see a message about timeout that I never saw before, is that it? If yes, we can put this message to Done.

**Comment by ayoyoness** [comment]
@deniscostadsc, no it should have something like the screenshot below.

![screen shot 2016-12-05 at 11 17 18 2](https://cloud.githubusercontent.com/assets/2129786/20884670/e0e6bb74-baec-11e6-942f-945f0621a9b5.png)

**Comment by thaissiqueira** [comment]
We lunch the follow exception on [this line](https://0xacab.org/pixelated/bitmask-dev/blob/master/src/leap/bitmask/mail/outgoing/service.py#L218) and we got the right message: "Error, message not sent: an error occurred while sending":

```
       self.sendError(Exception('Pareando com Anike'))
        return
```

So, we consider this done.
