### ISSUE TITLE
WARNING Invalid JSON data from key

### ISSUE THREAD

**Issue by gomex** [pixelated/pixelated-user-agent#627]
I am trying to send mail to my address, but I can't see the green padlock icon.

My public key is published: https://pgp.mit.edu/pks/lookup?search=linux.rafa%40gmail.com&op=index

I got this error on my pixelated-user-agent logs:

[leap.keymanager] WARNING Invalid JSON data from key: https://nicknym.dev.pixelated-project.org:6425/?address=linux.rafa@gmail.com

**Comment by meskio** [comment]
Just for the record I just opened an issue for this in our tracker:
https://leap.se/code/issues/7987

I have the feeling this is a 404 not properly treated.

**Comment by deniscostadsc** [comment]
@gomex I accessed this URL[1], but I didn't see a error. Does this still valid?

[1] - https://nicknym.dev.pixelated-project.org:6425/?address=linux.rafa@gmail.com

**Comment by zaraG** [comment]
[The PR to this ticket](https://github.com/leapcode/keymanager/pull/110)

**Comment by deniscostadsc** [comment]
👌
