### ISSUE TITLE
Feedback message is showing "[object Object]"

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#630]
After sending a email I got this feedback message.

<img width="353" alt="screen shot 2016-02-24 at 5 19 43 pm" src="https://cloud.githubusercontent.com/assets/358777/13299691/082f3bdc-db1b-11e5-9de3-9d64d89c8692.png">

**Comment by AdamNowotny** [comment]
Not able to reproduce this, getting the correct "Your message was sent!" message. Does that happen every time you send an email?
If you can reproduce, can you look at the browser console? There should "trigger: mail sent" event. If you could expand that and send screenshot that would help a lot

**Comment by zaraG** [comment]
Could not reproduce.
