### ISSUE TITLE
Kiss your address goodbye when you click off it

### ISSUE THREAD

**Issue by gusandrews** [pixelated/pixelated-user-agent#631]
Hi! I'm preparing to run some user tests on the try.pixelated demo at the IFF next week. In planning how to run the test, I found this bug:

https://www.youtube.com/watch?v=d2s4bYvBZ1M

tl;dr: When running the PM demo in Firefox on Windows 7, I enter an address in the To: field which has a verifiable key. 
PM gives it a green lock icon and turns the address in the To: field into a button. 
When I click on that button, it allows me to edit it, as it should. 
If I edit it, everything is apparently fine! 
If I do NOT edit the address, and I click out of the To: field, the address in the To: field disappears.
What should happen is that it returns to being buttonlike.

(There's a bonus request in that video but I'll file it separately ;))

**Comment by jeffhsta** [comment]
@gusandrews This issue happens not just on Windows, I already found out that.

We will check if there is an issue already opened for that and work on that soon.

Thanks for the feedback.

**Comment by gusandrews** [comment]
Still happening, on Mac in Firefox, as of today -- was there another bug filed elsewhere?

**Comment by tuliocasagrande** [comment]
It seems that the blur event was not working as expected. So we changed it to focusout.
@felixhammerl Do you know if this can bring us any trouble?
