### ISSUE TITLE
Less-scary demo emails, please?

### ISSUE THREAD

**Issue by gusandrews** [pixelated/pixelated-user-agent#632]
Hi team, I'm planning to run user tests on Pixelated Mail next week at the Internet Freedom Festival. Right now, the demo content in the emails is kind of frightening in a way which is likely to make users distracted, and possibly confused about Pixelated's security properties, while they go through tests.

Headlines like "How the USA Is Supporting ISIS. Join Russian" are kind of funny, but they give me a weird feeling in my gut that this email program is full of creepy spam. I showed the email headlines to my neighbor at my coworking space, and she was weirded out and distracted by the politicalness of the subject lines and the misspelling ("Russian" instead of "Russia.")

The trainers who attend the IFF will definitely be people who have and understand security concerns, but putting security-themed content in the test emails is likely to make their judgments of PM's security properties skew more negative. I often see users latch on to weird superficial elements in user tests, and these emails seem likely to distract and confuse them. Even the random-walk nature of the subjects and mail might be frightening -- it looks like a mailbox full of spam.

It might also be nice to avoid curse words in the subject lines. I don't mind them, but they may alienate some potential testers.

Could you populate the demo build with emails that are a little less distracting, please?

Thanks :)

**Comment by fbernitt** [comment]
Hey, the content is based on the [cypherpunks mailing list](https://www.cypherpunks.to/list/), fed into a markov chain. Do you have any recommendations for another mailing list we could use instead? Idea was to not hand-craft hundreds of example mails but also not have lorem ipsum content.

**Comment by varac** [comment]
When random shuffling of words (using a markov chain) turns out to produce irritating results, we should not do it.
I don't follow the  cypherpunks mailing list, but when cursing there is popular, we should also switch to another ml. Why not pick another ml related to the project ideas, like  [moderncrypto messaging](https://moderncrypto.org/), [leap-discuss](https://lists.riseup.net/www/info/leap-discuss), or others ?

**Comment by gusandrews** [comment]
Yes, I would recommend not using markov chains -- after all, that's what spammers do. They make text look spammy. 

Leap-discuss is a better idea (moderncrypto might still look a bit scary) -- but why not use a regular business email corpus, which will mostly look like everyday, non-technical email? May I suggest the Enron corpus? https://www.cs.cmu.edu/~./enron/ I imagine it's mostly banal, with the added bonus that if someone realizes it's the Enron corpus they might get a good laugh out of that.

**Comment by cz8s** [comment]
changed to moderncrypto 2015 for now because leap does not have an archive and I couldn't create a mbox without all the headers from my local leap-discuss folder.
Its quite easy to change if we don't like the outcome.

**Comment by gusandrews** [comment]
Thanks cz8s, I really appreciate the quick response to all this! When should I expect to see the change in the demo?

If it's easy to change, could we switch to http://listserv.aoir.org/pipermail/air-l-aoir.org/ ? It's a little less technical.

**Comment by cz8s** [comment]
the air-l archive is quite small. I fear its not enough input for our random mail generator. I will comment here when the new content is on try and then lets see how it looks and if we should improve.

**Comment by gusandrews** [comment]
Is Air-L too small for *scraping* email rather than *markoving* email, though?

**Comment by cz8s** [comment]
if we just copy the air-l, the to: and from: will be wrong and people might wonder why mails they have written end up on our demo. And we won't have any example tags

**Comment by gusandrews** [comment]
yeah, I was wondering about using other people's corpuses. (enron tho :D)

**Comment by cz8s** [comment]
@gusandrews : have a look at try. Mails are much better now.

**Comment by varac** [comment]
I see that most of first few emails in the Inbox are cut off right in the middle of a sentence. Also, some of the mails appear to have merged paragraphs where line breaks could have been. 
This could lead to users thinking mails are badly parsed/displayed, and we should fix that.

**Comment by gusandrews** [comment]
It looks *way* better with these emails :) TBH I don't think people will feel strange about paragraphs or truncations -- if they scan anything, it's most likely to be subject headings, and those now look much more normal. The text also looks normal. If I don't ask them to read closely, and I won't, I don't think they will notice anything else at all.

Thank you all so much for your attention to this!
