### ISSUE TITLE
Display new mails after login/logout/login sequence

### ISSUE THREAD

**Issue by fbernitt** [pixelated/pixelated-user-agent#634]
In multi-user setup, if a users logs in and logs out more than once (e.g. login/logout/login), he will no longer get any new mails.

The actual problem seems to be in the leap_mail library and there in the IMAPMailbox class. It has a class-level dictionary where it puts all event listeners. Class level means its not distinguishing between multiple users (or multiple sessions of the same user). That means e.g. if a users logs out and logs in, the event handler for the previous session could be called.

**Comment by cz8s** [comment]
I think folker still has some code on his laptop that needs to be packet into a pr. But I am not shure.
The symptom is gone anyway

**Comment by cz8s** [comment]
created a pr to leap:
https://github.com/leapcode/leap_mail/pull/228
