### ISSUE TITLE
Signed+encrypted mail from Thunderbird shows up as 'not signed'

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#635]
What: 

Sending an signed, PGP/Mime-encrypted mail from my TB shows up as 'not signed, encrypted'.

Details: 
I'm using TB1:38.5.1+build2-0ubuntu0.15.10.1/Enigmail 1.9 (20160223-1641)/gpg 2.0.28-3ubuntu1, and send the mail PGP/Mime encrypted.

Done: 
It should show up as 'Signed, Encrypted'

**Comment by varac** [comment]
Dor the record, i already replied to my external email adr before i recieve the 'not-signed' mail.

**Comment by re-nobre** [comment]
thaissiqueira and @cacarrara,

as you solve the #605 
what do you think we should do with this issue?

**Comment by cacarrara** [comment]
Sure, we can see if it's fixed or there anything else to be done.

**Comment by cacarrara** [comment]
@thaissiqueira I've tried to reproduce it again, but I couldn't. Could you?

**Comment by re-nobre** [comment]
@varac as you use a different machine with a different setup, I think it''be good if you test it.
Can you try to reproduce this again?

**Comment by varac** [comment]
It's not fixed :(
unstable is running the latest version of the useragent (c384e5f from 2016-06-07), and the signed+encrypted mail is still displayed as "Not signed / Encrypted" as you can see in this screenshot:

![Uploading Screenshot_2016-06-13_10-48-48.png…]()

You can have a look yourself logging into unstable.pix as "testuser" (pw is stored in the credentials repo).

**Comment by varac** [comment]
![screenshot_2016-06-13_10-48-48](https://cloud.githubusercontent.com/assets/488213/16001882/f1c05eb8-3154-11e6-98d5-b149b3448ba4.png)

**Comment by thaissiqueira** [comment]
@varac doesn't worked to me on unstable too. But to me is working on dev end wazokazi. Could you test again on dev or wazokazi, please?

If you prefere we can do it together.

**Comment by varac** [comment]
I did send another email to dev.pix and wazokazi to "testuser". Same result, please login as testuser and see yourself.

**Comment by thaissiqueira** [comment]
Even using "testuser" the encrypted and signed labels worked for me.
Now I'm trying to reproduce in a thunderbird ubuntu version.

**Comment by thaissiqueira** [comment]
@varac,

Trying to reproduce this problem we sent an encrypted and signed email 
using: 

- Enigmail version 1.9.3 
- gpg (GnuPG) 2.1.11
- GPG/MIME setted by default
- Thunderbird 38.8.0 installed on ubuntu 16.04 

And even so it worked for us 😕

<img width="1069" alt="screen shot 2016-06-16 at 2 45 40 pm" src="https://cloud.githubusercontent.com/assets/13627260/16127139/86b4c94a-33d1-11e6-95b6-5818d3302084.png">

One other thing that we did before to send this email was import the key of "testuser" through Key Manager of Enigmail, but just it.

Maybe we can pair on Monday and try to understand what is happening.

What do you think?

**Comment by felixhammerl** [comment]
@varac sorry for the stupid question, but 1) you're *sure* you signed the mail, and 2) you're sure your public key was there because you already sent a mail from that provider to your external address and it was able to encrypt it, right?

**Comment by varac** [comment]
@thaissiqueira Let's please use non-personalized test accounts for collecting mails from different mailclients.
Then everybody is able to see the recieved mails.

 I propose to use `testuser@unstable.pixelated-project.org`

**Comment by thaissiqueira** [comment]
ok

**Comment by thaissiqueira** [comment]
Analysing this problem we conclude:
The private key used to sign doesn't belong to same key pair stored on Pixelated server.

@cz8s , could you check if you are using the right key to sign?

If you are using the right key, the problem is happening because your key are expired. On this case we will open a  new issue.

**Comment by thaissiqueira** [comment]
This issue will be solved by issue #734
