### ISSUE TITLE
New Mail is indicated in the Inbox symbol, but doesn't appear in the list of mails

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#640]
Symptom:

- I wrote a mail to the team on wazokazi.is, including me.
- A "1" appeared over the Inbox symbol indicating that a new mail has arrived
- I don't see the new mail when i click on the Inbox symbol.
- When i reload the page, it appears also in the list of mails.
![screenshot_2016-03-08_14-32-32](https://cloud.githubusercontent.com/assets/488213/13603067/eb8398e6-e53a-11e5-888d-54de3c7ad8d5.png)

**Comment by cz8s** [comment]
this was on wazokazi, right?
I don't think we will be able to reproduce this, because since we are running multi-user now,
we changed quite a lot in the session management.

**Comment by re-nobre** [comment]
I tested in my account sending an email from me to me. It took a long time to arrive but the number and the email appearead at the same time.
Can you test with your account one more time , @varac?

**Comment by varac** [comment]
couldn't reproduce, i'm fine with closing this issue for now.
