### ISSUE TITLE
package the web-ui for the python ecosystem?

### ISSUE THREAD

**Issue by kalikaneko** [pixelated/pixelated-user-agent#642]
As you probably know by now, we want to be able to ship Bitmask client with the Pixelated MUA.
I was wondering if you have considered packaging al the (compiled) web-ui for the python ecosystem, so that it can be just pip-installed inside an env.

I have to check details, but for instance buildbot does something very similar to this.

**Comment by kalikaneko** [comment]
PR #664 implements this

**Comment by mnandri** [comment]
okay, so we're extending this discussion to debate whether we should go even further by splitting the backend and frontend into two repos... 

The discussion is in the PR. Please respond there.

**Comment by mnandri** [comment]
For the record,

we have decided that:
- Find ways to make the pixelated_www package as is specified by kalyi above, from our existing setup.py (in service): corresponding issues  https://github.com/pixelated/pixelated-user-agent/issues/729 and https://github.com/pixelated/pixelated-user-agent/issues/730
- Find ways to move the go command to the root folder in the pixelated repo: corresponding issue https://github.com/pixelated/pixelated-user-agent/issues/731

**Comment by deniscostadsc** [comment]
We put the PR on this branch https://github.com/pixelated/pixelated-user-agent/tree/package-www

It broke the package because PR added a second setup.py. We need to discuss that.

**Comment by thaissiqueira** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
