### ISSUE TITLE
Include Timestamp with commit id in sidebar

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#644]
Very often, i need to know what version of the useragent is running i.e. on wazokazi or local vagrant installations.

Parsing the git log is for the id is annoying, and it would be most helpful if we would add a timestamp to the commit id, because in 99% of all cases, I want to know if it is a recent useragent (from today or yesterday).

**Comment by cacarrara** [comment]
Well done @zaraG :smiley: 

Probably we will need to start thinking about a better place to put this info. But, for now it should be enough.
