### ISSUE TITLE
Modularize Compose View

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-user-agent#646]
This issue is about modularizing the compose view, according to the overarching CSS refactoring issue https://github.com/pixelated/pixelated-user-agent/issues/620
#### Done

This ticket is done when the composer view is refactored in BEM manner, making it easier to refactor in the future. The general layout must not be changed.

**Comment by re-nobre** [comment]
hey, @felixhammerl!
Is it possible that someone solve it on the Hacknights or as a volunteer task?

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
