### ISSUE TITLE
Refactor security labels stylesheet

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-user-agent#647]
This issue is about refactoring the [security status styles](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/scss/_security.scss), according to the overarching CSS refactoring issue #620

I assume it would make sense to integrate the label styles into the [read-view](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/scss/views/_read-view.scss), where they are actually used.

#### Done

This ticket is done when the security styles are refactored in BEM manner, making it easier to refactor in the future. The general layout must not be changed.

**Comment by albogabriel** [comment]
Reviewed the stylesheets and the app running. It all looks good :)
