### ISSUE TITLE
Refactor mail list styles

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-user-agent#648]
The [_styles.scss](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/scss/_styles.scss) file has been used as a pool where all the styles that didn't fit elsewhere have been poured in.

One first step is to extract the mail list view, move it to a dedicated file, and refactor the markup and styles.

**Comment by felixhammerl** [comment]
NB: After merging, this will break the [MailList Page Object](https://github.com/pixelated/puppet-pixelated/blob/master/files/functional-tests/page_objects/mail_list.py). Please update accordingly!

**Comment by cacarrara** [comment]
Hi, @felixhammerl! @thaissiqueira and I have reviewed this refactor and we note the following:

- [ ] Attachment icon position (we think that 15px margin-right should fix)
With your changes:
![image](https://cloud.githubusercontent.com/assets/348237/14234785/04f23896-f9c2-11e5-9dfb-7ccade753be5.png)
Without your changes:
![image](https://cloud.githubusercontent.com/assets/348237/14234789/21f91d88-f9c2-11e5-9b49-3ca893f82e20.png)

- [ ] Draft and Trash icon color
With your changes:
![image](https://cloud.githubusercontent.com/assets/348237/14234794/3c768812-f9c2-11e5-904c-cd95b9e90391.png)
![image](https://cloud.githubusercontent.com/assets/348237/14234798/61cc64b0-f9c2-11e5-8a42-b6e9777fb4de.png)
Without your changes:
![image](https://cloud.githubusercontent.com/assets/348237/14234795/485fe4fc-f9c2-11e5-86b2-b4c817497910.png)
![image](https://cloud.githubusercontent.com/assets/348237/14234800/7034f17a-f9c2-11e5-9728-093d694604a2.png)

So, as you told us before, we're assigning you again on this task.

**Comment by felixhammerl** [comment]
I actually like the attachment icon position better this way, seems kinda more ordered to me when it's properly right-aligned, same as the upper text border being aligned with the upper checkbox border. I'll bring it up in the daily. If somebody has strong opinions, we can change it ...
