### ISSUE TITLE
Error running functionals on vagrant

### ISSUE THREAD

**Issue by cacarrara** [pixelated/pixelated-user-agent#651]
The steps are these:

```
# Clone project
vagrant up
vagrant ssh
    cd /vagrant/web-ui
    ./go test (run successfully)
    cd ../service
    ./go test (run successfully)
    ./go functional (fail - output: http://paste.debian.net/416587/)
    cd ../web-ui
    ./go build
    cd ../service
    ./go functional (fail - output: http://paste.debian.net/416587/)
```
You can see that I just followed the User Agent README instructions so I also tried run `web-ui/go build`.

Anyone has any suggestion about what I could try to solve it?

**Comment by felixhammerl** [comment]
next thing on my issues stack. incredibly annoying.

**Comment by cacarrara** [comment]
Just in case it would be relevant, here are the vagrant npm packages installed (http://paste.debian.net/416604/) and also the python dependencies (http://paste.debian.net/416606/).

**Comment by cz8s** [comment]
depending on where I run the tests, they fail with different scenarios:
* on my laptop the fail at 'When I upload a valid file'
* on vagrant, they fail with 'Given I have a mail in my inbox'

I fear I am not of real help here ...

**Comment by bwagnerr** [comment]
I bumped the version of phantomjs on the vagrant to match the one in the CI. That fixed the problem (previous version didn't understand selenium keep-alive)

**Comment by cz8s** [comment]
works on my vagrant box now

**Comment by cz8s** [comment]
we use phantomjs 1.9.8 for the web-ui tests.
Maybe use the same version for both?
And installing two versions of phantomjs is suboptimal anyway, right?

**Comment by cacarrara** [comment]
Here I've destroyed and created vagrant machine again and now everything worked. The phantomjs version installed on vagrant is the 2.1.1. I think @bwagnerr lock this version on this commit 6855ac9

**Comment by cz8s** [comment]
if phantomjs is installed before karma, karma will use this phantomjs.
I had phantomjs 2.3.1 installed and karma used it. 
sadly the tests fail with this setup.
So either we leave it as it is for now, or we need to have look at it.
Latest karma still installs phantomjs 0.9.8. Maybe for a reason :)
We just need to be aware that this will break once karma installs a newer
phantomjs version.

**Comment by cacarrara** [comment]
Well, at least on Vagrant provisioning process karma 2.1.1 is going to be installed before karma-phantomjs-launcher (https://github.com/pixelated/pixelated-user-agent/blob/master/provisioning/modules/pixelated/manifests/source.pp#L3 / 6855ac9). Also, as the problem running functionals is solved, I think we can leave it as it.
