### ISSUE TITLE
JS minification

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#655]
Includes:
- remove all min and use normal js for all used libraries, pre-minification
- remove jquery-ui
- fix CI/npm minify so that it fails on CI whenever the minification fails... so that we are notified but also, broken js going into prod

**Comment by mnandri** [comment]
after investigation the plugin we use for attachment file upload uses jquery-ui... so we cannot remove it... for now.

**Comment by re-nobre** [comment]
Hi, @mnandri!
@pereiragislene and me pairing on it to do the QA.

Since it's not possible to remove the jquery-ui, we tried to check the other two points of this issue.

About the first one, we saw your commit with the updates. 
About the third point, we also saw on the commit that you put one condition to add the minification failed message. 

Have you finished the CI setup to get the failed status? How we can check it?

**Comment by mnandri** [comment]
the CI pipeline is already setup
https://go.pixelated-project.org/go/tab/pipeline/history/jessie-pixelated-user-agent-packaging
the settings is here
https://go.pixelated-project.org/go/admin/pipelines/jessie-pixelated-user-agent-packaging/general

unfortunately there is no simple way of testing/simulating it to fail.
the only way is to:
either check-in something that will fail the minification (for example re-introduce the minified libraries) 
but that wouldn't really make sense (check in wrong code to test ci)
or create a parallel go-cd ci that has the same config as what we have then fork the repo and push the failing minification code to that... the parallel ci then should use the forked-repo

The compromise is to try it on vagrant... revert the code to the failing minification and add back the code that catches the failure... and test from that. Not exactly the same but relatively close...

**Comment by bwagnerr** [comment]
I would revert the code and test the steps really, they shouldn't be hard to reproduce and could give us a fairly certainty

**Comment by cz8s** [comment]
i checked out cc7b3434863602b8e3bf351a5c0b1c4673c5c651 and saw that the app.min.js was 0 bytes. I then built with head and app.min.js was correct.
I'd say, that proves that the issue is fixed
