### ISSUE TITLE
opensans.css file is not found inside iframe

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#656]
## What
When opening a mail message, an error is displayed on the javascript console saying the opensans.css file was not found.
The error is displayed both locally and in Wazokazi.

<img width="1440" alt="screen shot 2016-03-22 at 11 22 55" src="https://cloud.githubusercontent.com/assets/554552/13954852/499790b8-f021-11e5-80a7-f147d16c3cc2.png">

## Definition of Done
The opensans.css file should be found when opening a mail message.

**Comment by felixhammerl** [comment]
I know why this happens (oops, my bad). I'll see if we can fix that today
during the hacknight, otherwise i'll fix it myself tomorrow.

**Comment by felixhammerl** [comment]
Relevant PR: https://github.com/pixelated/pixelated-user-agent/pull/660
Will continue working on that today/tomorrow

**Comment by pereiragislene** [comment]
It works fine. Can be launched :+1:
