### ISSUE TITLE
Add spinning logo before the email loads

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#657]
As a user opening an email
I want to see a indication while the email body is being loaded
So I know I have to wait to see it.

Currently, the email body is taking a bit long to load. We want to show a specific loading animation so users are aware of that and do not get confuse when they see a blank space in the email body.

Logic and style are the same as story #238, but with different colors:

![image](https://cloud.githubusercontent.com/assets/350155/13961386/234e5d3c-f03b-11e5-927b-bedbbec9c53e.png)

The logo color should be #C2C2C2 ($light_gray), and the animated parts should be 10% lighter (lighten( $light_gray, 10)).

The loading animation should last as long as the actual iframe loading does.

**Comment by felixhammerl** [comment]
Further information:

* [Build Toolchain](https://github.com/pixelated/pixelated-user-agent/wiki/Build-Toolchain)
* [CSS Architecture](https://github.com/pixelated/pixelated-user-agent/wiki/CSS-Architecture)
* [JS Architecture](https://github.com/pixelated/pixelated-user-agent/wiki/JS-Architecture)

**Comment by tayanefernandes** [comment]
@SweetVirginia Should we keep the same design suggested on the description?

**Comment by thaissiqueira** [comment]
> Currently, the email body is taking a bit long to load.

We are seeing the same problem even before load the header.
![screen shot 2017-01-25 at 4 19 42 pm](https://cloud.githubusercontent.com/assets/13627260/22303420/6199570e-e31a-11e6-8902-5b822031aa0f.png)

**Comment by tayanefernandes** [comment]
We added the spinner just before load the first part of the email (header with the title). We will create a new issue to make the email loads at once.
