### ISSUE TITLE
Failed vagrant up

### ISSUE THREAD

**Issue by repat** [pixelated/pixelated-user-agent#658]
During Hamburg hacknight, i followed the instructions on the read.me and it got the error in the attached file.
 
[pixelated-hacknight.txt](https://github.com/pixelated/pixelated-user-agent/files/184710/pixelated-hacknight.txt)

**Comment by bwagnerr** [comment]
Hello, it looks like a network error when downloading the phantomjs package, trying again should be enough. (for the record, the error returned was 429, too many requests)

**Comment by repat** [comment]
I just tried it again
```
vagrant destroy
rm -rf web-ui/node_modules/
vagrant up
```

Thanks!
