### ISSUE TITLE
Display  the author of previous segment of a replied/forwarded message

### ISSUE THREAD

**Issue by lqust** [pixelated/pixelated-user-agent#66]
* On reply or forward, append the sender of the message being replied and the timestamp on top of the replied or forwarded text

**Comment by lqust** [comment]
The classic `On 21 January 2015 at 16:01, Alice <alice@try.pixelated-project.org> wrote:`

**Comment by dudadornelles** [comment]
I guess this is done via d3c86f867d29b79eec1d280389975c920a7ec196 correct?

**Comment by rdoh** [comment]
Agreeing with @dudadornelles - I think this should be closed.

**Comment by neissi** [comment]
This issue is already done.
