### ISSUE TITLE
big mailboxes will take too long to sync when switching to multi-user

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#661]
on wazokazi we have big mailboxes. when we migrate from docker to multi-user, all accounts will have to start the initial sync again.
this will take too long for some accounts.
Maybe we should migrate the databases to avoid the initial sync?
Pleas discuss :)

**Comment by cacarrara** [comment]
Well, to help us decide what path to follow, it would be nice see pros and cons about the two choices. Seems that migrating the databases to avoid initial sync has only pros, but that is my limited point of view up to now.

**Comment by bwagnerr** [comment]
It is not clear to me how we would migrate the user agent databases (considering we can't open them, because we don't have the user passphrase). Even then it would be nice if we could have a separate location for the user databases as we do on the docker UA, so that we could store the user data outside the application, is that possible today?

Also that would be a non-issue concerning couchdb as far as I'm aware, because the server side database would remain intact.

**Comment by shyba** [comment]
It's possible to move the database file and try to open on multi user, but
I am not updated with latest changes.

From a server side point of view, I totally agree with Bruno. Server should
handle it.

From a soledad client side view... Soledad latest changes aren't merged,
which means multiprocessing is still there. I would (even if temporarily)
cherry-pick those soledad commits to help during this large scale initial
sync.
I am talking to Ayoyo during free time to hurry up this merge, but I think
he can load test to see how that sync would behave. (create X big accounts
and sync them all together).

Miss you all! S2

2016-03-28 12:13 GMT-03:00 Bruno Wagner Gonçalves <notifications@github.com>
:

> It is not clear to me how we would migrate the user agent databases
> (considering we can't open them, because we don't have the user
> passphrase). Even then it would be nice if we could have a separate
> location for the user databases as we do on the docker UA, so that we could
> store the user data outside the application, is that possible today?
>
> Also that would be a non-issue concerning couchdb as far as I'm aware,
> because the server side database would remain intact.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated/pixelated-user-agent/issues/661#issuecomment-202432599>
>



-- 
Victor Shyba

**Comment by cz8s** [comment]
If we migrate, no data will be lost, because everything is stored in couch and that will not be touched when migrating to multi-user. Problem is, that the couch has to be synced to local sqlite dbs and that might take more than 30minutes on some accounts. (I tried with my account when I accidentially migrated wazokazi and it wasn't finished after 30minutes)
So here are the files on wazokazi:
```
/var/lib/pixelated/dispatcher/USERNAME/data/ACCOUNTUID/soledad/
```
and on staging:
```
/var/lib/pixelated/.leap/ACCOUNTUID/soledad/
```
My question is:
If we copy the directories from the old to the new location, will that work?
That seems to be an easy task if it works.

**Comment by bwagnerr** [comment]
I'm fairly certain that that would work, but there's still the issue of the smtp certificate that is unique to each user and is supposed to be somewhere on that folder too

**Comment by cz8s** [comment]
they are in
```
/var/lib/pixelated/.leap/ACCOUTUID/providers/HOSTNAME/keys/client/smtp.pem
```
That should be easy to migrate aswel

**Comment by bwagnerr** [comment]
Then it should be golden :)

**Comment by cz8s** [comment]
can we somehow test this? unstable is running a non-multi-user setup right now, right?
Maybe we should test how migrating works with that machine?

**Comment by re-nobre** [comment]
I removed the  Migration label, because the migration was a label related with the bitmask 0.7 migration

**Comment by cacarrara** [comment]
So, as far as I could look with opinions on this thread, we definitely should run this "switch process" on unstable and see if everything will work well. The steps can be:

```
1. Copy data files
2. Copy smtp certificates
3. Deploy UA multi user
```

Is that correct? Should we create a task to it?

**Comment by cz8s** [comment]
yes. lets do this.

**Comment by deniscostadsc** [comment]
I would like to pair on those issues.

**Comment by deniscostadsc** [comment]
I created the three issues.

https://github.com/pixelated/pixelated-user-agent/issues/671
https://github.com/pixelated/pixelated-user-agent/issues/672
https://github.com/pixelated/pixelated-user-agent/issues/673

**Comment by re-nobre** [comment]
As Denis created new issues to resolve it, I'm closing this issue
