### ISSUE TITLE
search_index: path change proposal

### ISSUE THREAD

**Issue by kalikaneko** [pixelated/pixelated-user-agent#668]
currently, the path for the whoosh search indexes lies directly in the .config/leap folder, which kind of pollutes it, specially when there are many accounts on the same machine.

/home/kali/.config/leap/dc497c23fc8997a7b02cda9ff5643c16/search_index

suggestion: moving it under whoosh or pixelated subfolders, or inverting the order (search_index/<uid>).

**Comment by kalikaneko** [comment]
bumping this. it clogs a lot the shared leap folder.

**Comment by mnandri** [comment]
@tuliocasagrande 
it looks good.
Although, it's a bit of magic 'number' you got there on [line 59](https://github.com/pixelated/pixelated-user-agent/blob/e70df3d6d654c13992d5f58b9c2b7606548e3316/service/pixelated/config/services.py#L59).
