### ISSUE TITLE
Trigger loading animation for mail list actions

### ISSUE THREAD

**Issue by albogabriel** [pixelated/pixelated-user-agent#669]
(Missing functionalities from #238 )

Currently, the email list actions (below) are not triggering the logo loading animation. 

The actions that should activate it are:

- [ ] Mark as read
- [ ] Mark as unread
- [ ] Delete email (both on the email list and on the email view)
- [ ] Archive email
- [ ] Reply email
- [ ] Reply to all (both below the email body and on the down arrow)
- [ ] Forward email

![image](https://cloud.githubusercontent.com/assets/350155/14146771/34ddbaa4-f66f-11e5-9420-e94f249e845f.png)

![image](https://cloud.githubusercontent.com/assets/350155/14146831/7a236938-f66f-11e5-9869-7be667099707.png)

![image](https://cloud.githubusercontent.com/assets/350155/14146886/a8fc2d62-f66f-11e5-9f60-a1d0cff8b0da.png)

Note: if for some reason it makes sense to split this issue, please do :)

**Comment by re-nobre** [comment]
I talked with @SweetVirginia and we will analyse all the UX proposals in a different place and create the issues when we will work on it.

For all the UX/UI proposals and feedbacks, take a look [here](https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

I'm closing this issue now.
