### ISSUE TITLE
Copy data files to migrate emails users

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#671]
Discussion on https://github.com/pixelated/pixelated-user-agent/issues/661

**Comment by zaraG** [comment]
We checked in a migration script in https://github.com/pixelated/puppet-pixelated/blob/master/migrate_data_from_dispatcher_to_multi_user_agent.sh
To be run in wazokazi or in unstable for QA.

Unfortunately, we have deleted all users in unstable... so please follow the steps bellow to QA:

1. Register a already existing user at unstable (find out username in ls /var/lib/pixelated/dispatcher), use the correct old password.
2. Get the new user_id by _/usr/bin/curl -s --netrc-file /etc/couchdb/couchdb.netrc '127.0.0.1:5984/identities/_all_docs?include_docs=true' | grep <the_username>_
and get the value from the key user_id in the output
3. Rename the old folder in /var/lib/pixelated/dispatcher/<the_username>/data to the one obtained in step 2. E.g.: _root@unstable1:~# mv 7412c2b915918687e5204d4e3743127c e4c32885c78db3019968c890751f71cb_
4. Run the script _migrate_data_from_dispatcher_to_multi_user_agent.sh_
5. Login with the old password and check all emails are available.

**Comment by cz8s** [comment]
what I did:

* create account loadtest41 on unstable.
* find the id: 
```
root@unstable1:/srv/leap/webapp# /usr/bin/curl -s --netrc-file /etc/couchdb/couchdb.netrc '127.0.0.1:5984/identities/_all_docs?include_do
cs=true' | grep loadtest41
{"id":"7d032c0f022bdfe2e82cf4444c70a78d","key":"7d032c0f022bdfe2e82cf4444c70a78d","value":{"rev":"1-9cf4cd5320e85561562c71cec55ea3fb"},"d
oc":{"_id":"7d032c0f022bdfe2e82cf4444c70a78d","_rev":"1-9cf4cd5320e85561562c71cec55ea3fb","user_id":"7d032c0f022bdfe2e82cf4444c48623a","a
ddress":"loadtest41@unstable.pixelated-project.org","destination":"loadtest41@unstable.pixelated-project.org","enabled":true,"type":"Iden
tity"}},
```
Its the user_id 7d032c0f022bdfe2e82cf4444c48623a

* rename the data folder of loadtest41 from old to new id:
```
root@unstable1:~# cd /var/lib/pixelated/dispatcher/loadtest41/
root@unstable1:/var/lib/pixelated/dispatcher/loadtest41# mv ccd92e552976e341f22b3ff6a6c5298e/ 7d032c0f022bdfe2e82cf4444c48623a
```

* migrate: ```sh /root/migrate_data_from_dispatcher_to_multi_user_agent.sh```
* login to user-agent and see emails

**Comment by cz8s** [comment]
The account seemed empty, but had lots of mails in trash. So it worked \o/
