### ISSUE TITLE
Copy smtp certificates to migrate emails users

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#672]
Discussion on https://github.com/pixelated/pixelated-user-agent/issues/661

**Comment by cz8s** [comment]
the old directory is 
```
var/lib/pixelated/.leap/881231257b1232fad7a6ed3af85f8f71/providers/wazokazi.is/keys/client/smtp.pem
```
the new is 
```
var/lib/pixelated/.leap/881231257b1232fad7a6ed3af85f8f71/providers/wazokazi.is/keys/client/smtp.pem
```

So basically it is enough to copy the directory ```881231257b1232fad7a6ed3af85f8f71/``` from the old to the new place. So its the same story as #671
