### ISSUE TITLE
Improve Readme for useragent

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#677]
Issues we found while onboarding zara:
- Make it easier for ppl to only get the useragent running
- The Readme lacks a section on how to upgrade after a git pull (./go setup ?)
- https://github.com/pixelated/pixelated-user-agent#option-1-pixelated-user-agent-without-leap-provider should get reorganized, the numbering is wrong

**Comment by thaissiqueira** [comment]
The readme was updated.
