### ISSUE TITLE
[bug] deploy version timestamp

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#678]
The timestamp should be dynamic in the sense that:
if it is 47 minutes ago now, in one minute it should read 48 minutes ago.

See screenshot

**Comment by mnandri** [comment]
<img width="239" alt="screen shot 2016-04-13 at 3 17 01 pm" src="https://cloud.githubusercontent.com/assets/2129786/14494591/e3c749b4-018b-11e6-94cc-a266fd755c83.png">

**Comment by mnandri** [comment]
this is already deployed... so either needs to be fixed or the feature be reverted!

**Comment by re-nobre** [comment]
Hey, @mnandri !

I was thinking about it and I have a suggestion/question. 
What do you think about to have the exactly UTC time (UTC: <yyyy-mm-dd hh:mm>) instead of have a dynamic time?

**Comment by varac** [comment]
+1 for absolute UTC time

**Comment by mnandri** [comment]
@re-nobre  @varac time since is better because:
1. the idea is to get a quick appreciation of when was it deployed/written... if you want exact/absolute time then you can still use the commit sha to get it, much like any other details such as the author, commit message and the diff.
2. absolute time is very long and is hard to read
3. utc time would require the user to compute their actual time... that would take more time than just looking at the commit itself.
