### ISSUE TITLE
[bug] duplicate emails

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#685]
If your email address is written twice, in the to/cc/bcc field then you will receive the email twice...

Both frontend and backend (controller +  email sender) filters for duplicates should be implemented.

**Comment by zaraG** [comment]
Do you think this "frontend-check" won't devalue the usability? We would say, don't care and just send the email ONES. =)

**Comment by zaraG** [comment]
Prio 1: BCC
Prio 2: TO
Prio 3: CC

**Comment by madziaf** [comment]
To QA, run the useragent locally. Write an email with recipient duplicated in fields  - meaning the same recipient twice in either or all of fields (To, Cc, Bcc) and observe, that the recipient received only one email and that priorities (most important Bcc, least - Cc) are followed. For example, if the recipient was put in To and Cc fields, she will receive the email only from To field.
