### ISSUE TITLE
[bug] soledad_invalid_auth_token, stops the server

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#686]
Whenever SOLEDAD_INVALID_AUTH_TOKEN event is emitted, we shutdown the reactor and stop the server (see [code here](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/application.py#L141))

we should instead, just logout the user who is broadcasting the event... so that not all the users are all logged out (just because one user has his soledad sync token expired).

**Comment by mnandri** [comment]
see sreenshot
<img width="1303" alt="screen shot 2016-05-11 at 9 49 51 am" src="https://cloud.githubusercontent.com/assets/2129786/15173684/c7cab042-175d-11e6-92ef-2643f13e7d2c.png">

**Comment by mnandri** [comment]
To QA:
you need to login...
wait for a couple of hours (till soledad token auth expires)
see that you are:
1. logged out
2. the log says that you had invalid soledad token and being logged out

Also, check that no other user have been logged out and the system not restarted (from systemd log)

**Comment by zaraG** [comment]
I am logged out, get an invalid token, **but** it seems to me, that an error happens before login out properly.

<img width="1642" alt="screen shot 2016-05-20 at 11 12 46" src="https://cloud.githubusercontent.com/assets/12573024/15423081/0754f72a-1e7c-11e6-9214-c99269b23ff7.png">

There are other users with an invalid token as well.

**Comment by zaraG** [comment]
I am logged out and the soledad process is finished. Great. :)
