### ISSUE TITLE
Useragent should log more without --debug flag

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#689]
Today @felixhammerl and me went crazy because without `--debug`, the useragent doesn't log anything. Watching the logs it looks like it's dead.

It should log at least when someone logs in and out and other useful information like sync status etc.

**Comment by varac** [comment]
see also #601

**Comment by cacarrara** [comment]
It would be good try to raise some initial enough data to be logged, so anyone who get this task can have a clearer vision and goal. For now the suggestions are:
* User login and logout
* Sync status (it shouldn't be logged by soledad?)

More?

**Comment by mnandri** [comment]
oops, made a mistake on the issue id...
the commit above is for #686

**Comment by thaissiqueira** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
