### ISSUE TITLE
[bug] logout button disappeared

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#692]
on wazokazi... no logout button (see screenshot below).

Please add/change a functional tests to assert it is there... ideally the functional tests in puppet (for live testing) as well

**Comment by mnandri** [comment]
![screen shot 2016-05-17 at 12 06 49 pm](https://cloud.githubusercontent.com/assets/2129786/15318748/e9bc4098-1c27-11e6-9a0c-809edb89e98f.png)

**Comment by deniscostadsc** [comment]
@SweetVirginia this is why I couldn't logout today.

**Comment by varac** [comment]
works!
