### ISSUE TITLE
Fix floating point exception and segfault errors on multicore servers on soledad sync [PR #309]

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#693]
We need to get to the bottom of why PR  [309](https://github.com/leapcode/soledad/pull/309) and [320](https://github.com/leapcode/soledad/pull/320) throws a SIGFPE on a fresh soledad synch on multicore servers.

source of the issue is detailed here:
https://github.com/pixelated/pixelated-user-agent/issues/683
https://github.com/pixelated/pixelated-user-agent/issues/690

This includes:
- unreverting the  reverted commits of PR 309
- provide a stable fix for the SIGFPE issue

**Comment by mnandri** [comment]
culprit could be:
sqlite, sqlcipher 
openssl

**Comment by varac** [comment]
Steps to reproduce:

- Merge [shybas bye-multiprocessing PR](https://github.com/leapcode/soledad/pull/309) locally and use it in your local useragent
- Run the (latest) useragent locally (if you have a multicore CPU) in multiuser mode
- connect to dev.pix. Login with multiple "loadtestXY" users in parallel and try to break it. We were able to produce FPE/segfaults with two accounts in parallel in a few minutes.

**Comment by varac** [comment]
@shyba: ping, just to let you know that we needed to revert your patches for now :(

**Comment by bwagnerr** [comment]
@varac @mnandri does this still make sense considering shyba's commit is not the source of the problem?

**Comment by mnandri** [comment]
see also https://github.com/pixelated/pixelated-user-agent/issues/683
