### ISSUE TITLE
count how many users are logged in

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#694]
Narrative
As a leap admin users, I would like to know the number of logged in users  so that I am able to infer system usage and load on the server

ACs:
* API provide a GET (xsrf-protected) access that gives number of logged in users
* Only leap admin users have access
* Non-leap admin gets a 403 (Forbidden), or 401 (Unauthorized)

**Comment by mnandri** [comment]
We are making a request to leap web app to expose over the api if the user is admin or not... 
This is blocked until that feature is available.

**Comment by bwagnerr** [comment]
Moved back to backlog because it's not part of the current goals

**Comment by re-nobre** [comment]
is this issue solution related with this discussion: https://github.com/pixelated/pixelated-user-agent/issues/601 ?

**Comment by deniscostadsc** [comment]
> is this issue solution related with this discussion: #601 ?

No. #601 is about put on the log the information about which user got the error.

**Comment by mnandri** [comment]
This is done. 
You should be able to see the number of users online at: https://provider:8080/users
Admin will get a number and non-admin will get a 401 (Unauthorized).

Note:
1. On local machine, you will need to re-install leap.auth in your virtualenv. It requires some changes that we pushed through there.
This is done automatically on package installs, that is no the servers... so not required.
2. This depends on the web_app PR https://github.com/leapcode/leap_web/pull/221
