### ISSUE TITLE
Show all recipients in mail sent folder

### ISSUE THREAD

**Issue by zaraG** [pixelated/pixelated-user-agent#695]
**Steps to reproduce the behavior:**
- send an email to at least two recipients in the bcc field
- go to the sent folder and check for the email you just send

**Expected behavior:**
- in the bcc list of the email you should be able to see all bcc recipients 

**Actual behavior:**
- bcc list just shows one bcc recipient

**Hint:**
Please have a look to the mail_sender and the mail_service.
The method _ _define_bcc_field()_ changes the bcc fileds while sending, for every bcc recipient, before moving the  the mail to the sent folder _move_to_sent()_.
Please be aware of just changeing that, because if an error happens while sending the user shouldn't find the email in the mail sent folder.

**Comment by re-nobre** [comment]
Hey, maybe the discussed on this closed issue can help understand the current behaviour: https://github.com/pixelated/pixelated-user-agent/issues/515

**Comment by zaraG** [comment]
@re-nobre yes that explains the actual behavior, for the the recipients it is working pretty fine, but the sender isn't able to see the list of bcc recipients was send to.

**Comment by cz8s** [comment]
the pr is still open. how should this be qa'ed?

**Comment by cz8s** [comment]
qa'ed on staging. works. looks cool
