### ISSUE TITLE
Generated OpenPGP keys should use SHA256 or SHA512 for cert-digest-algo

### ISSUE THREAD

**Issue by zariye** [pixelated/pixelated-user-agent#702]
https://leap.se/code/issues/7407

**Comment by zaraG** [comment]
[PR](https://github.com/leapcode/python_gnupg-ng/pull/5)

**Comment by zaraG** [comment]
The new [PR](https://github.com/isislovecruft/python-gnupg/pull/149) to the origin library [python_gnupg](https://github.com/isislovecruft/python-gnupg/).

**Comment by zaraG** [comment]
**Update for the standup** as you know we discussed last week that the ownership of the gnupg libary might change, or LEAP will create a copy (I know there is already a copy, but it is not really in development state as well..no tests and so on) to use...for now I guess this PR is in hold?

**Comment by zariye** [comment]
merged for 2.1.0.
