### ISSUE TITLE
Check validity of key signature

### ISSUE THREAD

**Issue by zariye** [pixelated/pixelated-user-agent#703]
https://leap.se/code/issues/8112

**Comment by zaraG** [comment]
GNUPGP Repo
[ISIS PR](https://github.com/isislovecruft/python-gnupg/pull/150)
[LEAP PR](https://github.com/leapcode/python_gnupg-ng/pull/6)

KEYMANAGER
Next step is going to be to filter the the new key which is signed by the same persons old key (compare with fingerprint).

**Comment by zaraG** [comment]
[LEAP Keymanager](https://github.com/leapcode/keymanager/pull/114)

**Comment by zaraG** [comment]
**Update for the standup** same then https://github.com/pixelated/pixelated-user-agent/issues/702

**Comment by zariye** [comment]
merged for 2.1.0.
