### ISSUE TITLE
user-agent fails if user-database missing

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#704]
When running the functional tests, we delete the user-database when we have finished to save space.
When the user-agent logs in again, leap.mail tries to access the deleted db and crashes.
But soledad recreates that db in the same session.
This is the error:

```
unstable1 pixelated-user-agent[21324]: 2016-06-01 18:31:58 [leap.mail.mail] ERROR BUG: (please report) Null doc_id 
for document {'fdoc': 'F-e1d384f2_2181_4ea5_9506_6b5d083e26de-16FF67455C89F5724D92190CF117D08C9CD769265DF1D322E0D04C6C995A2699', 'type': 'meta', 'hd
oc': 'H-16FF67455C89F5724D92190CF117D08C9CD769265DF1D322E0D04C6C995A2699', 'cdocs': ['C-45D7B60AE57A4C23E0F7636976AB1A53056F843C723AB96582D0E3E86BC0
E09A']}
```

But after the first sync everything works again.
Is there a way to only start leap.mail after the first soledad sync? Or am I totally wrong?

Ways to reproduce:
Run the functional tests by hand:

```
INVITE_CODE_ENABLED=true  /usr/local/bin/behave --tags @staging --tags ~@wip -k /srv/leap/tests_custom/functional-tests/
```

Then the user behave-testuser should exist, but the database should not exist.
If you then login as behave-testuser, it should fail first,
but the second login should succeed.

**Comment by bwagnerr** [comment]
@cz8s We currently only start leap mail after the first soledad sync, so this should be true already

**Comment by deniscostadsc** [comment]
Closing this issue. The problem seem solved since we don't see this problem for a while.
