### ISSUE TITLE
JSON exception during login

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-user-agent#707]
![screen shot 2016-06-07 at 10 43 04 am](https://cloud.githubusercontent.com/assets/1818340/15859002/7eb96e86-2cc3-11e6-9036-cdcab0dbfa41.png)

This happened randomly during login, fixed itself later...

**Comment by felixhammerl** [comment]
single event, closing for now

**Comment by zaraG** [comment]
Actually I don't think that it is a single event. It happend a couple of times to me, but after reloading the page everything was fine.
