### ISSUE TITLE
Send email about splitting soledad sync storage

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#708]
Start a discussion with leap about a split of sync and storage on Soledad.

**Comment by bwagnerr** [comment]
Let's write the mail here:
https://pad.riseup.net/p/soledad-split

**Comment by bwagnerr** [comment]
@all can you review this? I would like to have everyone on the same page before sending this

**Comment by zaraG** [comment]
I am ok with it, or even more. I like the idea!

I just wonder if it is something Pix people are going to do, or LEAP or will we pair on that? Because it looks like a lot of effort to spend in.

**Comment by mnandri** [comment]
added some notes

**Comment by deniscostadsc** [comment]
It's ok!

**Comment by bwagnerr** [comment]
@zaraG @mnandri  That is something that greatly benefits Pixelated, but doesn't impact Leap, so would be done by us, step by step (there are small enough steps to do little by little)

**Comment by cz8s** [comment]
mail was sent
