### ISSUE TITLE
Prepare Hacknight in SP

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#709]
We need to start organize some Pizzelated (hacknihgt)

- [x] Get a place (probably on Garoa Hacker Clube)
- [x] Set a date (probably on 28/06/16)
- [x] Do marketing about it
- [x] Invite organizations

**Comment by thaissiqueira** [comment]
I sent email to Luciano Ramalho to confirm the date.
Now I'm waiting to confirmation.

**Comment by re-nobre** [comment]
hey, @thaissiqueira, @deniscostadsc, @bwagnerr, @SweetVirginia , @tuliocasagrande, @cacarrara 
The last times that we did the hacknight in Brazil we just did a hacknight for code. 
I was talking with the team in Hamburg and I think can be interest we have the something more like they are doing here. They split the people in groups and there are groups that only talk about things. 
Please, take a look on the meetup description: http://www.meetup.com/pt-BR/ThoughtWorks-Hamburg/events/231933541/ 

As we have space in Garoa, I think can be a good ideia.
What do you think?

**Comment by thaissiqueira** [comment]
Event scheduled on [Garoa's](https://garoa.net.br/wiki/P%C3%A1gina_principal) calendar.

**Comment by re-nobre** [comment]
hey, @thaissiqueira !
Awesome!
But I think the date is wrong, for me it's appear as 5 June: https://garoa.net.br/wiki/Categoria:Eventos

**Comment by thaissiqueira** [comment]
@re-nobre,

Sounds good. Maybe we can just change to subjects more related with brazilians reality. Even because this event will be useful as a showcase for some organizations like Garoa and MariaLab.

What do you think?

**Comment by thaissiqueira** [comment]
@re-nobre 

> But I think the date is wrong, for me it's appear as 5 June: https://garoa.net.br/wiki/Categoria:Eventos

It's right because already exist an event scheduled to 28/6. 
So we change to 5/7.

**Comment by re-nobre** [comment]
Yeah, @thaissiqueira ! 
This is what I thought. 
I liked the format and I think we can change the subject the way we think is the best.
Do you think about any specific subject?

About the dates, ok, I will change on the post that I'm writing then!

It will be awesome! \o/

**Comment by thaissiqueira** [comment]
Hello team,

Here is the pad with description for the meetup schedule: https://pad.riseup.net/p/hacknight-garoa
Can you help me on pt the revision and about the topics suggestions for talks?

**Comment by deniscostadsc** [comment]
@thaissiqueira 

I wrote a comment there.

**Comment by thaissiqueira** [comment]
Created event on TW's Meetup organization: http://www.meetup.com/conexaotwsp/events/232056198/

**Comment by thaissiqueira** [comment]
Tweeted: https://twitter.com/pixelatedteam/status/745351609467736068

**Comment by thaissiqueira** [comment]
Please, re-tweet it 👆 😉

**Comment by re-nobre** [comment]
checklist on the wiki: https://github.com/pixelated/project-issues/wiki/Hacknight-Checklist

**Comment by thaissiqueira** [comment]
# Hacknight Review

## What need to be better
- We can prepare ourselves better to present, planning who will present what;
- Ask about food restriction (maybe on invite for hacknight);
- Ask for who will eat before do the order;
- The instructions was not clear;
- Think about how to run pixelated-user-agent on Windows;
- Prepare t-shits, banner and stickers if we are planning to take it.

## What was good
- Ask for who want to code and who want to talk about Pixelated subjects relatives;
- Made a Pixelated vagrant box and share it using a flash drive; 

## Insights
- Maintain a Pixelated vagrant box published using pipeline generate and validate it;
- Run pixelated-user-agant locally without vagrant box;
- Make pixelated-user-agent usable with docker;

## Problems
- We had problem to provisioning the vagrant of pixelated-user-agent and it disturb the progress of work.
We are trying to solve it yet.

## Time to prepare
- We calculated that we used a amount of 24 hours to prepare this hacknight.

**Comment by mnandri** [comment]
@thaissiqueira  do you have a record of the logs during `vagrant up`  or a screenshot you can provide?
