### ISSUE TITLE
[bug] feedback icon not showing on wazo

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#710]
Did we disable this?
or we broke compatiliby

**Comment by re-nobre** [comment]
I saw that there is a nav tag for it on the code, but it's empty

<img width="358" alt="screen shot 2016-06-13 at 1 55 35 pm" src="https://cloud.githubusercontent.com/assets/2657059/16006679/a5ff81e2-316e-11e6-80de-858aa192687d.png">

**Comment by mnandri** [comment]
just needed to add the following line in /etc/default/pixelated-server

` FEEDBACK_URL=https://pixelated.wazokazi.is/tickets`

**Comment by mnandri** [comment]
we could add that in [puppet-pixelated](https://github.com/pixelated/puppet-pixelated/blob/master/templates/pixelated-server-default)  and make it conditional in such a way that leap deploy will know what to do... but then it is inherently a property of the server, where the feedback url itself may not have a pattern...
what do you think @cz8s

**Comment by mnandri** [comment]
We adopted the following approach:
1. add empty FEEDBACK_URL env variable in the default pixelated-server config template... so that people are reminded that it can be set if desired
2. Empty FEEDBACK_URL does not enable the feedback feature. It has to be non-empty for it to be enabled, and the actual url is at the discretion of the configurer.

related commit in puppet-pixelated
https://github.com/pixelated/puppet-pixelated/commit/8b8d1670ca58978c965653a9903d45ae842d9dc0

**Comment by mnandri** [comment]
To QA:
1. deploy
2. verify `FEEDBACK_URL=` in /etc/default/pixelated-server
3. verify feedback icon is not available
4. change `FEEDBACK_URL=https://some.url.that.accepts/tickets`
5. verify feedback icon is available and feedback can be submitted
6. check in the webapp system that the ticket is actually there.
