### ISSUE TITLE
Encrypted vs. Unencrypted

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#711]
Encrypted vs. Unencrypted: not clear enough. 
(also sending one message both encrypted and unencrypted, with no warnings is a security risk .)

I was thinking....
Pixelated is an email client that happens to sign and encrypt some emails by default, but it does not do that to most messages off provider (assuming most people exchange emails with people with no keys at all). Maybe the post card metaphor can be more useful here.
Currently most people send post cards by default and only a few have access to letters because encryption is hard, right?
So why in Pixelated normal emails people are used to send (post cards) are always yellow, as if something is wrong? Why won't Pixelated alerts only when communication is secure (letter) - following http vs. https patterns - and show encryption as a positive reinforcement?  

I mean, assuming the user is never wrong. If Pixelated needs to create awareness over encryption for people who don't know and/or don't understand it, wouldn't a more positive approach be a better solution?   

I'll come with some prototyped suggestions to test with people later.

**Comment by SweetVirginia** [comment]
https://github.com/pixelated/pixelated-user-agent/issues/388

**Comment by olabini** [comment]
Hi,

I'm not a huge fan of this approach, and the analogy with http/https is actually false. All major browsers are in the process of moving to warning for http and not saying much about https. The goal is to normalize security as much as possible. A lot of research has shown that the approach of showing something special for https but showing nothing for http gives the wrong incentives to users such that they make bad decisions.

I do agree that it is a problem that most of all emails will be marked as unsafe in some way or another - but that's also a way we can drive change, hopefully.

**Comment by zaraG** [comment]
Hi @olabini,

by side the comparison might be wrong. Do you think we shouldn't add a warning if a email will be send unencrypted? The user feedback we got is that it is confusing (or not clear enough) if a user sends a email to a couple of people and some will be unencrypted. Currently the only way to see that (as a user) is the small open lock icon (in yellow).
 
That might be not enough, for ppl who don't know the product or the way how encryption works in general.

**Comment by olabini** [comment]
So maybe we are talking about different things here. I thought Virginia was proposing removing warnings for ALL unencrypted/unsigned emails, and add notifications when encryption/signing was present. That's what I'm arguing against.

Warning (or even stopping) a user when sending mixed content is something I think is absolutely crucial. It's a terrible security risk to have it as it is now.

**Comment by SweetVirginia** [comment]
@olabini: We are talking about two different things. Sorry if that was confusing. 
First of all, I am not proposing removing all unencrypted/unsigned emails, and add notifications.  
And "Warning (or even stopping) a user when sending mixed content is something I think is absolutely crucial."  yes, indeed. 👍 

Nevertheless, if Pixelated's user is an average, non-target, non-technical person who has no idea what a signature and/or a gpg key is, getting an orange padlock punishes the user for no reason, because as far as I understand, there's nothing he or she can actively do to change the padlock to green without further knowledge, the message sounds like "you are wrong and there's nothing you can do about it" (the worst part is that now there is no message at all and that's why I mentioned issue #388). And also, always displaying alert-orange for normal actions takes off all it's alert connotation and normalizes unsafe behaviour. 
 
So the "false" analogy I was proposing, was to understand Chrome's pattern and maybe do something like it for "safe/not that safe/not safe at all/don't send this message": 
![chrome_padlocks](https://cloud.githubusercontent.com/assets/6019419/16045798/7352fec4-3220-11e6-8805-9aa96e7d0a26.png)


PS: if you can share it with me those studies you mentioned, it would be great 😄

**Comment by olabini** [comment]
Hi,

So actually, Chrome's current behavior is what they are moving away from. They will move towards a model where you get a broken lock for ALL sites that are not using https. It turns out that the green padlock is not strong enough for positive reinforcement, and since  most sites are not https, most of the time there is nothing there. Only positive reinforcement with a green padlock for https has been shown to not be enough to have users make good calls. I'll try to dig up the studies.

I agree that giving people a warning for things they have no agency to change is not a good idea. But actually, they _can_ do something - which is to recommend their friends to start using encrypted and signed email. Writing/read unencrypted/unsigned emails should NOT be the normal action. Even if it's the more common action, part of educating users to use more encryption is to normalize encryption, and "denormalize" plaintext.

The problem is to test these approaches, and what measures to use to compare them. I honestly don't know what the right parameters are.

Maybe it's possible to go away from the whole green/red/orange thing (which btw is very problematic for red-green color blind people) and try to think about something else. Can we change the background image of the compose thing to indicate a post card when unencrypted, and a sealed letter for encrypted/signed? Or some other way that doesn't scream WRONG or RIGHT for the different actions?

**Comment by SweetVirginia** [comment]
I agree with you. I'm not saying that a green padlock is a solution, it's just an example to say that right actions deserve more attention than the wrong ones, about **how** to do that is a different discussion.  😉 

About  _"they can do something - which is to recommend their friends to start using encrypted and signed email."_ -> No, actually they don't because, again, they don't know how to do it. They can invite their contacts to use Pixelated and that's it.  

_"Writing/read unencrypted/unsigned emails should NOT be the normal action"_ -> Yes, perfect! 
The problem is that you can't ask someone to get off a gmail-like-experience to an email client that says most of the messages sent are unsafe, even though that's true, in comparison to most email clients Pixelated would give the impression that it is much more unsafe than Gmail. That's something to be careful about, but maybe is easy to be tested: we can ask users questions like how much they would trust Pixelated, etc.  :)

I think that the best way to measure this different approaches are qualitative researches, talking to people, asking open questions where they can say their impressions, their trust levels, opinions and watch them try these approaches (that we haven't designed yet) to observe if their behavior is coherent with what they say. I have to research if there's any other way to measure this, validade and get insights, but I believe talking to people should be enough.

_"Maybe it's possible to go away from the whole green/red/orange thing (which btw is very problematic for red-green color blind people) and try to think about something else."_  -> Totally agree. Thanks for the suggestions. I'll try to prototype some and we can discuss more and better with some ideas on the table 💃 

Thanks again 😄 


I've found this on Chrome Usable Security Team, doesn't say much, but is helpful: https://docs.google.com/presentation/d/1Qmpl-5epx0B5C2t4XsUTyjgbwab_rXfK_4iHqX3IC30/pub?start=false&loop=false&delayms=3000&slide=id.gf44795496_0_125

**Comment by olabini** [comment]
Sounds good. When it comes to talking to people - you are right it's definitely possible to test many of these things. But you can't test it against an evaluation of the security of their actions, since the users can't judge that in most cases.

**Comment by SweetVirginia** [comment]
This issue has some ideas -> https://github.com/pixelated/pixelated-user-agent/issues/758
