### ISSUE TITLE
Icons, let's try some new ones.

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#712]
- [ ] Settings Icon is not clear. 
- [ ] Padlock icons on recipients needs to be larger. 
- [ ] Hamburger icon too small
- [ ] Paper airplane is not appropriate as “sent” icon. “The icon for seeing the SENT e-mails was confusing to him, for he was writing an e-mail and thinking that the button was for sending the e-mail.

**Comment by re-nobre** [comment]
Hey, @SweetVirginia!
I was thinking that maybe is better have one issue for each improvement, this way we can have small issues for be done on hacknights.
What do you think?

**Comment by thaissiqueira** [comment]
This issue was splitted in: 
#717
#716 
#715
