### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#714]
- [ ] Move time and date closer at the inbox list.
- [x] Make list of messages easier to scan: alternate shadings for every other message
- [x] Review white texts and darken background colours. 
- [x] Page number and arrows are actionable, but don’t look like they are. 
- [ ] Display the sender’s name so is easy to scan and determine who you are talking to.

**Comment by re-nobre** [comment]
@SweetVirginia mapped all the UI Tweaks [here] (https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

We will analyse better all these points and we will create github issues when we decide work on it. So, I'm close this issue for now. 
:)
