### ISSUE TITLE
Hamburger icon too small

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#715]
Users are having problems understanding some of the icons at Pixelated's interface. 

Hamburger Menu Icon is too small and doesn't look clickable. It needs to be bigger, the same size as other icons on the left column. 

![screen shot 2016-06-15 at 4](https://cloud.githubusercontent.com/assets/13627260/16094160/4f0e59a0-3315-11e6-8ea7-3f507d7910a8.png)

**Comment by cacarrara** [comment]
I think it's duplicated. We already have a issue related: https://github.com/pixelated/pixelated-user-agent/issues/712

**Comment by thaissiqueira** [comment]
It's because we are splitting it ;)
After this the other one will be deleted.

**Comment by SweetVirginia** [comment]
This an UI Tweak. Recently some usability tests and analysis were done by Pixelated members and supporters, one of the things people reported the menu behaved unexpectedly. For now, the suggestion it's just to make it bigger, but it would be nice if it disappears when the menu is open like other apps do :)  
 
_______
<img width="383" alt="screen shot 2016-06-17 at 6 05 41 pm" src="https://cloud.githubusercontent.com/assets/6019419/16164719/23ca8938-34b6-11e6-8924-2ea3a42923d4.png">
________

<img width="421" alt="screen shot 2016-06-17 at 6 13 43 pm" src="https://cloud.githubusercontent.com/assets/6019419/16164925/49641942-34b7-11e6-9e16-99fb6f43e8ce.png">
