### ISSUE TITLE
Padlock icons on recipients needs to be larger

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#716]
Users are having problems understanding some of the icons at Pixelated's interface. 

About padlock icons, people with poor eyesight had some difficult identifying the open padlock and the closed padlock at the recipient's field.

<img width="467" alt="screen shot 2016-06-15 at 4 04 55 pm" src="https://cloud.githubusercontent.com/assets/13627260/16095627/dbffe404-331b-11e6-8820-f910121ed9d1.png">

We just need to make these icons a little larger.

**Comment by SweetVirginia** [comment]
Actually I've found this open lock icon (http://fontawesome.io/icon/unlock/) which has a much different shape compared to the closed lock and I think it will be easier for people see the difference. 

I used a 20px font-size at my mockup, but please, be aware and observe the icon's proportion 👊 

<img width="516" alt="screen shot 2016-06-17 at 6 46 26 pm" src="https://cloud.githubusercontent.com/assets/6019419/16165690/d38b08c0-34bb-11e6-8b86-763bfb9c8d8a.png">

**Comment by deniscostadsc** [comment]
Much better!

**Comment by tayanefernandes** [comment]
@SweetVirginia 
We increased the icon size a little bit.
Not exactly 20px, but 1.2em, because it's a relative size unit. What do you think?

![screen shot 2016-09-29 at 6 15 12 pm](https://cloud.githubusercontent.com/assets/10910322/18972734/b9452db8-8670-11e6-86f7-e88a2463b689.png)

![screen shot 2016-09-29 at 6 10 21 pm](https://cloud.githubusercontent.com/assets/10910322/18972562/0c7bef68-8670-11e6-868b-12662fa8aba7.png)

**Comment by thaissiqueira** [comment]
Comparing the current version (left) and the mockup version (right) - as is showed on the image above - I think that we can increase and centralize a little more the current padlock.

![padlock](https://cloud.githubusercontent.com/assets/13627260/19008127/7c3d1ec4-873f-11e6-95e1-3132543f4c8b.png)

What do you think @SweetVirginia? Or is enough?

**Comment by SweetVirginia** [comment]
I agree @thaissiqueira, doesn't have to be exactly like the mockup but it could be a little bit larger. Is it possible to align the padlock base line to the type?

**Comment by tayanefernandes** [comment]
<img width="369" alt="screen shot 2016-11-10 at 5 42 15 pm" src="https://cloud.githubusercontent.com/assets/10910322/20191543/18385ff8-a76d-11e6-8697-8f6a48170c3c.png">
