### ISSUE TITLE
Paper airplane is not appropriate as “sent” icon

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#717]
Users are having problems understanding some of the icons at Pixelated's interface. 

About Paper Airplaine Icon, people are getting confused because the paper airplaine is more related to the action of sending emails and not sent emails.

![sent-icon](https://cloud.githubusercontent.com/assets/13627260/16094542/0e1ad5f2-3317-11e6-8072-4b6b26a43aaa.png)

The new icon for the outbox is this: [fa-sent.svg.zip](https://github.com/pixelated/pixelated-user-agent/files/317100/fa-sent.svg.zip)
We just need to switch these icons.

**Comment by SweetVirginia** [comment]
<img width="394" alt="screen shot 2016-06-17 at 6 22 26 pm" src="https://cloud.githubusercontent.com/assets/6019419/16165114/794fa7f6-34b8-11e6-907c-f47d2836552a.png">
