### ISSUE TITLE
Search bar should accept non alphanumeric chars

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#719]
## What
I tried to make a search for the standart: "from:" and I got this message: 
_"Please match the request format"_
Then I also trie to search for a specific email: "renata@wazokazi" and I got the same message.

Then @felixhammerl and I went to the code and saw that it's happing because of this change:
web-ui/app/templates/search/search_trigger.hbs

## Definition of done
The search bar should accept non alphanumeric chars

**Comment by bwagnerr** [comment]
We should just revert 2b41494b and d2d6fb98 that introduce this search restriction.

**Comment by bwagnerr** [comment]
I moved this to ready, because this is just reverting two commits (no real coding) and this is essential to the usability of Pixelated
