### ISSUE TITLE
Lack of contrast between white text and blue background

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#721]
Recently some usability tests and analysis were done by Pixelated members and supporters, one of the feedbacks people reported is the lack of contrast between the white text and blue background, this makes the tags hard to read and it's specially problematic for people with poor eyesight. 

Suggestion: change tag's background color to **#218CA4**

________________________
Old color: #6cbfd2    

<img width="214" alt="screen shot 2016-06-17 at 4 31 08 pm" src="https://cloud.githubusercontent.com/assets/6019419/16162317/f92e2d0e-34a8-11e6-9470-be87a69ad611.png">
________________________
New Color: #218CA4

<img width="491" alt="screen shot 2016-06-17 at 4 27 40 pm" src="https://cloud.githubusercontent.com/assets/6019419/16162220/7e0b369e-34a8-11e6-9dbd-bf9d65eec0b9.png">

**Comment by tayanefernandes** [comment]
@SweetVirginia It's not exactly the color you suggested, but it is the #178CA6
What do you think?

![screen shot 2016-09-28 at 6 03 15 pm](https://cloud.githubusercontent.com/assets/10910322/18932242/de5a6e90-85a5-11e6-8ee6-778fb5787b92.png)

**Comment by varac** [comment]
looks much better !
