### ISSUE TITLE
Make list of messages easier to scan

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#722]
Recently some usability tests and analysis were done by Pixelated members and supporters, usability experts advised us to make list of messages easier to scan by alternating shadings for every other message. 

---

Suggestion:
Alternate between #E0E0E0 and #EDEDED: 

<img width="459" alt="screen shot 2016-06-17 at 5 43 23 pm" src="https://cloud.githubusercontent.com/assets/6019419/16164068/096aa116-34b3-11e6-82fd-fe123b8c8b8a.png">

**Comment by re-nobre** [comment]
Hey, @SweetVirginia!

Today, the background color and the bold text are the difference between an no read email and a read one.

What do you suggest that we can do to make this difference?

**Comment by SweetVirginia** [comment]
I don't think I understood your question. The alternate shading is to make the read ones easier to scan. The new messages won't be changed (still bold with white background).

**Comment by re-nobre** [comment]
Hey, @SweetVirginia!

Actually, I noticed that for now only thing that change for a new email is the bold text.
<img width="873" alt="screen shot 2016-06-21 at 12 08 48 pm" src="https://cloud.githubusercontent.com/assets/2657059/16225874/210e41c6-37a9-11e6-9203-42d5ce5b01f7.png">


Just to clarify, the idea is maintain this behaviour with this issue, right?

**Comment by SweetVirginia** [comment]
Yes, just like this:

<img width="287" alt="screen shot 2016-06-23 at 11 26 41 am" src="https://cloud.githubusercontent.com/assets/6019419/16307123/7e6d763c-3936-11e6-969f-127c1f149c77.png">

What do you think?

**Comment by SweetVirginia** [comment]
Yes, @tayanefernandes 🙂 But I guess with no one line preview yet.

**Comment by tayanefernandes** [comment]
This the result: 
@SweetVirginia please take a look! 🙂
<img width="513" alt="screen shot 2016-11-23 at 6 21 26 pm" src="https://cloud.githubusercontent.com/assets/10910322/20577483/b0cc6ae8-b1a9-11e6-9bc6-5dc505135633.png">

**Comment by SweetVirginia** [comment]
In my opinion, It's much better this way :) Great work, @tayanefernandes  :D
