### ISSUE TITLE
Setup a translating tool

### ISSUE THREAD

**Issue by cacarrara** [pixelated/pixelated-user-agent#727]
The first try will be use Transifex as the translating tool. It's free for open source projects and sort of a common tool used by other projects.

- [x] Create Transifex organization
- [x] Create Transifex project (open source, free)
- [x] Set Transifex config on project
- [x] Update CONTRIBUTING.md
- [x] Create translators instructions and link to Transifex project
- [x] Invite team administrators

**Comment by cacarrara** [comment]
Transifex has already support for the same file format that we're using at User Agent: http://docs.transifex.com/formats/json/

**Comment by cacarrara** [comment]
I've created a project and an organization for Pixelated at Transifex: https://www.transifex.com/pixelated/pixelated-user-agent

**Comment by zaraG** [comment]
What is about [i18](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/js/views/i18n.js)? It looks like it is already in use as well.

http://i18next.com/

**Comment by cacarrara** [comment]
@zaraG we're going keep using i18next internally in Pixelated to do all the work necessary to internacionalize our interface. The Transifex work is going to be exclusively related to manage the translation files that i18next uses. So, for a contributor who haven't experience with git, github and all those "dev" things, a translation contribution is just a matter of getting an Transifex account (most of them already use it) and do all the contributions by there.

**Comment by zaraG** [comment]
@cacarrara thank you for the explanation, I just understood it yesterday in the meeting. :)

**Comment by cacarrara** [comment]
@cz8s, do you have any experience automating the process to update Transifex translations? An account is required to use Transifex Client. So should we create an account for all project/team and do some script to run during the build? Other projects I've saw seems have a manual process for it.

**Comment by cz8s** [comment]
there is txgh: http://docs.transifex.com/integrations/github/
that sounds like we have to run yet another service to connect
github<->transifex ...
Since we already run so many services, I don't really like this aproach.

**Comment by cacarrara** [comment]
Well, I'm facing an issue now. i18next uses language code with _dashes_ `en-US` and Transifex uses it with _underscore_ `en_US`. This incompatibility makes i18next unable to found the translation files. Im trying to see how to address it.

@tuliocasagrande and @bwagnerr are aware about it.

**Comment by cacarrara** [comment]
For now, the updating process wasn't implemented. I think this task is a first step and has enough work to be validated. We can create a new task to automate the translation update process.

**Comment by zaraG** [comment]
@cacarrara after the automation is done, should be tweet about it?

**Comment by rhatahet** [comment]
Hi @cacarrara,
I've made a language request for French on transifex.com/pixelated/ (was quite easy to get to that point, thanks for the contribution guide, it's very clear).
What is the process from now? Do I need to wait for you to create the language file, and then I can join the Transifex team for the French language?
Thanks for your help.
Cheers,
Racha

**Comment by tuliocasagrande** [comment]
Hello @rhatahet,
We added the fr_FR language. 🎉 
I think you can request to join now.

Let me know if you encounter any problems.

**Comment by tuliocasagrande** [comment]
We moved the instructions to manage the translations to a specific page on wiki: https://github.com/pixelated/pixelated-user-agent/wiki/Managing-translations
