### ISSUE TITLE
Backend/Frontend packaging

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#728]
This is a dummy card to follow up on this PR
https://github.com/pixelated/pixelated-user-agent/pull/664

please add your comments/concerns/suggestions in the PR itself

**Comment by cacarrara** [comment]
Hmm, now we have 3 things to track, the PR itself, this issue and that other one: https://github.com/pixelated/pixelated-user-agent/issues/642.

We should keep only one.

**Comment by mnandri** [comment]
oh sorry I did not see that one... I'm closing this.
