### ISSUE TITLE
Use single setup.py

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#729]
We should merge the pixelated_www package setup to our existing setup.

Done will be:
- Setup.py, Makefile and et al... in web-ui is incorporated in the current setup.py in service
- and those (in web-ui) should be removed.
- possibly rename pixelated_www if desired

**Comment by mnandri** [comment]
First/quick investigation  tells me that this is an anti-pattern.
Because if we combine our normal user-agent package and this pix_www package to use the same setup.py then either package will get unnecessary data from either side... Why would  user-agent  package get sandbox.html? conversely, why would pix_www get pixelated.adapter.listeners

**Comment by re-nobre** [comment]
As @mnandri commented it's an anti-pattern and we won't do it.
