### ISSUE TITLE
Feedbacks field shouldn't delete the content

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#733]
## What
As a user,
I would like that the content on the feedback field to not disappear, when I navigate away.
So that I can explore more the product and able to incrementally input my feedback.

## Acceptance criteria
Given that the user is on the feedback field, writing his/her feedback
When he/she clicks away, to explore more the product 
And then clicks back the feedback icon
Then what the user wrote before in the feedback field should still be there.

**Comment by cz8s** [comment]
looks good and works as expected
