### ISSUE TITLE
Start the user-agent in watch mode

### ISSUE THREAD

**Issue by pameck** [pixelated/pixelated-user-agent#735]
When making changes to stylesheets, markup or templates, I have to manually rebuild the ui with: 
`./go build` or `npm run build`

I would like to be able to run the user-agent in watch mode so the ui gets automatically built.

One option could be just adding a watch flag, like this: 
`pixelated-user-agent --host 0.0.0.0 --watch`

**Comment by bwagnerr** [comment]
Hey, I know it is not exactly what you were looking for, but on the web-ui folder you can run "./go watch" to have everything be rebuilt automatically.

You still would have to run two things though (the user agent and the watch)

**Comment by olabini** [comment]
It seems like adding a watch command to pixelated-user-agent is not the right thing to do. That would introduce development concerns into the end product.
From my perspective, running "go watch" and the user agent somewhere else is more than enough to solve this issue.

**Comment by olabini** [comment]
This is duplicated in #611.
