### ISSUE TITLE
[bug] sandbox assets throws 404

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#738]
On Firefox, when it is set to not accept thrid-party cookies. The user agent cannot display the email body, that is normally sandboxed in an iframe.

The problem is that Firefox no third-party cookies policy is very strict. In that, the sandbox assets (sandbox.css and sandbox.min.js) request will not carry the origin's cookies and therefore will be seen as "not logged in" from the server side. Then, it will get a 404 as static assets, and any resources for that matter, are not available if the use is "not logged in".

This does not happen in Chrome or Safari... as cookies from the same origin (even on ajax, or iframe) are shared.

**Comment by mnandri** [comment]
Possible solution:
* find a way to make the iframe use the cookies of parent document
* or relax server policy on sandbox static assets
Or something in between, that enhances security of the overall user-agent (api + frontend).

**Comment by cz8s** [comment]
works. But this is not covered with tests. Is that intentional?
