### ISSUE TITLE
Change Open Padlock icon  

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#742]
In this issue's user feedback: https://github.com/pixelated/pixelated-user-agent/issues/716  we suggest an icon change. To keep consistency, lets change the open padlock icon (http://fontawesome.io/icon/unlock/)  in the header box as well. 

<img width="590" alt="screen shot 2016-07-05 at 12 17 04 pm" src="https://cloud.githubusercontent.com/assets/6019419/16589644/70a8bb60-42aa-11e6-8a29-18a2e9cda70c.png">

**Comment by felixhammerl** [comment]
fixed by https://github.com/pixelated/pixelated-user-agent/commit/8897c7b203aaaa4ae7cc175c61b7105ebc7488ac
