### ISSUE TITLE
ua unit-tests fail

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#752]
the unit tests fail.
The last commits are from me, but I don't know why they interfere with the unit-tests...

**Comment by cz8s** [comment]
https://snap-ci.com/pixelated/pixelated-user-agent/branch/master

**Comment by mnandri** [comment]
leap.mail still using u1db instead of l2db was the culprit... 
see https://github.com/leapcode/leap_mail/pull/247

It should be fixed when that PR is merge.
For now I have paused the gocd pipeline to not generate new jessie packages... it will break wazokazi otherwise.
