### ISSUE TITLE
some browsers can not validate cert

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#757]
the user-agent does not send the intermediate certificates
to the browser. this might result in a invalid cert if the browser does  not know the letsencrypt ca.
This will only happen on :8080

We should send the intermediate cert as we do in apache (the webapp).

dod: browsers (esp. android browsers) don't complain if they access https://try.pixelated-project.org:8080

**Comment by zaraG** [comment]
it might be that this ticket really stops users from testing the web app, just got the feedback again..

**Comment by anikarni** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
