### ISSUE TITLE
New approach for signatures and encryption

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#760]
> "While using Pixelated, I expect it to handle automatically this privacy/security features it says it has so I don't bother with tech complicated stuff"

_The bold suggestion:_

What if  we try to make Pixelated show only 2 states? Secure and Insecure. 
Those states may depend on previous behaviours, mimicking the same mindset security aware people have when analysing their emails.

Assuming the discussion we had earlier in https://github.com/pixelated/pixelated-user-agent/issues/758 Issue: 

What’s the best UI strategy? What to show or not to show the user?
- [x]  Design User Flows. 
- [x]  Rough pen and pencil prototyping.
- [ ]  Discuss with the team and star think about how to develop it.

_Concerns:_

What will be the instructions for them in case there’s something wrong?(What can possibly go wrong?)
Expired/Revoked keys, how to show?
How will public keys be found by people outside their provider? Can we do it manually if that’s the case?
Encrypted and signed behaviour changes, should we alert?

**Comment by SweetVirginia** [comment]
I put this issue on hold because we have some higher priorities with  organizations this week. I'll be back here with more time. 
Since discuss with the team is in this issue, and now we are discussing lost passwords, I think is better to wait that other issue to resolve too.

**Comment by re-nobre** [comment]
I talked with @SweetVirginia  and we will analyse all the UX proposals in a different place and create the issues when we will work on it. 

For all the UX/UI proposals and feedbacks, take a look [here] (https://docs.google.com/a/thoughtworks.com/document/d/19cBhvyfdmLY7iQ6ktRYGG6LaqYBa447Z_eg8_f1bfKw/edit?usp=sharing)

I'm closing this issue now.
