### ISSUE TITLE
Move combined_ca_bundle to UA bootstrap

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#765]
Currently, on login in [sessions.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/config/sessions.py#L52), the keymanager [instantiation ](https://github.com/pixelated/keymanager/blob/develop/src/leap/keymanager/__init__.py#L128)combines certificates into one file. This is done for each user, although it is the same certificates for all of them.
This process should be moved out of keymanager instantiation and be done, at the begining, when the UA starts... Something similar to: https://github.com/pixelated/pixelated-user-agent/commit/debb86dfc9cf70d310bd3b45dc32c91d5d26b9d1

related PR:   https://github.com/leapcode/keymanager/pull/116
related Issue: https://github.com/pixelated/pixelated-user-agent/issues/763
Also, will solve https://github.com/pixelated/pixelated-user-agent/issues/753

**Comment by mnandri** [comment]
Currently keymanager instantiation combines certificates into one file. This is done for each user, although it is the same certificates for all of them.
This process should be moved out of keymanager instantiation and be done, at the begining, when the UA starts... Something similar to: https://github.com/pixelated/pixelated-user-agent/commit/debb86dfc9cf70d310bd3b45dc32c91d5d26b9d1

related PR:   https://github.com/leapcode/keymanager/pull/116

**Comment by tuliocasagrande** [comment]
@mnandri The PR was merged. What are the next steps?

**Comment by mnandri** [comment]
@tuliocasagrande 
there's only one next step: implement the rest...
tha is, during the UA bootstrap: run [the procedure](https://github.com/pixelated/keymanager/blob/develop/src/leap/keymanager/__init__.py#L157) create the combined_ca_bundle, and supply the filename to all subsequent Keymanager instantiations.

**Comment by tuliocasagrande** [comment]
@bwagnerr and I moved the `combined_ca_bundle` to the UA initialization.

@thaissiqueira @deniscostadsc is it possible to measure the impact on #771 ?

**Comment by deniscostadsc** [comment]
@tuliocasagrande 

We'll take a look on that. But I think we should test before and after this change.

**Comment by tuliocasagrande** [comment]
We opened a second PR: https://github.com/leapcode/keymanager/pull/117

**Comment by tuliocasagrande** [comment]
Review steps:

- [ ] check our changes
- [ ] wait for leap PR

**Comment by thaissiqueira** [comment]
Is this error related with this issue?
```
2016-08-31T21:17:20.442300+02:00 unstable1 pixelated-user-agent[19136]: 2016-08-31 21:17:20 [pixelated.resources.login_resource] INFO [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 2] No such file or directory: '/var/lib/pixelated/.leap/providers/unstable.pixelated-project.org/keys/client/ca_bundle'
```

**Comment by tuliocasagrande** [comment]
@thaissiqueira yes, it is. 
It's going to be fixed in https://github.com/leapcode/keymanager/pull/117

@bwagnerr and I were thinking to write a temporary patch to mitigate this problem while we don't get the PR merged.

**Comment by tuliocasagrande** [comment]
The leap PR was merged 🎉 
We still need someone to review our changes

@mnandri @varac can you do this when you have the chance? 💚
