### ISSUE TITLE
Adapt the twisted patch to measure inlineCallbacks correctly

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#768]
What
---
As mentioned on #763, our current twisted measurement patch only measured traditional deferred callbacks accurately.

Definition of done
---
We have a patch we can use to measure both traditional callbacks and inlineCallbacks accurately

---

This is the excerpt from that issue:

> We analysed the patch to understand the behaviour of the timings when used with inlineCallbacks and came to the belief that our patch can only measure correctly traditional defer.addCallback calls.
> 
> When used with inlineCallbacks, the timing of the patch includes everything from the start of the inlineCallback invocation to the defer.returnValue(x) at the end. This includes all the yields that interrupt the method execution and allow other things to run on the reactor.
> 
> With this we concluded that the current patch can't be used to time inlineCallbacks, we are adapting the current approach to filter the inlineCallbacks timing and are working on adding a timing for the inlineCallback g.send(result), that resumes the execution of the inlineCallback generator until the next yield interruption or the end of the method.

**Comment by thaissiqueira** [comment]
We added the new patch on the commit above, details below:

> We did two changes to the twisted patch to be able to
> measure the inlineCallbacks correctly:
> - Filtered the traditional callbacks timing so that it
> doesn't print inlineCallback timings
> - Added a measurement for the g.send() method inside
> the inlineCallback, to measure the actual execution
> time of the call on the main thread, between the
> inlineCallback yields

The new patch is here:
https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/defer.patch

It will log:
- The call type (Deferred callback or inlineCallback)
- The method name, file and line number where the call was made
- The thread ID the deferred is running on
- The timing of the execution on that thread

**Comment by mnandri** [comment]
It seems that the patch does not cater for the unexplained/cumulative/confusing timing for inlineCallbacks.

Running a single user login, still shows the following:
```
0.29302 EXECUTING inlineCallback: <code object _index_all_mails at 0x7f2c0d215330, file "pixelated/config/services.py", line 48> in thread 139827288909568
0.29311 EXECUTING inlineCallback: <code object all_mails at 0x7f2c0bf64030, file "pixelated/adapter/services/mail_service.py", line 38> in thread 139827288909568
0.29319 EXECUTING inlineCallback: <code object all_mails at 0x7f2c0d221ab0, file "pixelated/adapter/mailstore/leap_mailstore.py", line 227> in thread 139827288909568
0.29327 EXECUTING inlineCallback: <code object get_mails at 0x7f2c0d221830, file "pixelated/adapter/mailstore/leap_mailstore.py", line 207> in thread 139827288909568
0.29335 EXECUTING deferred: <bound method DeferredList._cbDeferred of <DeferredList at 0x7f2c080d6320>> (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/defer.py:882) in thread 139827288909568
0.29497 EXECUTING inlineCallback: <code object get_mail at 0x7f2c0d2217b0, file "pixelated/adapter/mailstore/leap_mailstore.py", line 197> in thread 139827288909568
0.29512 EXECUTING inlineCallback: <code object _leap_message_to_leap_mail at 0x7f2c0d227230, file "pixelated/adapter/mailstore/leap_mailst2016-08-26 13:26:57 [twisted] INFO Stopping factory <leap.common.http._HTTP11ClientFactory instanc
0.29528 EXECUTING inlineCallback: <code object _mailbox_name_from_uuid at 0x7f2c0d227330, file "pixelated/adapter/mailstore/leap_mailstore.py", line 337> in thread 139827288909568
0.29544 EXECUTING inlineCallback: <code object _mailbox_uuid_to_name_map at 0x7f2c0d221c30, file "pixelated/adapter/mailstore/leap_mailstore.py", line 247> in thread 139827288909568
```
which all come from `_index_all_mails`

I created a very simple snipet to check this: [see here ](https://gist.github.com/mnandri/b85c76ba4aad22fe5959b3e3461d0d82)
which simply runs inline1 inside inline2. The result confirms the assumption:
```
4.00417 EXECUTING inlineCallback: <code object inline2 at 0x7f66704f0eb0, file "yoyo.py", line 56> in thread 140077948737280
4.00569 EXECUTING deferred: <bound method _ThreePhaseEvent._continueFiring of <twisted.internet.base._ThreePhaseEvent object at 0x7f666cb09090>> (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/base.py:420) in thread 140077948737280
Reactor was blocked for 4.0 seconds
1.00114 EXECUTING inlineCallback: <code object inline1 at 0x7f66704f0730, file "yoyo.py", line 46> in thread 140077948737280
1.00161 EXECUTING inlineCallback: <code object inline2 at 0x7f66704f0eb0, file "yoyo.py", line 56> in thread 140077948737280
Reactor was blocked for 1.0 seconds
3.00134 EXECUTING direct: inline1 in thread  140077948737280
[8, 8]
9.00585 EXECUTING direct: inline2 in thread  140077948737280
7.00710 EXECUTING deferred: <function cb_blocking at 0x7f666c6a8398> (yoyo.py:77) in thread 140077948737280
the result is True
3.00318 EXECUTING deferred: <function show at 0x7f666c6a8410> (yoyo.py:72) in thread 140077948737280
10.01291 EXECUTING inlineCallback: <code object inline2 at 0x7f66704f0eb0, file "yoyo.py", line 56> in thread 140077948737280
10.01317 EXECUTING inlineCallback: <code object inline1 at 0x7f66704f0730, file "yoyo.py", line 46> in thread 140077948737280
```
It will attribute timings to both the inline callbacks inline1 and inline2

**Comment by mnandri** [comment]
[Here is a fix to the twisted.patch](https://github.com/pixelated/pixelated-user-agent/blob/480e7d3bd48f2a7c23a76843750daaa03f2b12b3/service/test/reactor/defer.patch)

Running the [same snippet](https://gist.github.com/mnandri/b85c76ba4aad22fe5959b3e3461d0d82), shows:
```
starting watchdog...
4.00416 EXECUTING inlineCallback: <function inline2 at 0x7fc511ae0578> in thread 140484448438016
4.00743 EXECUTING deferred: <bound method _ThreePhaseEvent._continueFiring of <twisted.internet.base._ThreePhaseEvent object at 0x7fc511f60f10>> (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/base.py:420) in thread 140484448438016
Reactor was blocked for 4.0 seconds
1.00115 EXECUTING inlineCallback: <function inline1 at 0x7fc511ae0488> in thread 140484448438016
Reactor was blocked for 1.0 seconds
3.00115 EXECUTING direct: inline1 in thread  140484448438016
[8, 8]
9.00541 EXECUTING direct: inline2 in thread  140484448438016
7.00708 EXECUTING deferred: <function cb_blocking at 0x7fc511afc410> (yoyo.py:77) in thread 140484448438016
the result is True
3.00310 EXECUTING deferred: <function show at 0x7fc511afc488> (yoyo.py:72) in thread 140484448438016
```
We can conclude:
* new twisted patch will measure correctly inlineCallbacks own time (ie not including inner-yield)
* direct measurements inside an inlineCallbacks will give the total time taken
* callback time is correct, as is stated from the Ola's original patch

With this, we are able to know all inlineCallbacks own time as well as all addCallback time. What is missing is normal deferreds time. Although, that could be inferred from the direct measurement for the inlineCallback case.

**Comment by thaissiqueira** [comment]
After @mnandri tests and explorations we talked to him and spotted a problem when measuring the defer.returnValue times inside inlineCallbacks. It was measuring the whole time of the deferredChain (including all callbacks that were added after that).

We adapted the code to stop the clock right after the result is received and used the @mnandri  gist to re-test the problem. Now the patch is showing the correct time from the last yield to the defer.returnValue call.

For reference, this was the change: https://github.com/pixelated/pixelated-user-agent/commit/d107dd9fa0f5d837adb952fb8cb3f8b3b0b9804c

We also normalised the line output in this [commit](https://github.com/pixelated/pixelated-user-agent/commit/6fe3b52af612062927b5d14a69f8f66d2e33635e):
- callbacks and inlineCallbacks appear in the same format
- explicitly output the type of deferred
- changed the typing from deferred to callback

**Comment by mnandri** [comment]
This is great... just QA-ed briefly :)
The obvious limitation is the multiple yield logs for each call  from the same inlineCallback... follow up with login multiple users might be tricky :)
Nonetheless, it's as good as we should invest in this i would say...

**Comment by thaissiqueira** [comment]
@mnandri do you agree to close these issue for now and open another as necessary?

**Comment by mnandri** [comment]
I agree, we can close.
