### ISSUE TITLE
Investigate and fix: DeferredList._cbDeferred

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#770]
As is reported [here](https://github.com/pixelated/pixelated-user-agent/issues/762#issuecomment-242929128), this is the next big bottleneck.
This story is about investigating the root cause and provide a fix (remove/defer/deferToThread/deferToProcess)

Related/Parent issue" #762

**Comment by mnandri** [comment]
One source of the problem is traced back to  [soledad.get_from_index](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/adapter/mailstore/leap_mailstore.py#L250)

Here is the stack hierarchy:

> _index_all_mails 
> 
> - mail_service.all_mails
>   - leap_mail_store.get_mails <= **DeferredList._cbDeferred**
>     - get_mail
>       - _leap_message_to_leap_mail
>         - _mailbox_name_from_uuid
>           - _mailbox_uuid_to_name_map
>             - soledad.get_from_index [**Assumed slow**]
> - search_engine.index_mails [**slow in thread, non-blocking**]

Investigation
--------------
**Step 1: Benchmark**

On a single user login: the total request time is `0m0.885s`. There are 4 appearance of  `DeferredList._cbDeferred` in the log, and the maximum takes `0.2946s`

Running curl in [parallel and measuring time](https://github.com/pixelated/pixelated-user-agent/blob/get_leap_session/service/test/load/manual_loadtest.sh), with 10 users login (hatch rate=2reqs/s),
```
real    0m0.993s
real    0m1.734s
real    0m1.966s
real    0m2.658s
real    0m2.719s
real    0m3.272s
real    0m3.080s
real    0m3.660s
real    0m3.577s
real    0m3.138s
```
The 10 longest time for `DeferredList._cbDeferred` are:
```
0.0345
0.0385
0.2924
0.2941
0.2944
0.2973
0.3292
0.4120
0.4251
0.4335
```

**Step 2: Confirm**
The approach is to stub the `soledad.get_from_index` call as follows:
```
247     @defer.inlineCallbacks
248     def _mailbox_uuid_to_name_map(self):
249         map = {}
250         a = Mock()
251         a.content = {}
252         mbox_docs = [a,]
253         #mbox_docs = yield self.soledad.get_from_index('by-type', 'mbox')
254         for doc in mbox_docs:
255             map[underscore_uuid(doc.content.get('uuid'))] = doc.content.get('mbox')
256
257         defer.returnValue(map)
```

On a single user login, the request still takes `0m0.884s` but  the maximum time for `DeferredList._cbDeferred` is `0.0125s`

Login the same 10 users as above, hatch rate=2reqs/s, 
```
real    0m0.918s
real    0m1.067s
real    0m1.084s
real    0m1.234s
real    0m1.491s
real    0m1.294s
real    0m1.572s
real    0m1.798s
real    0m1.715s
real    0m1.503s
```
The 10 longest time for `DeferredList._cbDeferred` are:
```
0.0174
0.0182
0.0194
0.0198
0.0223
0.0238
0.0240
0.0244
0.0266
0.0368
```
This is somehow stabilized, although not definite as those number varies slightly as we do more login runs for the same users.

**Conclusion**
The [soledad.get_from_index](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/adapter/mailstore/leap_mailstore.py#L250) line heavily influence both independence of subsequent login requests and the total time per request.

**Comment by mnandri** [comment]
Update,
further investigation shows there was a mistake in the previous approach... `@defer.inlineCallbacks ` needs at least one `yield`... therefore the code was consistently errback-ing from the DeferredList... thus the consistency on the overall timing and independence...

**Comment by bwagnerr** [comment]
We validated that the login time doesn't increase anymore with more users after the latest changes. With that, we decided to move forward on other paths and deprioritize this issue.

I'll close this issue and we can reopen it if we decide to come back to this.
