### ISSUE TITLE
Confirm that the contention problem was mitigated on the login

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#771]
What we need to do?
--

Confirm that the contention problem was mitigated on the login.

How we will do that?
--

Run load test several times with 1, 10, 25, 50 and 100 users measuring the time of self._portal.login() also know as login-leap-session.

**Comment by deniscostadsc** [comment]
We are writing a script to help us to run several times without pain. We didn't finish yet. In the end of this issue we should be able to use this script every time we'll have a similar situation.

**Comment by olabini** [comment]
I'm not sure if I like the idea of measuring internals to ensure the contention is gone - since that doesn't take into account the whole stack, you won't notice if there is contention in some other part. I strongly recommend that the right way of testing this is to actually check how long the http request actually takes instead.

**Comment by deniscostadsc** [comment]
We finished the script that login several time for many users. And we instrumented the code of UA to measure login method.

@olabini, we already thought on that and this is the next step. We can do both approaches at the same time with almost no work.

**Comment by thaissiqueira** [comment]
We got the measurements for 1, 5, 10, 25 e 50 users. Now we are processing this numbers in graphics.
We try to run with 100 users but on the middle of the day we had problems with internet.
We are going to get measurements for 100 users tomorrow.

**Comment by thaissiqueira** [comment]
Here are some numbers about login's time:

run 2016-08-31
--
![20160831 - login metrics - request x method](https://cloud.githubusercontent.com/assets/13627260/18186697/883668a6-707a-11e6-92fb-388f28beec5c.png)

To got this numbers we ran:
```
# ./concurrent_logins.sh -u 1,5,10,25,50 -r 15 -p unstable.pixelated-project.org
```
[This script](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/concurrent_logins.sh) does the 'http://localhost:3333/login' request 15 times for 1,5,10,25,50 users, measuring this response time and [portal.login()](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/resources/login_resource.py#L153) call.

run 2016-09-01
--
Today we ran the same script, but with more users and more times:
```
# ./concurrent_logins.sh -u 1,5,10,25,50,75 -r 25 -p unstable.pixelated-project.org
```
That one does the 'http://localhost:3333/login' request 25 times for 1,5,10,25,50,75 users, measuring the same response time and portal.login() call.

![20160901 - login metrics - request x method](https://cloud.githubusercontent.com/assets/13627260/18186696/8830fe52-707a-11e6-8a1d-dad02e9f4414.png)

It until have some deviation on the ’50 users’ run.

**Comment by thaissiqueira** [comment]
This is the graph with 1,5,10, 25, 50, 75 and 100 users running on the same way that are described above.

```
./concurrent_logins.sh -u 1,5,10,25,50,75,100 -r 25 -p unstable.pixelated-project.org
```

![20160902 - login metrics - request x method](https://cloud.githubusercontent.com/assets/13627260/18213637/98aa9202-711f-11e6-8c35-5e3c1c01ca82.png)

This graph show us that the contention problem on the login request and on the 'login-leap-session' (portal.login()) was mitigated. 
But is important to remember that it does not represent the total login's time. It represents only the time until loading page.

**Comment by olabini** [comment]
Fantastic work everyone! This is good news!
Of course, as you say there might still be contention in other places, but now the team is very aware of the procedure for finding and eradicating these kinds of problems.

**Comment by deniscostadsc** [comment]
@thaissiqueira,

@rdevries-thoughtworks and @mnandri would like to see raw data for the last test we did. But I forgot you got the data. Could you please share them here?

**Comment by thaissiqueira** [comment]
@deniscostadsc, @rdevries-thoughtworks, @mnandri I just saw this message now.
Here is the metrics' files: [Archive.zip](https://github.com/pixelated/pixelated-user-agent/files/464338/Archive.zip)

**Comment by thaissiqueira** [comment]
@rdevries-thoughtworks we ran the concurrent_logins.sh here and also could not start user-agent because the bonafide was not installed. 
To fix it  we ran  ```cd /vagrant/service; ./go setup``` inside pixelated-user-agent-vagrant and then it works.

So, the steps to review are:

- Check if the loadtest users are created on the provider you're going to use[1]
- Start pixelated-user-agent vagrant
-  Check if the pixelated-user-agent can be started on vagrant
- To get the login-leap-session time you need to add this clock below [here](https://github.com/pixelated/pixelated-user-agent/blob/metrics/service/pixelated/resources/login_resource.py#L151):

```
@defer.inlineCallbacks
def _handle_login(self, request):
    self.creds = self._get_creds_from(request)
    t = Clock('login-leap-session')
    iface, leap_session, logout = yield self._portal.login(self.creds, None, IResource)
    t.stop(leap_session.fresh_account, leap_session.user_auth.uuid)
    defer.returnValue(leap_session)
```

- And to get the same numbers that we got this command:

```
./concurrent_logins.sh -u 1,5,10,25,50,75,100 -r 25 -p unstable.pixelated-project.org
```

If you have any question, please ping @thaissiquera or @deniscostadsc.

[1] If not, you can use the [create_users.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/create_users.py) to create it.

**Comment by rdevries-thoughtworks** [comment]
Didn't get it to work yet. I started the user agent, but as soon as I started the `concurrent_logins.sh` script, it exited with:

```
2016-09-15 15:32:14 [twisted] INFO Received SIGTERM, shutting down.
2016-09-15 15:32:14 [twisted] INFO (TCP Port 3333 Closed)
2016-09-15 15:32:14 [twisted] INFO Stopping factory <pixelated.config.site.PixelatedSite instance at 0x7f141bab2a70>
2016-09-15 15:32:14 [twisted] INFO Main loop terminated.
```

**Comment by bwagnerr** [comment]
hey @rdevries-thoughtworks, the script itself spawns the user agent, so you don't have to worry about that, if there's any running it will kill the instance (that is what happened to you in this case)

**Comment by rdevries-thoughtworks** [comment]
Executed the `concurrent_logins.sh` script locally, and request times went from around 3 seconds (very rough average estimation) to below a second.
