### ISSUE TITLE
Multiple Attachments are displayed as one msg.asc when body is empty

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#774]
I sent yoyo an email with two attachments, see my screenshot below.

![screenshot_2016-08-30_11-57-04](https://cloud.githubusercontent.com/assets/488213/18084801/ea8ae91a-6ea8-11e6-9dc9-c4501526e394.png)

He got a mail with two messed up attachments, see here:

![index](https://cloud.githubusercontent.com/assets/488213/18084859/1defa1e2-6ea9-11e6-8f5c-6d99a1b6a9a8.png)

**Comment by re-nobre** [comment]
hey @varac!
Can you confirm if this problem still happening?

**Comment by thaissiqueira** [comment]
I'm closing this issue because we did same steps and the error not happen again.
