### ISSUE TITLE
Investigate the complete login time (including loading page)

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#779]
What
---
After the latest improvements on login time (before the loading screen), we decided that it is important to measure the whole login time without emails, from pressing the login button to reaching the inbox

Definition of done
---
We have measurements for the performance of the whole login without emails considering until the user reaches the inbox

**Comment by bwagnerr** [comment]
I changed the concurrent_logins.rb script to wait until the loading page was finished to stop measuring. From two preliminary runs, these are the results:

| Request | Loading Page | Total   |
|---------|--------------|---------|
|2.726    |0.166         |**2.898**|
|2.963    |0.127         |**3.099**|
|2.101    |0.120         |**2.227**|
|2.159    |0.040         |**2.207**|
|2.298    |0.115         |**2.421**|
|2.232    |0.116         |**2.354**|
|2.015    |0.117         |**2.138**|
|2.154    |0.132         |**2.292**|
|2.276    |0.120         |**2.402**|
|2.053    |0.111         |**2.171**|

| Request | Loading Page | Total   |
|---------|--------------|---------|
|2.903    |0.137         |**3.046**|
|2.892    |0.142         |**3.046**|
|2.369    |0.119         |**2.502**|
|2.106    |0.024         |**2.136**|
|2.027    |0.137         |**2.172**|
|2.176    |0.111         |**2.300**|
|2.288    |0.116         |**2.412**|
|2.077    |0.115         |**2.202**|
|2.282    |0.116         |**2.405**|
|2.412    |0.112         |**2.535**|


That means it accounts for a small part of the login experience (considering the login without emails).

Should we dig deeper inside that time to understand what is taking that time?

**Comment by bwagnerr** [comment]
After the [latest commit](69cbc6713bb156a845e9a616b35927cfce8cf70c) that measured the whole login time, Ola suggested putting a sleep between interstitial requests to prevent overloading the server with these requests.
I've done that on e7f9c3c7220618438830cd36361db5089351cf81 and re-run the tests, the results are below:

The medians were:
Login Request: **2.306**
Loading page: **0.103**
Total time: **2.409**

|Login Request|Loading Page|Total time|
|-------|------------|----------|
|3.095  |0.114       |**3.216** |
|3.049  |0.115       |**3.177** |
|2.414  |0.107       |**2.527** |
|2.306  |0.059       |**2.371** |
|2.075  |0.103       |**2.183** |
|2.402  |0.103       |**2.511** |
|2.364  |0.108       |**2.480** |
|2.322  |0.107       |**2.435** |
|2.479  |0.102       |**2.586** |
|2.828  |0.103       |**2.941** |

|Login Request|Loading Page|Total time|
|-------|------------|----------|
|2.877  |0.118       |**3.001** |
|2.753  |0.119       |**2.878** |
|2.142  |0.102       |**2.254** |
|1.957  |0.059       |**2.022** |
|2.047  |0.104       |**2.156** |
|2.246  |0.104       |**2.357** |
|2.012  |0.114       |**2.136** |
|2.143  |0.101       |**2.250** |
|2.110  |0.103       |**2.219** |
|2.206  |0.100       |**2.320** |

**Comment by thaissiqueira** [comment]
We successfully reproduced the above tests and have a few considerations:

* The loading page time after https://github.com/pixelated/pixelated-user-agent/commit/e7f9c3c7220618438830cd36361db5089351cf81 is increased by 0.05 seconds, which is the sleep time between requests;
* The achieved results are bound to the specific environment configuration (local machine without vagrant using dev as provider) and do not necessarily reflect the login time of our production environment;
* We tested with new and old test users, by removing their emails. Even, removing the emails, the latter took more time to log in.
