### ISSUE TITLE
Adapt the twisted patch to identify DeferredList times

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#784]
What
---
On issue #783, we identified some calls to _cbDeferred that were taking a long time for logins with emails. On a superficial inspection I found out those calls are made by twisted DeferredLists that we use on the code. We have to adapt the twisted patch to correctly measure and identify the source of those DeferredList calls

Definition of done
---
DeferredLists are correctly identified and their time measured using our twisted patch

**Comment by rdevries-thoughtworks** [comment]
In order to keep the patch in the repo, I would suggest monkey-patching instead of actually changing the twisted code inside the virtualenv.

**Comment by thaissiqueira** [comment]
Moving back this issue to 'ready' column to prioritize the [functional tests analysis] (https://github.com/pixelated/puppet-pixelated/issues/53).

**Comment by re-nobre** [comment]
as the fix contention problem with emails is one of our weekly goals, this issue is prioritesed again. :) 

@bwagnerr can you update the issue with what you discovered last week?

**Comment by mnandri** [comment]
`_cbDeferred` collects results of all  Deferreds in the deferredList, and then run callbacks attached to the deferredList (not to each Deferreds).
The hierarchy is like this:
gatherResults/DeferredList -> _cbDeferred -> callback -> _runCallBacks (where current patch lies)

=> The `_cbDeferred` time mesurements, measures the time that it takes to finish all the callbacks of the deferredList. That is, the cumulative time between when the last Defered result is obtained and when the last callback of the deferredList is finished.

We can simply ignore the `_cbDeferred` measurements as it is cumulative, and the detailed measurements for each callbacks (or next inlineCallback) is already measure by the current patch.
This can be shown,  using [this snippet](https://gist.github.com/mnandri/b8a6023cf8be19414d32cb3834396dfe).

**Comment by deniscostadsc** [comment]
@mnandri

In the case you mentioned, you already know and measure the callbacks inside the _cbDeferred. But how the case @bwagnerr said he doesn't know which callbacks are inside are inside the _cbDeferred.

Is that right?

**Comment by mnandri** [comment]
@deniscostadsc 
True but my point is, we don't need to know them from _cbDeferred.
Their measurement will appear on their own if they are bigger than the threshold.
Tracking them from _cbDeferred is redundant and not priority.

**Comment by deniscostadsc** [comment]
@bwagnerr has points to add here.

**Comment by bwagnerr** [comment]
@mnandri my understanding when looking at that code is that it added one cbDeferred for each callback, thus the timing of the cbDeferred would be the time of one callback call, are you sure there is only one cbDeferred per DeferredList and that it collects all of the callbacks?

I didn't have time to confirm it, just wanted to point this out before moving on to other issues.

**Comment by mnandri** [comment]
@bwagnerr 
you can run [this](https://gist.github.com/mnandri/b8a6023cf8be19414d32cb3834396dfe) to understand what it does.
We can talk when you are back.

**Comment by bwagnerr** [comment]
Hey, I checked this and I'm okay with the solution, I'll close the issue
