### ISSUE TITLE
Investigate/Fix decryption slowness on new incoming mails

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#785]
We have in the logs:

```
0.5580 inlineCallback: function decrypt (/root/junk/git_env/src/leap.keymanager/src/leap/keymanager/__init__.py:467) in thread 139677182150400
0.5581 callback: function decrypt (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/defer.py:1305) in thread 139677182150400
```

**Comment by mnandri** [comment]
Login with emails but no new emails (pure sync), does not have this decrypt slowness. It is only present when there are new incoming emails.

**Comment by mnandri** [comment]
Running a login on a single new email, the overall decrypt callback takes around 250ms (using our patch measurements). 
Running leap's independent [benchmark measurement](https://0xacab.org/leap/keymanager/merge_requests/5/commits), GPGwrapper init+decryption on the same machine (dev.pix) takes on average: 201ms (also median).
Given:
- the leap benchmark test is not decrypting the exact same ciphertext as our login
- both measurements are relatively on the same range of magnitude
- keymanager puts all decryption operations on a separate thread and the underlying python-gnupg also runs actual gpg  on a subprocess. Although expensive, these are non-blocking operations.
I'm discarding this for now and will move on the next blocker.

**Comment by mnandri** [comment]
Just re-confirmed that our patch measurement does not account for time spent in threads.
We are effectively spending those 250ms in the reactor (on top of the potentially 201ms in threads for actual decryption).
This is not sorted out.

**Comment by mnandri** [comment]
Direct measurement (using Clock), shows the blockage is in the [TempGPGwrapper](https://github.com/pixelated/keymanager/blob/develop/src/leap/keymanager/openpgp.py#L625) contextmanager:
```
0.2328 haha : function haha inside tempgpgwrapper in thread 0
0.2337 haha inlineCallback: function decrypt (/root/junk/keymanager/src/leap/keymanager/openpgp.py:612) in thread 139738256766720
0.2337 haha inlineCallback: function decrypt (/root/junk/keymanager/src/leap/keymanager/__init__.py:467) in thread 139738256766720
0.2338 haha callback: function decrypt (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/defer.py:1305) in thread 139738256766720
0.1006 haha : function haha decrypting in thread in thread 0
0.3339 haha : function haha overall openpgp in thread 0
```

**Comment by mnandri** [comment]
with a clocking [like this](https://gist.github.com/mnandri/68a3bc6dc9829c5981b26bca0c0f3e59), we get
```
0.1004 haha : function haha gpg instantiation tmpgpgw in thread 0
0.0140 haha : function haha leapassert 1 tmpgpgw in thread 0
0.0928 haha : function haha import keys tmpgpgw in thread 0
0.0646 haha : function haha leap assert2 tmpgpgw in thread 0
0.2721 haha : function haha overall tmpgpgw in thread 0
```
We should discuss if there is a way to only do the wrapper once per user (at instantiation or something)  or alternatively, deferToThread the overall operation: wrapper enter + decrypt + wrapper exit
@kalikaneko @drebs @meskio comments/suggestions... or do you have preference over those 2...
we can do a PR.

**Comment by meskio** [comment]
We had the idea of reusing the wrapper and it might be a good choice to do so. To do it we'll need to have some extra complexity to make sure that the keys in the wrapper and the keys in the keyring are in sync.

**Comment by mnandri** [comment]
update:
I pushed a [few commits](https://github.com/pixelated/keymanager/tree/single_tmp_gpg_wrapper) in the old keymanager on Friday... so that i can do measurements, while waiting for the process on how do we move to bitmask-dev.

**Comment by mnandri** [comment]
The commits basically implements a single GPG instantiation per user, per session...
That saves ~100ms per TempGPGWrapper instantiation ie encrypt/decrypt/all gpg operations.

**Comment by mnandri** [comment]
This is blocked because of the move to bitmask-dev

**Comment by mnandri** [comment]
There are two  alternative possible improvements remaining, pertaining this issue:
* smarter way of  import/delete keys in the keyring, for every wrapper 
* provide passphrase to avoid import/delete altogether

The first one is not-pursued at this point as there is no way around import/delete private keys without compromising security (given there is no passphrase), so we would really save less than 50ms.

The second one is ideal but also not prioritized as there is no trivial solution and could take time to implement... and should ultimately be on its own issue.

**Comment by anikarni** [comment]
Closed due to inactivity
