### ISSUE TITLE
Functional tests users are staying on leap webapp

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#787]
## What
Our current "functional tests" are creating a lot of users and these users are staying on the leap webapp. 

It's being  a problem for the sysadmins because it's hard to find the real users in a big list with a lot of strange users.

## Definition of done

**Comment by varac** [comment]
This is the old issue about the same problem: https://github.com/pixelated/puppet-pixelated/issues/36

I wonder how this can happen because we don't see this behaviour in our envs anymore (well on unstable.bm I just saw 3 stale testusers in the webapp from the last month).

**Comment by varac** [comment]
should we re-open pixelated/puppet-pixelated#36 or continue here?

**Comment by varac** [comment]
Hugh, i can confirm that at least not all `testuser_` users are removed from the webapp. unstable.bm has 3 of them, dev.bm has 34. So we need some mechanism that removes those old ones (obvious removing them from within the test is not reliable). Maybe we implement the removing of all stale testusers at the beginning of the new test run ?

**Comment by varac** [comment]
Hugh, i can confirm that at least not all `testuser_` users are removed from the webapp. unstable.bm has 3 of them, dev.bm has 34. So we need some mechanism that removes those old ones (obvious removing them from within the test is not reliable). Maybe we implement the removing of all stale testusers at the beginning of the new test run ?

![screenshot_2016-10-04_14-13-59](https://cloud.githubusercontent.com/assets/488213/19073730/d6bd17c8-8a3c-11e6-885b-a4320ea3adac.png)

**Comment by re-nobre** [comment]
Hey, varac! 
As you linked the #36 here, I think it is ok we continue here. :)

**Comment by tayanefernandes** [comment]
We noticed that we are creating an user in the "Register" scenario, but we just try to delete it after we run all the scenarios. If for some reason the "after all" step fails, we will not delete the user.
So @thaissiqueira and I will add a step to delete the user after the "Register" scenario.

**Comment by thaissiqueira** [comment]
We discovered that the [delete function](https://github.com/pixelated/puppet-pixelated/blob/master/files/functional-tests/environment.py#L50) is not working properly. Now we are investigating it.

**Comment by thaissiqueira** [comment]
The click method is not working when we are trying to click on the destroy button.
`self._find_elements_by_css_locator(delete_button_selector)[0].click()`

**Comment by mnandri** [comment]
My earlier suggestion:
scrap the whole behaviour driven tests for user-deletion and call direct the `destroy_user_db` script in `/srv/leap/couchdb/scripts` using subprocess or something.
That will be faster and less flaky.
@thaissiqueira @tayanefernandes

**Comment by thaissiqueira** [comment]
@mnandri thanks for the suggestion.
We tried to run this script on dev but the result was "the user does not exist".
Let's pair tomorrow?

**Comment by mnandri** [comment]
You can verify by:
- trying to login the user or
- verifying the user-db and identities in couchdb or 
- recreate the user <= i think this  is the ultimate goal/requirement of the FT :)
yes, happy to pair.

**Comment by tayanefernandes** [comment]
We fixed the test using the Naval's suggestion.
Now we are just waiting for the issue that is fixing the package (issue #357).
After that we will send a script to Guilherme from Araguaia, to delete all the old test users that were created.

**Comment by varac** [comment]
Hej, what's the current state ? What's blocked ?

**Comment by thaissiqueira** [comment]
We sent an email to remove the remaining test users and with that the araguaia's sysadmin can see the list with all real users.

But we still need to do a deploy to fix the test code to delete the test users during the execution.

Now we are trying to reproduce the deploy steps before put it on production but we are with problems in staging, dev and try environments. So we need to fix this environments or use unstable to to that because we want to ensure that the new version will be reliable.

**Comment by tayanefernandes** [comment]
We sent the email to Guilherme, to update the functional tests with the fix.
