### ISSUE TITLE
Move to new twisted logger setup

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#789]
What
---
We have a controlled leak since Twisted version 15.

Why
---
Twisted moved to a new logging system and it holds reference to all the log lines emitted (and objects it references) until you call `beginLoggingTo` on the globalLogger.

We were using the old twisted log infrastructure and the python default blocking logger.

Definition of done
---
We use twisted new logging infrastructure for user-agent logs and we stop using the default python logger.

**Comment by thaissiqueira** [comment]
We checked that the _HTTP11ClientFactory is not increasing the number of instances after login anymore.
