### ISSUE TITLE
Not able to see special characters in the emails

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#797]
We are not able to see special characters.

It is related to the PR https://github.com/pixelated/pixelated-user-agent/issues/794

<img width="719" alt="screen shot 2016-10-20 at 2 39 53 pm" src="https://cloud.githubusercontent.com/assets/10910322/19569089/1d8a23ba-96d3-11e6-88a9-9d6a67a57601.png">

**Comment by ayoyoness** [comment]
To QA:
resend the same email... and see it rendereded

**Comment by thaissiqueira** [comment]
Is it should be working already on wazokazi? Because I check it now and is not working there.
We need to deploy platform?

<img width="1083" alt="screen shot 2016-10-22 at 11 37 28 pm" src="https://cloud.githubusercontent.com/assets/13627260/19623653/da206b40-98b0-11e6-873e-8dabaad4301f.png">

**Comment by thaissiqueira** [comment]
I checked it again and now it is working.
