### ISSUE TITLE
signup through pixelated

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [pixelated/pixelated-user-agent#801]
_spawned from #791, estimation: 5 points_

Create a screen for Pixelated signup, which calls the Bonafide API. After signup, the user is redirected to the inbox (first showing the interstitial).

Flow:

- **user** enters invite-code, goes to the next screen
- **user** enters username/password, posts to Pixelated UA
- **Pixelated** sends invide-code/username/password to Bonafide
- **Bonafide** creates the user, returns a session token
- **Pixelated** redirects the user to inbox

Background
----------

When you register with LEAP, you register with the Bonafide server, which is the RoR web app. Bonafide creates a document in the `users` database in CouchDB, containing e.g. the password verifier, and another document in the `tokens` database containing the currently active token that the user can use as authentication for e.g. (and mainly) Soledad. Currently, the Soledad server uses this `tokens` database directly to authenticate users, but the intended design is that Soledad doesn't have direct access to this database, and the user is authenticated through an API call to the Bonafide server.  The password never reaches the Bonafide server in plain text, but the password is always SRP'ed by the Bonafide client.  Note that Pixelated UA plays both the roles of Bonafide client and Soledad client.

Task breakdown
--------------

-  Refactor:
    - [x] Resources tests: delete tests that we are not using, fix the tests that are testings something wrong
    - [x] Create the PublicRootResource (this way we can have login and signup together)  
    - [x] Moving the new InboxResource from RootResource
    - [x] Reorganize the static files (they are spread over the place)
    - [x] Reorganize the static files that are mixed with things like templates 
    - [x] Remove duplicate twisted resources
    - [ ] ~~Use the Twisted modules instead of the copy-pasted code from it~~

- Implement:
   - [ ] "insert code" screen
   - [ ] "create account" screen
   - [ ] call the Bonafide API
   - [ ]  redirect to inbox after the account be created

**Comment by tayanefernandes** [comment]
Hi @rdevries-thoughtworks! Is this estimation considering that we will try to use [React](https://facebook.github.io/react/) in the UI (since FlightJS is being deprecated) and we should consider a time to learn more about it?

**Comment by tayanefernandes** [comment]
@SweetVirginia will the signup screen follow the prototype design (https://projects.invisionapp.com/share/ZR8W9K1DA#/screens/195625135) or will we change it?

**Comment by rdevries-thoughtworks** [comment]
@tayanefernandes 

> Is this estimation considering that we will try to use React in the UI 

Yes and no. In principle, the estimation is supposed to be independent of how we'll implement it, and our knowledge of specific technology. The estimation should be a property of the story, independent of the implementer. This is an example of why (in good projects) a team increases velocity over time: they get more knowledge of the technology used, so they can build the same functionality faster.

Apart from that, setting up React will take some time, but my guess is it's not too much.

**Comment by rdevries-thoughtworks** [comment]
I created a branch 'signup' where you can preview how React works. To run it locally (untested):

    cd web-ui
    npm intall
    npm run build-signup
    npm install http-server
    http-server

... and go to [http://localhost:8080/signup/](http://localhost:8080/signup/).

**Comment by SweetVirginia** [comment]
@tayanefernandes We should improve that prototype a little bit. Specially adding some graphics. Is it time do do it now? If it is, we should organise our workflow for that :)

**Comment by tayanefernandes** [comment]
> Is it time do do it now? If it is, we should organise our workflow for that

@SweetVirginia I think so, because Roald started to work on this. What do you think @rdevries-thoughtworks?

**Comment by rdevries-thoughtworks** [comment]
@SweetVirginia @tayanefernandes Yes, now is the time! I'll take it into account and won't spend to much time on the front-end details.

**Comment by SweetVirginia** [comment]
Guys, this is an idea for the Invite Code desktop screen, I'm still deciding if the image will show up on mobile devices. The reason why there is what Pixelated is on this screen is to cover a use case we've been observing - people hear about Pixelated in the organisation, ask for an invite code but then have little context when creating account, so this is sort of an onboarding.  
Not all graphics are ready, but I would like your feedback. Sorry is still in Portuguese, I decided to do it first because our users now are Brazilians and Portuguese has larger words, but soon I come back here with the international version. ![invite_code](https://cloud.githubusercontent.com/assets/6019419/20503821/935782ce-b02b-11e6-818f-06daef72e4cc.png)

**Comment by rdevries-thoughtworks** [comment]
Catch up of the status:
- currently, only the login resource is public, and served as the root resource, and it's not trivial to add another public resource (like signup) next to it; there are other pains (see below) with the way the resources are layed out; I'm working on fixing this by pushing authentication 1 level down the resource tree (and moving the new `InboxResource`, which is currently part of the `RootResource`, to that level as a special case)
- some (resource) tests weren't actually testing anything, or tested something wrong, so I worked on that too; they're by no means fixed, but at least moved a step in the right direction.

Other pains with the resources layout: static files spread over the place, static files mixed with things like templates, duplicate twisted resources, copy-pasted code from private Twisted modules, adapted that code intransparently.

**Comment by rdevries-thoughtworks** [comment]
A bit more details about the refactoring I'm doing:

Instead of delegating to a `LoginResource` on the root url when logged out, I'll delegate to a `PublicRootResource`. This public root resource will have the `LoginResource` on `/login`, and get the SignupResource on `/signup`. It will also have the sandbox and static files as child resources. When `/` is requested by an unauthenticated user, he will be redirected to `/login` by the public root resource. I'll remove the exception that serves the sandbox when not authenticated, remove the static files and the login resource from the (protected) RootResource, and will make it delegate to (maybe inherit from) the public root resource for public urls.

**Comment by re-nobre** [comment]
Hey, @rdevries-thoughtworks !

Thanks for bringing more details.

I will put here what I understood about what we need to for finish this issue. 
Please correct me, if I'm wrong or miss something.

The steps for this issue be done are:

-  Refactor:
    - [x] Resources tests: delete tests that we are not using, fix the tests that are testings something wrong
    - [ ] Create the PublicRootResource (this way we can have login and signup together)  
    - [ ] Moving the new InboxResource from RootResource
    - [ ] Reorganize the static files (they are spread over the place)
    - [ ] Reorganize the static files that are mixed with things like templates 
    - [ ] Remove duplicate twisted resources
    - [ ] Use the Twisted modules instead of the copy-pasted code from it 
    - [ ] Adapted that code (what code?) in-transparently.

- Implement:
   - [ ] "insert code" screen
   - [ ] "create account" screen
   - [ ] call the Bonafide API
   - [ ]  redirect to inbox after the account be created

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks
Hey, most of these problems are tech debts left from the rush of the multi-user transition.
I like the idea of fixing this now, we need a new public resource and the work to have this is kinda big (as you stated in bigger detail).

Considering this I want to ask, should we create a new issue for these changes. I feel they work to enable the signup but they are not part of the signup in my view.

**Comment by rdevries-thoughtworks** [comment]
@bwagnerr What would be the advantage of a new card?

I think this depends on how high-level we want our github issues. If we want them at the task-level, then it makes sense, but then we have to create a whole lot more. If we want them at the user story/functionality level, then I would normally not split out refactorings that are needed to get the story done.

**Comment by rdevries-thoughtworks** [comment]
@re-nobre: looks good, but 2 remarks:

Regarding "removing the copy-pasted code": if that's possible without too much hassle. It looks like we're not doing anything that couldn't be done by twisted's http authentication module, but I'm not entirely sure yet.

Regarding "Adapted that code (what code?) in-transparently": this is referring to `PixelatedAuthSessionWrapper`, so should already be covered by "removing the copy-pasted code".

**Comment by tuliocasagrande** [comment]
@rdevries-thoughtworks 
Thank you for summarising.

For me, it seems the main problem is the root resource being `\login`, blocking the possibility of making `\signup` also public.
In order to move faster and tackle tech debts one at a time, is it possible to only implement `\` as the root and then move on?

**Comment by deniscostadsc** [comment]
@rdevries-thoughtworks first of all thanx for the explanation.

This is happening really often. You start a issue, and then you face few problems that are going to add some challenges to solve your issue. These problems are related to architecture, python/twisted anti-patterns and much more things. I have the opinion that we need to fix these problem before move on. Of course we have to work in the minimum amount of problem to start to really work, but I think new cards for that is over managing.

**Comment by rdevries-thoughtworks** [comment]
@tuliocasagrande I'll go through the different refactorings:

- **Moving the new InboxResource from RootResource**: I started doing this with a different setup in mind. It would not be more work to remove it than to finish it. Otherwise indeed I shouldn't do it.
- **Reorganize the static files (they are spread over the place)** and **Reorganize the static files that are mixed with things like templates**: these are technically not required, but they were messed up because it was not clear how to do it right with the former setup. With the new setup it is clear, and if I don't change it now, I'm a bit scared people will keep misusing it. Moreover this should be simple to fix.
- **Remove duplicate twisted resources**: This morning, Naval and me chose for 1 `RootResource` class with a `public` flag in favor of the `PublicRootResource` class; this choice almost-automatically removes the duplicate Resource instances; if I encounter a place where there are 2 instances that can't be easily unified, I'll be pragmatic and leave them.
- **Use the Twisted modules instead of the copy-pasted code from it**: This one we *could* probably skip. On the other hand, in principle we would like to keep our code in a maintainable state, and not build up technical debt. If we ever want to pay this specific tech debt back, I think now would be *the* moment.

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks These bullet points on your last comment are a lot clearer than the ones up there, they could be the checkboxes for refactoring, would you mind updating those up there?

**Comment by rdevries-thoughtworks** [comment]
Feel free to update the first comment. I don't see what's clearer (I just copy-pasted ;-)).

**Comment by bwagnerr** [comment]
I see these as the synthesis of the small things, they work better as units of work and as checkable boxes.
I'll put the proposal here, see if it makes sense:

- [ ] **Moving the new InboxResource from RootResource**
- [ ] **Reorganize the static files**
- [ ] **Remove duplicate twisted resources**
- [ ] **Use the Twisted modules for authentication**

**Comment by rdevries-thoughtworks** [comment]
@bwagnerr I adopted your version of "Use the Twisted modules for authentication". I don't think removing checkbox items makes sense. It makes things less explicit and less clear. I could forget about the removed items, tell people I'm almost done refactoring, and then realize when all checkboxes are checked that I still have some tasks to do.

**Comment by SweetVirginia** [comment]
Some prototypes for the mobile version here: https://invis.io/RM9JRPXYF#/209143302_M_Signup_4 

I would love some feedback.

**Comment by SweetVirginia** [comment]
![01signup_1_en](https://cloud.githubusercontent.com/assets/6019419/20772049/28e972e4-b733-11e6-87fd-0806ed111902.png)
![02 signup_2_en](https://cloud.githubusercontent.com/assets/6019419/20772052/29016de0-b733-11e6-852a-f896009cecc8.png)
![03 signup_2a_en](https://cloud.githubusercontent.com/assets/6019419/20772054/2902f9da-b733-11e6-9a89-1768db2accda.png)
![04 signup_2b_en](https://cloud.githubusercontent.com/assets/6019419/20772053/2902999a-b733-11e6-9085-e5c317c1853f.png)
![form states](https://cloud.githubusercontent.com/assets/6019419/20772091/4bb0cbec-b733-11e6-8f53-587e73ab96d1.png)

**Comment by SweetVirginia** [comment]
Mobile version -> https://invis.io/RM9JRPXYF

**Comment by rdevries-thoughtworks** [comment]
This issue is blocked until #869, #870 and #871 are done.
