### ISSUE TITLE
The attachment icon is not indicating that it is clickable

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#811]
When we puts the mouse cursor over the attachment icon, it is not indicating that this icon is clickable.

**Comment by SweetVirginia** [comment]
@tayanefernandes This already helps a lot, but I would still add a button-like stroke like this: ![screen shot 2016-11-21 at 3 41 27 pm](https://cloud.githubusercontent.com/assets/6019419/20493712/0f51c4dc-b001-11e6-8a2a-8a47e91086ab.png)
Thinking in a future mobile user, it would be nice to avoid mouse overs. Is that ok?

**Comment by tayanefernandes** [comment]
@SweetVirginia Right! I created a new task for that and move this one to done.
https://github.com/pixelated/pixelated-user-agent/issues/824
