### ISSUE TITLE
Decide on a migration strategy

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [pixelated/pixelated-user-agent#813]
Figure out what it would take to migrate soledad so we can start using [LEAP's streaming branch](https://0xacab.org/leap/soledad/tree/78cd816cddfd76ee76ba1d372fb44fb41e717469/)

#### Definition of Done

A breakdown of how to implement the migrations into estimable parts.

**Comment by rdevries-thoughtworks** [comment]
After discussion with @shyba the fastest way to migrate seems to create a standalone script that:

1. gets docs from CouchDB
2. derives the soledad doc (by removing soledad metadata)
3. decodes the doc according to the old soledad version
4. encodes according to the new soledad version
5. derives the CouchDB doc (by restoring the soledad metadata)
6. put the doc to CouchDB

Notes:
- GPG-encrypted documents (that is: the ones that haven't been processed by leap mail in the client yet) should be skipped by this script.
- this doesn't reuse the flow of documents that's tested by usage -- trough the soledad server and client -- so we should test particularly well
- if the way we generate the MAC (message auth) changed, we can't go down this path; so we should double check that we didn't

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks this encoding/decoding happens after encryption? I would like to make sure we are not involving encryption/decryption of the symmetrically encrypted documents

**Comment by rdevries-thoughtworks** [comment]
@bwagnerr indeed, encoding happens after encryption, and decoding happens before decryption.

**Comment by rdevries-thoughtworks** [comment]
For reference: the old encoding of the document is done [here](https://0xacab.org/kali/soledad/blob/develop/client/src/leap/soledad/client/crypto.py#L304), the new encoding is done [here](https://0xacab.org/leap/soledad/blob/78cd816cddfd76ee76ba1d372fb44fb41e717469/client/src/leap/soledad/client/_crypto.py#L172).

**Comment by rdevries-thoughtworks** [comment]
It seems like the way we generate the MAC has changed, so a standalone script will not be possible.

**Comment by rdevries-thoughtworks** [comment]
The best approach @shyba and I could come up with: back-up the unsync'ed emails, remove the soledad server database, sync the documents back to the server, restore the unsync'ed emails.

Some details:
- backing up the emails is done by putting them back in the queue, like LEAP MX does
- we want to bring pix ua down while backing up, to prevent sync'ing during backing up (which could lead to duplicate mails)
- we want to somehow make sure that the mails from the queue won't be delivered to the Soledad server during back-up
- when the user logs in after removing the server database, sync'ing might take some time

Risk: if pixelated doesn't have all the sync'ed docs locally, the user will loose the missing docs; this seems hypothetical for the Pixelated use case though.

**Comment by rdevries-thoughtworks** [comment]
LEAP is working on supporting both 'schema's' temporarily. After that, at some stage, they might implement *real* migrations. I'm not sure if it's useful to keep this issue for now.

**Comment by shyba** [comment]
It's a deprecation policy to give us more time to finish this issue with a meaningful tool.

I created a pad [here](https://pad.riseup.net/p/migration-taskforce) for collecting ideas.

The tools should be simple and we are brainstorming it. On the pad we have the current knowledge on places where previous migrations happened and some gotchas to keep an eye. Feel free to add your idea there and try out a solution.

**Comment by varac** [comment]
What's the status of this ? Is https://github.com/pixelated/pixelated-user-agent/issues/813#issuecomment-259721368 still the way to go/review ?

**Comment by rdevries-thoughtworks** [comment]
@varac That's not entirely clear yet. If we do the encoding migration as a first step, then yes, removing the Soledad server database seems the way to go. But if LEAP stays backward compatible throughout the 3 schema changes (encoding, blob, doc_id), then we might invest in a more thorough and less hacky migration solution.

**Comment by bwagnerr** [comment]
Just to note, we can't get the incoming mails and put them back on the leap_mx queue, that's because the whole mail is encrypted by leap_mx and you won't have access to the metadata leap_mx need to place the mail on the right place

**Comment by bwagnerr** [comment]
Strategy
---
We decided to do this change by regenerating the userDB on Couch, these are the steps (some of them can translate into issues)

- [ ] Stop pixelated-user-agent, soledad-server and leap-mx
- [ ] Backup incoming mails from CouchDB
- [ ] Delete all docs and incoming mails from user database on CouchDB
- [ ] Change the 'replica_uid' of the 'Replica info' doc to make sure the next sync will happen from the start
- [ ] Update soledad-client and soledad-server
- [ ] Restore incoming mails on CouchDB
- [ ] Start pixelated-user-agent, soledad-server and leap-mx

**When the user log in, all the emails from SQLCipher will be synced back to user database on CouchDB with the right encoding.**

Note: The first user login after these steps will be slow (even slower for bigger inboxes).

Testing/dry-run of the migration
---
A big plus is that we can test these steps without migrating at all, we can remove one userDB from dev or unstable this way and validate that the db is regenerated correctly.

**Comment by rdevries-thoughtworks** [comment]
Re "Backup incoming mails from CouchDB": how would you do this? Put them back in the mail queue, or replicate them to another CouchDB, or something else still?

Re "The first user login after these steps will be slow": since (almost) all docs are already on the local (sqlcipher) copy, and the sync is mainly from client to server, could we do the sync in the background, so the user won't have to wait for so long?

**Comment by olabini** [comment]
Won't this run the risk of losing documents if not all documents have been synced?

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks
>Re "Backup incoming mails from CouchDB": how would you do this? Put them back in the mail queue, or replicate them to another CouchDB, or something else still?
We would extract them querying couchdb for documents with incoming=true, save on a file/files and use soledad to put it back the way leap-mx does.

We can't put them on the mail queue because they are already wholly encrypted (including headers) and leap-mx can't process them again.

>Re "The first user login after these steps will be slow": since (almost) all docs are already on the local (sqlcipher) copy, and the sync is mainly from client to server, could we do the sync in the background, so the user won't have to wait for so long?

We can't do the sync in the background because of the current architecture. The documents have to be symmetrically encrypted and transferred, we need the user to be logged in for that. That blocks the login process because the first sync is synchronous.

**Comment by thaissiqueira** [comment]
> Won't this run the risk of losing documents if not all documents have been synced?

Considering that we are using only the organization mode, there is a risk of losing the incoming mail, because we will delete the provider docs. To prevent that we are planning to backup the incoming mail.

**Comment by rdevries-thoughtworks** [comment]
> That blocks the login process because the first sync is synchronous.

Is there a conceptual reason that this should be synchronous? Or is this just how it's done today?

**Comment by rdevries-thoughtworks** [comment]
> save on a file/files

I think it's simpler to replicate the incoming documents to a 'backup database' for the user, and then after migration replicate them back.

**Comment by bwagnerr** [comment]
@rdevries-thoughtworks 

> Is there a conceptual reason that this should be synchronous? Or is this just how it's done today?

It needs to be synchronous because we have to decide if we have to create the user secrets/keys or not. Until we have selective sync and can sync only the key info, I don't think we can change that.

> I think it's simpler to replicate the incoming documents to a 'backup database' for the user, and then after migration replicate them back.

I understand you feel it is simpler with your couch experience, but using files is not harder, considering most people know how to do that. If you are the one to develop the migration and you find it easier to use a backup db in couchDB you should still feel free to do so, the steps are not binding :)

**Comment by thaissiqueira** [comment]
Link for migration strategy analysis: 
https://docs.google.com/presentation/d/19k6ihxRsKXm615ADn3MF0Ncl9KctoE_ophc7zDJU-OQ/edit?usp=sharing

**Comment by thaissiqueira** [comment]
We created these following  milestone to apply this strategy: [Encoding migration](https://github.com/pixelated/pixelated-user-agent/milestone/2)
