### ISSUE TITLE
python-gnupg key extension

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#818]
To easily  track https://github.com/isislovecruft/python-gnupg/pull/167

**Comment by ayoyoness** [comment]
This could move slowly so we'll use the branch in the meantime.

**Comment by zariye** [comment]
@ayoyoness did do ur pr on other pr's? it looks kinda overloaded with this 11 commits from 2015 and 16

**Comment by ayoyoness** [comment]
yeah, i made a mistake... the PR was made on top of develop... and the diff is from master... we can fix but I'll wait for kalyi's feedback... he will surely have more comments.
