### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#820]
- Analyse the UI document and prioritize things we can do.

**Comment by tayanefernandes** [comment]
I wrote this document with all the improvements that we gathered. @SweetVirginia and I still have to add more details to each one of this topics.
https://docs.google.com/a/thoughtworks.com/document/d/1aF5dwCkiLu22WuNBaF5-yqR-1xW9bn9luW1mUlbrnt4/edit?usp=sharing

**Comment by tayanefernandes** [comment]
We added more details to each topic, some of them still need a mockup, but we can work on this in the future.

**Comment by tuliocasagrande** [comment]
We added a new bug to the list (long recipients list).

**Comment by varac** [comment]
I reviewed the document, added a few comments and another issue at the bottom.
Looks good ! Is this enought for review ?

**Comment by SweetVirginia** [comment]
Thank you for your inputs, people. Super valuable :D

**Comment by re-nobre** [comment]
hey, @tayanefernandes and @SweetVirginia! 
Thank you for this great document, the screens and images helped a lot to understand what we need to change. I know that it is a high level analysis, but do you think you can estimate the time that we will need to spend to make this changes? I think it can help us to prioritize them. :)

**Comment by SweetVirginia** [comment]
We created issues for all UI improvements, you can find them with the label UI. 

Also, they are in order and briefly estimated at our waffle board :)
