### ISSUE TITLE
Add a border to the attachment button

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#824]
Add a border to the attachment button because thinking in a future mobile user, it would be nice to avoid mouse overs.
![](https://cloud.githubusercontent.com/assets/6019419/20493712/0f51c4dc-b001-11e6-8a2a-8a47e91086ab.png)

**Comment by tayanefernandes** [comment]
I changed to be like this:
<img width="301" alt="screen shot 2016-11-23 at 2 59 32 pm" src="https://cloud.githubusercontent.com/assets/10910322/20571152/7b612982-b18d-11e6-9eb4-e826f718f4ce.png">

**Comment by SweetVirginia** [comment]
<3 Awesome!
