### ISSUE TITLE
Unsigned emails at Pixelated

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#825]
Some Araguaia's mails are arriving to my wazokazi's inbox unsigned. Isn't all Pixelated emails supposed to be signed by default?

It is not all users. Can someone investigate this?

![screen shot 2016-11-24 at 2 12 41 pm](https://cloud.githubusercontent.com/assets/6019419/20605012/60254680-b250-11e6-9a73-f88643812bf8.png)

**Comment by varac** [comment]
I'd really like to prioritize this. This is super irritating for the users.
I mean, the main reason to use pixelated is to have automatic encryption/signing, and when our main features fails, we should worry.

**Comment by SweetVirginia** [comment]
+1 @varac

**Comment by SweetVirginia** [comment]
To describe what is happening a little bit more:

0. Alice's key was published manually (@deniscostadsc  did it) when she created her account. 1. I've sent a signed and encrypted email from my Wazokazi account to Alice's Araguaia account (both Pixelated). 
2. She replied me and it came signed and encrypted and with Bob's Araguaia mail in copy. 
3. When bob replied to me, (Red: Re), it came not signed. 

Also, 
I sent an email to @thaissiqueira 's account from my TW account, I configured my Enigmail to always sign. Thais received my email as unsigned.

**Comment by SweetVirginia** [comment]
Just did a test with @thaissiqueira 

1. I sent an email from my TW account to her Araguaia's Account. - She received not signed and not encrypted. 
2. She replied me with her key attached. I imported to my keychain. 
3. I've sent another email, this time signed and encrypted - She received only encrypted. NOT signed.

**Comment by varac** [comment]
Hi. So in nickserver:0.9 th lookup problems are solved.
I propose that araguaia upgrades from nickerserver:0.8 to nickserver:0.9.
This would be done by adding this to common.json in the provider dir:

```
{
  "sources": {
    "nickserver": {
      "revision": "master"
    }
  }
}

```

then, `leap deploy` would take up the changes update the nickserver version.

**Comment by SweetVirginia** [comment]
Not sure if I understand. It means the bug is solved? ;P

**Comment by varac** [comment]
I'm pretty sure this is related to [nickserver lookups not working properly](https://leap.se/code/issues/8648). This is fixed in latest 0.9 branch/master branch of nickserver.
Before, nickserver-to-nickserver queries (i.e. I write a mail on wazokazi to an araguaia user, and the useragent requests the recipient key from wazokazis nickserver, which then asks araguaias nickserver) were not working. Also, queries inside the domain were buggy as well.
So Araguaia needs to update its nickserver. So the best would be to contact them and ask them to update (who?). 
First, we need to find out which version of the platform they are using, and which version of nickserver:

```
cd PROVIDERCONFIG
grep sources -A12 hiera/* | grep nickserver -A3
leap history --last          
```

With this information, we can guide them best through the upgrade process.

**Comment by varac** [comment]
I wrote a mail to araguaia using our support account on their provider instance.

**Comment by re-nobre** [comment]
hey, @varac!
Did you get some reply from the araguaia sysadmin?

**Comment by varac** [comment]
no :( I send a mail to his gmail address today.

**Comment by varac** [comment]
OK, after talking to the admin latest nickserver:version/0.9 is running now.
This should fix the issue - @SweetVirginia could you pls try again ?

**Comment by SweetVirginia** [comment]
I tested slightly same way as before 

I sent an email from my TW account to Thais' Araguaia Account. She received signed and encrypted. She also replied it signed and encrypted.  
Thais sent me an email from her Araguaia account to my Wazokazi account. We both communicated signed and encrypted. 
I've also asked another Araguaia user I have never communicated through they Araguaia account before and it came also signed. 

With that I can assume that the problem I was observing before is not happening anymore :)

**Comment by varac** [comment]
I also checked using the suporte email account, and all three types of nickserver recipient lookups were successful:

- [x] inside same domain
- [x] querying for an account at another LEAP/Pixelated domain
- [x] keys at an external keyserver

\o/
