### ISSUE TITLE
More feedback at interstitial screen

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#826]
### **Visibility of system status**: 
When we are on the interstitial screen, sometimes it takes a long time mainly if you are doing your first login. We should add messages during the login, to say to the user what the system is doing and why it is taking too long. 

The importance of giving feedback to the user is giving a reason to wait, it doesn't even have to be real. It supposed t be independent if the user want details or not, it is just an interactive waiting time :)

Examples: “Creating Keys”, “Creating secure environment”, “Creating Account”, phrases that can inspire what Pixelated is, why is a little bit different and why is taking time to load...  

Reference:
![image](https://cloud.githubusercontent.com/assets/6019419/20606170/5c974166-b256-11e6-87b1-4a93c5532b4f.png)

Definition of done:
  - TBD with the prototypes.

**Comment by tayanefernandes** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
