### ISSUE TITLE
Tool Tips on "encrypted" and "signed" labels

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#828]
### Visibility of system status

We should add a tooltip on the "encrypted" and "signed" label to inform the user what these flags mean.

It is not supposed to explain all levels of signature like suggested in the issue #388 because most popular and user friendly services that use encryption, usually, hide such complicated information. Also, we discussed a lot on how to simplify that information at issue #758 

So, **FOR NOW**, we will add a simple tool tip with a quick explanation of what those labels mean. Nothing more than that!

<img width="622" alt="screen shot 2016-11-24 at 3 25 23 pm" src="https://cloud.githubusercontent.com/assets/10910322/20606872/0fc94aa0-b25b-11e6-96df-90a4561d2589.png">

Definition of done:
 - TBD with the prototypes.

**Comment by tayanefernandes** [comment]
**Waiting for the tooltip prototype**

**Comment by thaissiqueira** [comment]
@SweetVirginia We already have a tooltip style in our ui:
<img width="468" alt="screen shot 2017-01-19 at 4 11 16 pm" src="https://cloud.githubusercontent.com/assets/13627260/22119358/7785809a-de62-11e6-9420-5dd8ecbb3f0b.png">

We kept the same style, to maintain the visual consistency.

<img width="405" alt="screen shot 2017-01-19 at 4 12 55 pm" src="https://cloud.githubusercontent.com/assets/13627260/22119390/94a3cdbc-de62-11e6-9ba5-86783b4cb09c.png">

Should we change all the tooltips style to be like your prototype or we can keep this?

**Comment by SweetVirginia** [comment]
@thaissiqueira great! I didn't know we had a tooltip, of course, consistency comes first :D 

As we talked, I think this is fine, we may show this to users and get some feedback soon.
