### ISSUE TITLE
Long recipients list is breaking the alignment

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#829]
### Consistency and standards

The broke alignment makes the mail list confusing. 

Current situation:
![screen shot 2016-11-24 at 3 50 18 pm](https://cloud.githubusercontent.com/assets/6019419/20607239/c2477754-b25d-11e6-9e80-b89d1b3e91d2.png)

Definition of done: 
 - The list should be like this image:
![screen shot 2016-11-24 at 3 50 25 pm](https://cloud.githubusercontent.com/assets/6019419/20607240/c248e030-b25d-11e6-947d-2d77bcebefca.png)

**Comment by annacruz** [comment]
Solvend in PR #921
