### ISSUE TITLE
Late feedback after pressing "send" is painful to users

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#830]
### Visibility of system status

After pressing the "send" button when composing an email, takes some time to show a message that the email was sent. This creates some anxiety on our users because they have a moment which they are not sure what happened to their email after they pressed send.

Suggestion:
At the exact time when the user presses the send button, a message "sending email" should appear until it changes to "your message was sent" 

Definition of done:
 - The user should see the message "sending email", following the design bellow:
![screen shot 2016-11-24 at 3 34 28 pm](https://cloud.githubusercontent.com/assets/6019419/20606929/9045d93c-b25b-11e6-8ccc-ddfd44fb1240.png)

**Comment by varac** [comment]
For me it would be important that on success, the box stays a bit longer before it fades away, and on failure it should wait for confirmation.

**Comment by SweetVirginia** [comment]
More on this issue too https://github.com/pixelated/pixelated-user-agent/issues/860 I closed for us to keep talking here. Thank you for your input @varac

**Comment by varac** [comment]
\o/
