### ISSUE TITLE
The tag button is not clickable and it can confuse the user.

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#845]
Definition of done: Make the tag icon be a link and have a "cursor: pointer" like the (+) plus icon.
<img width="130" alt="screen shot 2016-11-24 at 5 32 50 pm" src="https://cloud.githubusercontent.com/assets/10910322/20608784/0e94d80a-b26c-11e6-88e4-7530300aed71.png">

**Comment by tuliocasagrande** [comment]
@tayanefernandes @SweetVirginia 

What should the tag icon do? I can see the box is opened next to the current labels:

<img width="178" alt="screen shot 2016-11-30 at 10 22 12 am" src="https://cloud.githubusercontent.com/assets/1420513/20752187/194db332-b6e7-11e6-8ea2-02a268620f72.png"> 

---

<img width="266" alt="screen shot 2016-11-30 at 10 23 43 am" src="https://cloud.githubusercontent.com/assets/1420513/20752188/194e420c-b6e7-11e6-92cc-ade928235fdc.png">

**Comment by SweetVirginia** [comment]
Hey, the idea is the tag button to be clickable. When the user clicks the tag button it should expect the same behaviour as GitHub Labels: click the button > list of tags and a "filter" field > begin to write tag wanted and it auto-completes with existent or creates a tag > tag the email. 

The plus button will be gone for good. 
Makes sense?

**Comment by anikarni** [comment]
We've agreed this issue involves only switching the functionality from the "plus" icon to the tag icon. The functionality of filtering is now in #886.

**Comment by thaissiqueira** [comment]
The change is already available on production instances.
