### ISSUE TITLE
Text Editor while composing

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#846]
### User control and freedom

As a journalist using Pixelated I want edit fonts, size and colours of my message so I can send to my colleagues the article's content hierarchy already organised. 

Definition of done:  a secure text editor, working (changing font size, style - bold, italic, underline - paragraph, colours), to be defined with prototype and security analysis.  

Example of text editor:
![screen shot 2016-11-24 at 5 39 47 pm](https://cloud.githubusercontent.com/assets/6019419/20608861/0614013c-b26d-11e6-9950-5dfbc3a4131f.png)

This issue is related with Pixelated rendering HTML. Is there an issue for that, yet?

**Comment by tayanefernandes** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
