### ISSUE TITLE
UI Bug: clicking body doesn't move the cursor

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#847]
If a user clicks on the text "Body" in Body of compose email section, the cursor isn't moved to body. This caused a user to click on it multiple times only to fail. The user was confused.

Body is also a not very intuitive section name for a non-tech user. Message should be more clear. 

Definition of done: in place of "body" we should put "message". When the user clicks there, the behaviour expected should be exactly the same when the user clicks "subject".

**Comment by thaissiqueira** [comment]
Reviewed on staging 👍
