### ISSUE TITLE
Change the message "Invalid Credentials"

### ISSUE THREAD

**Issue by tayanefernandes** [pixelated/pixelated-user-agent#849]
Replace this message by "Invalid username or password"
<img width="322" alt="screen shot 2016-11-24 at 6 34 32 pm" src="https://cloud.githubusercontent.com/assets/10910322/20609505/b232cb9a-b274-11e6-9c54-320ee81aeece.png">

Definition of done: We should see the new message.

**Comment by tuliocasagrande** [comment]
🎉

**Comment by zariye** [comment]
🎉

**Comment by re-nobre** [comment]
One comment about this issue that I think is important to clarify:
- in this issue we only change the message, but we still have some errors that are not related with the wrong type of the username or password by the user, but we are giving this feedback error.
