### ISSUE TITLE
Add feedback button on try

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#858]
"As a Pixelated tester I would like to have a place to give feedback about the product I'm testing so I can have a better tool in the future."

During the presentation at Araguaia we realised that we don't have the feedback button on try!!!
😱

Definition of done: feedback button on try visible, clickable and working.

**Comment by tuliocasagrande** [comment]
Take a look: https://github.com/pixelated/pixelated-user-agent/issues/710#issuecomment-225626970

**Comment by tayanefernandes** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
