### ISSUE TITLE
How to notify on (un)successful mail sending

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#860]
When I send a mail, I don't want to stare on the screen and wait for a notification that tells me either " Mail send" or "There was an error sending the mail" for ~20 seconds, because the notification will fade away after ~5 seconds.

I want to send it, turn away, get a coffee, return and still want to be able to know if this mail got sent or not.

Maybe we should notify the user immidiately after sending with "Sending your mail. In case of an error you will get notified".

And in  the case of an error we should have a notification box that needs to get confirmed to fade away.

@vee, how does this sound ?

**Comment by SweetVirginia** [comment]
Hi @varac I totally agree with you, our feedback after pressing send is awful. We have this issue that I think is the same: https://github.com/pixelated/pixelated-user-agent/issues/830 do you agree?

I was thinking about making the yellow notification tab after you press the button always visible giving feedback until it gets sent. Something like "uploading attachments..." (if there's attachments to upload) > "sending message..." > "message sent" or "an error occurred. Try again"

**Comment by varac** [comment]
yes i think they can get merged.

**Comment by SweetVirginia** [comment]
Ok, then the discussion continues here https://github.com/pixelated/pixelated-user-agent/issues/830
