### ISSUE TITLE
Front-end ajax timeouts when sending

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#861]
What
---
When sending a mail with big attachment, the sending might take more than the 60 seconds defined for the front-end ajax request timeout. To have 25MB attachments we need to solve this problem.

The timeout is defined here [monitoredAjax](https://github.com/pixelated/pixelated-user-agent/blob/master/web-ui/app/js/helpers/monitored_ajax.js#L30)
For more context see [this comment](https://github.com/pixelated/pixelated-user-agent/issues/814#issuecomment-262838558)

**Possible solution**: The user-agent should keep the connection alive while processing the request (HTTP KeepAlive)

Definition of done
---
The user agent keeps the connection alive while a mail with 25MB attachments is being sent and we see no timeouts

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
