### ISSUE TITLE
Explore the out of memory problem when receiving 25MB attachments

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#863]
What
---
We created the issues #854 and then #861 and #862 to identify and fix the problems that block us from having 25MB attachments. After those fixes, we still have an OOM (Out of Memory) problem.

We have to explore and understand what is exploding the memory usage so we can fix this bug.

Optimally this issue should be done after Leap merges the streaming branch back to develop and we  merge it to our fork.

More context [here](https://github.com/pixelated/pixelated-user-agent/issues/854#issuecomment-263999138)

Definition of done
---
We identify the biggest sources of memory increase and we create issues to tackle them

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
