### ISSUE TITLE
Increase the message size limits to allow 25MB attachments

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#864]
What
---
After identifying and fixing 25MB attachment issues on #854, #861, #862 and #863, we have to increase the attachment size limit our application accepts.

There are two parts to this:

### Front-end attachment limit is set to 5MB
We need to increase this if we want to send 25MB attachments, pretty straighforward.
The limit is defined here [ATTACHMENT_SIZE_LIMIT](https://github.com/pixelated/pixelated-user-agent/blob/fc4fe7f3efc69a04a7cd11d2a8ec98a68ec76e4d/web-ui/app/js/mail_view/ui/attachment_list.js#L45)

### Postfix message size limit defaults to 10MB
In order to accomodate 25MB attachments, we have to increase the message limit on postfix to 40MB (this considers a 25MB attachment plus 1MB headers and body, encrypted and armored that amounts to 35MB plus 4MB as a safety margin to account for encoding and such)

We have to change on the postfix conf the following option:
```message_size_limit=<new_limit>```

Definition of done
---
An user can send a 25MB attachment using pixelated without receiving attachment limit errors and without errors on postfix because of message size limit

**Comment by tuliocasagrande** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't ake sense to keep this issue open.
