### ISSUE TITLE
Merge our bitmask-dev PRs related to key expiry to our fork

### ISSUE THREAD

**Issue by bwagnerr** [pixelated/pixelated-user-agent#867]
We have three PRs on bitmask-dev

https://0xacab.org/leap/bitmask-dev/merge_requests/46
https://0xacab.org/leap/bitmask-dev/merge_requests/47
https://0xacab.org/leap/bitmask-dev/merge_requests/48

We need those changes in our fork to be able to validate the key expiry (and we won't wait for the PRs for now)

**Comment by thaissiqueira** [comment]
part of #815
