### ISSUE TITLE
Remove uses of stdlib unittests in favor of Twisted trial's unittests

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [pixelated/pixelated-user-agent#869]
Because the unittest of the stdlib doesn't support tests on deferreds, some tests are not actually testing what they seem to test. This can be fixed by using the unittests from Twisted.

**Comment by deniscostadsc** [comment]
After this issue all usages of unittest should be from `twisted.trial`. The only exception are the tests about [performance](https://github.com/pixelated/pixelated-user-agent/tree/master/service/test/perf).

To review just check that.
