### ISSUE TITLE
Hide Gmail HTML attached in messages

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#881]
Pixelated renders the text part and shows the HTML part as an weird attachment. That scares the users, who may think that UNAMED thing was consciously sent from their contact. 

![screen shot 2016-12-12 at 5 00 49 pm](https://cloud.githubusercontent.com/assets/6019419/21112337/923105fc-c08c-11e6-86d6-2d43bc590dbe.png)

Definition of done: no UNAMED attachments from Gmail :)

**Comment by olabini** [comment]
We have a lot of different problems with how we display attachments.
I'm wondering if for this specific issue, we should just take the opportunity and making sure rendering basic HTML works again - that's the real solution after all, and it used to work. #357 might be related to this.

**Comment by tayanefernandes** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
