### ISSUE TITLE
Second welcome mail after renew key

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#895]
***Precondition***: a user with expired key

***Steps to reproduce***

1. Log in on Pixelated with some expired key user;

***Obtained result*** 
This user received a second welcome mail.

***Expected result***
This second welcome mail should not be received.

PS: This behaviour was detected on [key_expiry](https://github.com/pixelated/pixelated-user-agent/tree/key_expiry) branch.

**Comment by thaissiqueira** [comment]
This issue is related with #815

**Comment by tuliocasagrande** [comment]
Fixed on #815.
