### ISSUE TITLE
Handle errors during interstitial

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#907]
We found this problem while working at #815 (renew expired keys).
When the user has any problem during the services setup, the login is interrupted, but the user continues waiting and seeing the interstitial screen, without any feedback.

**Acceptance Criteria:**

- Given I'm logging on Pixelated, when some error occurs during the interstitial time, I should be redirected to the login page and see the error message.

**Comment by tuliocasagrande** [comment]
Related with this:

```
2017-01-18 16:01:47 [pixelated.resources.login_resource] ERROR Login error during expired2 services setup: FirstError[#3, [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'endswith'
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py:434:errback
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:_startRunCallbacks
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
--- <exception caught here> ---
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py:1126:_inlineCallbacks
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
/home/vagrant/.venvs/pixua/src/leap.bitmask/src/leap/bitmask/keymanager/openpgp.py:600:reset_sign_used
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/python/threadpool.py:246:inContext
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/python/threadpool.py:262:<lambda>
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/python/context.py:118:callWithContext
/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/python/context.py:81:callWithContext
/home/vagrant/.venvs/pixua/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py:273:_runInteraction
/home/vagrant/.venvs/pixua/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py:240:_runU1DBQuery
/home/vagrant/.venvs/pixua/src/leap.soledad.common/common/src/leap/soledad/common/l2db/backends/sqlite_backend.py:668:get_from_index
/home/vagrant/.venvs/pixua/src/leap.soledad.common/common/src/leap/soledad/common/l2db/backends/sqlite_backend.py:639:_format_query
]]
```

I noticed we have 5 points of exception while creating a session (`service/pixelated/config/sessions.py`), but only in one of them we have the session closed.

**Comment by olabini** [comment]
Looking at this and the five places:
- _create_dir - this method is never called, so we should remove it - but not a problem.
- _create_database_dir - this exception can only happen before the session is even created, so not a problem
- finish_bootstrap - this already closes
- sync - this doesn't close - but should it close on an exception?
- setup_soledad - this one doesn't close, but we don't have a valid session when this happens, so should it close?

**Comment by olabini** [comment]
PR #915 fixes most of these issues by moving it further up in the call chain. I don't know if that has any effect on the interstitial though.

**Comment by SweetVirginia** [comment]
Hey I just did this idea of a generic "error" message. I am trying to follow the principle of  "human, helpful, humorous and humble" for treating errors. 

There's a lot to improve still, but the team's opinions and suggestions on this would be great. 😄 

![screen shot 2017-02-06 at 5 11 38 pm](https://cloud.githubusercontent.com/assets/6019419/22662213/5e0896b2-ec8f-11e6-9f7c-8e71932e8312.png)

In case you noticed, this error message is totally inconsistent with our current UI. I did it on purpose. This is a move to push Pix to a more friendly aesthetics 😈

**Comment by olabini** [comment]
Would it be possible to have this message show up on the login screen, so a person could try logging in again without having to press "try again"?

**Comment by SweetVirginia** [comment]
Makes much more sense @olabini, this is a modal, so it can be used where ever. I'll prototype a little bit more, I posted it so we can have more feedback ;)

**Comment by olabini** [comment]
Sorry, I'm too literal ;) - I see the image and imagine it being _exactly_ like that. :D

**Comment by SweetVirginia** [comment]
What about now?

![screen shot 2017-02-08 at 4 41 57 pm](https://cloud.githubusercontent.com/assets/6019419/22751906/8ba5ec5c-ee1d-11e6-83e2-6bbf860d06bf.png)

**Comment by SweetVirginia** [comment]
Actually, I prefer this one. 
![screen shot 2017-02-08 at 4 43 07 pm](https://cloud.githubusercontent.com/assets/6019419/22751939/b3733410-ee1d-11e6-83a6-1c9541b2c9a3.png)

**Comment by SweetVirginia** [comment]
Oh, this gave me an idea on how to iterate whart we have now we the new stuff we want to add ;) 

![screen shot 2017-02-08 at 4 46 09 pm](https://cloud.githubusercontent.com/assets/6019419/22752036/1fbf66ca-ee1e-11e6-967f-40b08adb363f.png)

**Comment by tayanefernandes** [comment]
Why don't we use the same text box style from Account Recovery?
![captura de tela 2017-02-09 as 12 47 45 pm](https://cloud.githubusercontent.com/assets/10910322/22788213/2b7218b6-eec6-11e6-8fcf-d5a987d794e8.png)
![captura de tela 2017-02-09 as 12 48 11 pm](https://cloud.githubusercontent.com/assets/10910322/22788214/2b7277d4-eec6-11e6-9924-bae66472ef68.png)

**Comment by SweetVirginia** [comment]
I think that would be awesome, @tayanefernandes :D 
I didn't put the new text box style because I didn't know how much attached that is to the inbox ui, where I know it's difficult to change things.

**Comment by tuliocasagrande** [comment]
#968 is the PR (wip) for that.

We changed to store the login information in the session. It might change, but currently it can be `login_started`, `login_completed` or `login_error`.

We still need to render that awesome page @SweetVirginia created, when an error occurs.

**Comment by SweetVirginia** [comment]
In case you need the SVG of the little dead email: https://codepen.io/SweetVirginia/pen/WRYdQO

**Comment by SweetVirginia** [comment]
There's also the login one, just in case: https://codepen.io/SweetVirginia/pen/NdEXxg

**Comment by SweetVirginia** [comment]
@tuliocasagrande and @anikarni here the mobile idea:
![error](https://cloud.githubusercontent.com/assets/6019419/23137581/7f64e46c-f781-11e6-86c1-dd60dc75a4ce.png)
