### ISSUE TITLE
Restart Pixelated server after package installation

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#918]
# Description

**When** a new Pixelated package is installed
**I want** to have the Pixelated server restarted automatically
**So I can** use all the new features delivered with this new package

# Acceptance Criteria

**Given** a new pixelated package is available
**When** the cron job runs and updates the pixelated package
**Then** the new features should be available for the users on this updated instance.

**Comment by thaissiqueira** [comment]
We changed the last step of acceptance criteria to bring the view of user value.

From:

> **Then** the pixelated service should be restarted

To:

> **Then** the new features should be available for the users on this updated instance.

**Comment by anikarni** [comment]
@deniscostadsc , we came up with two ideas for how to manage the pixelated-server if the pixelated-user-agent is updated:

1. Create a postinst for pixelated that kills the process

If the pixelated-user-agent is updated, it will kill any existing process (pkill). When we use systemd with the pixelated-server, it will restart the service automatically. This way, we won't be concerned with wether we are running the agent as multi-user or single-user.

2. Move the pixelated-server scripts into the user agent

This would involve a bit of redesigning our deploy process to remove the necessity for the pixelated-server, making the agent independent. We can then take advantage of this approach to create a service for multi-user and one for single-user. Plus, one less repo to maintain.

Thoughts? Suggestions?

**Comment by varac** [comment]
@anikarni: I like the second approach!

**Comment by varac** [comment]
On second thought - well, ppl use the pixelated-user-agent debian package standalone on their laptop/vagrant box in activist mode without having pixelated-server installed. It should not be a background service in this case. So having both packages split up makes sense actually.

**Comment by anikarni** [comment]
We can have more than one service, one for single-user, one for multi-user. But there are a lot of advantages of having the debian packaged by itself. One of them being that this story wouldn't have been necessary, since the package would know to update itself.

**Comment by varac** [comment]
@anikarni: Ok, I just want to make sure that we make a service optional for those ppl who install it on their laptop for activist mode and don't want to have it running 24/7. But there are a lot of packages that do this, where you can actually choose to run it as a daemon or not by configuring i.e. `/etc/default/pixelated-user-agent` or sth like this.
