### ISSUE TITLE
Create "add back-up email for existing user" page

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#922]
Existing users still do not have a way to add a back-up account and receive a recovery code. This story is to create a page (that will later be used for the sign-up and "forgot password" functionality) to provide a way to create that code. This flow will not require a password change, but will create the code and send it to the admin and user back-up emails. However, this is just the first story that will be played in the flow, so it does not involve creating the code or sending it yet, just creating the interface for it.

## Acceptance Criteria

Given I'm logged in, when I access the ""add back-up account for existing user"" page, I should see a form to submit my email address.

Given I'm logged out, I should be redirected to login when I try to access this page

Other criteria:
- Responsive
- Mobile first?
- Accessible (semantic HTML, keyboard accessible, voice over and color contrast

Technical criteria:
- Resolve Root conflict
- Implemented in React?

## In Scope

* Design and implement page for existing users
* Require authentication to see this page

## Out of Scope

* Implementation -- should not send email or create recovery code

## Depends on

--

**Comment by SweetVirginia** [comment]
english and Portuguese desktop mockups: https://invis.io/82A9OMMKW

Mobile mockups: https://invis.io/DNA9P1Y2P

For whoever gets this issue for development, please ping me so we can set the assets, transitions and pair <3
