### ISSUE TITLE
Validate back-up email

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#923]
If the user enters an invalid email, we should provide feedback.

## Acceptance Criteria

When I enter an invalid email (invalid characters or no provider), I should see an error message prompting me to verify if I mistyped my email.

## In Scope

* Validation
* Error message

## Depends on

#922

**Comment by tayanefernandes** [comment]
PR: https://github.com/pixelated/pixelated-user-agent/pull/1006
