### ISSUE TITLE
Show error message to user on recovery code error

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#931]
If there is an error during the process of recovery code creation, the user should be informed of such an error. This will require some research and design beforehand.

## Acceptance Criteria

When I add my back-up account and there is an error in creating a recovery code, I should receive feedback that there was an error and I should try again later.

## In Scope

* If setting the recovery code in Soledad fails, the user should be informed
* If updating recovery code in Bonafide fails, the user should be informed

## Out of Scope

* Rolling back the recovery code creation

## Depends on

#930

**Comment by FrailWords** [comment]
![mar-27-2017 14-42-31](https://cloud.githubusercontent.com/assets/1758326/24369896/e1498986-12fb-11e7-9b79-05a2a7a361cc.gif)

SnackBar error style using material-ui.

**Comment by FrailWords** [comment]
If we want to implement the material-ui Snackbar, we can use something like - 

```
          <Snackbar
            open={this.state.status === 'error'}
            bodyStyle={{ backgroundColor: red500 }}
            message={this.state.errorMessage}
            autoHideDuration={0}
            contentStyle={{'text-align': 'center'}}
          />
```

in our component above the footer to display notifications.
