### ISSUE TITLE
Create "forgot password" page

### ISSUE THREAD

**Issue by anikarni** [pixelated/pixelated-user-agent#932]
When the user forgets her password, she should be able to access this page to inform the recovery code. This involves design and implementation, but should not add a link for the user to access it.

## Acceptance Criteria

When I access the "forgot password" page, I should see a form with the recovery code fields (one for the admin code and one for the user code) and email address.

Other criteria:
- Responsive
- Mobile first
- Accessible (semantic HTML, keyboard accessible, voice over and color contrast

Technical criteria:
- Resolve Root conflict
- Implemented in React

## In Scope

* Include fields for recovery code

## Out of Scope

* It should still not be viewable by the user, so this story does not include having a link from the login page
* Should not include setting a back-up account

## Depends on

--

**Comment by anikarni** [comment]
![image](https://cloud.githubusercontent.com/assets/7905650/24221915/f103873a-0f2e-11e7-807c-61e1c496882d.png)

**Comment by SweetVirginia** [comment]
@anikarni hey, mobile prototypes: https://invis.io/YXB1ZMJBG#/226009151_01_M_Forgot_Password

**Comment by SweetVirginia** [comment]
I created this issue to require the email field to be filled, so we don't add an extra step to this flow. https://github.com/pixelated/pixelated-user-agent/issues/1033
