### ISSUE TITLE
Generating and installing debian packages locally

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#951]
As a developer
I want to be able to test debian packages locally on the same way that it is done on pipeline
So I'll not impact all the team changing the packaging pipeline

Docker could be a good solution for this problem 🐳

**Comment by deniscostadsc** [comment]
@varac do you if it's a problem to share the chroot image on the PUA repo? Is there any sensitive information there?

**Comment by varac** [comment]
@deniscostadsc not at all, but the images are quite big and I don't think we should share a chroot in a git repo.

**Comment by varac** [comment]
Done: https://github.com/pixelated/pixelated-user-agent/wiki/Debian-package
