### ISSUE TITLE
New mail is not displayed on first try

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#966]
I just loged into wazokazi, clicked on a new, unread mail but it was not displayed. I only saw "Waiting for wazokazi.is...".

After a while I clicked on an older, read mail what was displayed fine, and afterwards I could read the new mail.

**Comment by tuliocasagrande** [comment]
hey @varac, can you add the time/day you faced this problem? 
It'd be easier to track the log.

**Comment by varac** [comment]
I stepped into this today again.
I attached the logs.

[wazokazi.is.log.txt](https://github.com/pixelated/pixelated-user-agent/files/789683/wazokazi.is.log.txt)

**Comment by tuliocasagrande** [comment]
Hello @varac, thanks for the logs, that helps a lot.

As far as I can see, absolutely **every** error is related with `Failed to encrypt/decrypt: [GNUPG:] NODATA 2`, so it endorses our hypothesis that your unreadable incoming queue is bringing this unstable state (by consuming resources and so on).

Let's see if this problem persists after #981.

**Comment by anikarni** [comment]
Closed due to inactivity after the issue @tuliocasagrande mentioned
