### ISSUE TITLE
Design 404 cute page for Pixelated

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#969]
When doing the Account Recovery MVP, we observed that if the user changes something on the URL, he or she could get a 404 and we didn't have a nice one. 

I got inspired and draw this cute page :) 

Appreciate some feedback. 

![screen shot 2017-02-10 at 4 32 03 pm](https://cloud.githubusercontent.com/assets/6019419/22839593/364c4676-efb1-11e6-9ea3-aa7c4ad4d3bb.png)

**Comment by tuliocasagrande** [comment]
Awesome work, @SweetVirginia 

I'm wondering if a _"page not found"_ or similar would be more suitable then _"something went wrong"_.
What do you think?

**Comment by SweetVirginia** [comment]
Hey @tuliocasagrande 

I changed the text :)   https://invis.io/3AAFI9AB4#/218757793_404

**Comment by SweetVirginia** [comment]
I did some desk check with @anikarni and @tuliocasagrande we all agreed it's cute. 

More iterations on this will happen during development at Issue #977
