### ISSUE TITLE
New incoming mails not signed

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#979]
I just realized that a got a new mail today from @thaissiqueira and it shows up as not signed :o 

See screenshot below

**Comment by varac** [comment]
![screenshot_2017-02-13_16-57-38](https://cloud.githubusercontent.com/assets/488213/22890831/c79df2ba-f20d-11e6-9b2e-84a62647c36d.png)

**Comment by anikarni** [comment]
Related with #997
