### ISSUE TITLE
Mails for accounts with an expired key should bounce and not get deleted

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#982]
If I understoud @tulio correctly, incoming mails for accounts with an expired key are deleted, not bounced. This is a very bad behaviour, they should bounce instead.

**Comment by tuliocasagrande** [comment]
@varac, please, keep in mind to avoid bothering github's tulio account, whoever he is.

**Comment by deniscostadsc** [comment]
I'm closing this issue because #1007 is suppose to solve the same problem.
