### ISSUE TITLE
Form validation for user input errors

### ISSUE THREAD

**Issue by SweetVirginia** [pixelated/pixelated-user-agent#988]
#### "As an user, I would like to know if type something wrong right after typing so I can fix before finishing the task." 

- Show errors for incompatible values during or after a user interacts with a text field.
- In the text field, indicate a fix is needed. Add an error message below.
- If you are performing inline form validation, and the field with the error is clearly marked, the submit button may be disabled until the error is corrected.

### Form behaviour:

![screen shot 2017-02-22 at 4 34 35 pm](https://cloud.githubusercontent.com/assets/6019419/23228860/d6f2ff60-f91c-11e6-9e48-a5c4e5da0e28.png)

**Comment by SweetVirginia** [comment]
#934

**Comment by tayanefernandes** [comment]
The Pixelated team is stopping active development for this project. We hope that it will be picked up in the future though but for now it doesn't make sense to keep this issue open.
